"use strict";this.default_datachannel=this.default_datachannel||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,da,ea;_.n=function(a){return void 0!==a};ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};da=function(a,b,c){return a.call.apply(a.bind,arguments)};
ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.t=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Fd=function(a,c,f){for(var g=Array(arguments.length-2),l=2;l<arguments.length;l++)g[l-2]=arguments[l];return b.prototype[c].apply(a,g)}};
_.ga=function(a,b){var c=a.split("."),d=_.k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.r=function(a,b,c){_.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return _.r.apply(null,arguments)};
_.ia=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ja=function(a){return"function"==ea(a)};_.ka=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.la=function(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ma=function(a){return"array"==ea(a)};_.na=function(){};_.pa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}; _.p(_.pa,Error);_.pa.prototype.name="CustomError";
var ra,ua,ta;ra=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.sa=function(a,b){return-1!=a.indexOf(b)};
ua=function(a,b){for(var c=0,d=ra(String(a)).split("."),e=ra(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var l=d[g]||"",q=e[g]||"",C=RegExp("(\\d*)(\\D*)","g"),L=RegExp("(\\d*)(\\D*)","g");do{var fa=C.exec(l)||["","",""],P=L.exec(q)||["","",""];if(0==fa[0].length&&0==P[0].length)break;c=ta(0==fa[1].length?0:(0,window.parseInt)(fa[1],10),0==P[1].length?0:(0,window.parseInt)(P[1],10))||ta(0==fa[2].length,0==P[2].length)||ta(fa[2],P[2])}while(0==c)}return c}; ta=function(a,b){return a<b?-1:a>b?1:0};
_.u=Array.prototype;_.va=_.u.indexOf?function(a,b,c){return _.u.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.wa=_.u.lastIndexOf?function(a,b,c){return _.u.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.t(a))return _.t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.v=_.u.forEach?function(a,b,c){_.u.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.xa=_.u.filter?function(a,b,c){return _.u.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.t(a)?a.split(""):a,l=0;l<d;l++)if(l in g){var q=g[l];b.call(c,q,l,a)&&(e[f++]=q)}return e};_.ya=_.u.map?function(a,b,c){return _.u.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.za=_.u.reduce?function(a,b,c,d){d&&(b=(0,_.r)(b,d));return _.u.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.v)(a,function(c,g){e=b.call(d,e,c,g,a)});return e};_.Aa=_.u.some?function(a,b,c){return _.u.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Ba=function(a,b){var c=(0,_.va)(a,b),d;(d=0<=c)&&_.u.splice.call(a,c,1);return d};
_.Ca=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var Ea,Ga;_.Da=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Ea=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Fa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Ga=function(a){var b=arguments.length;if(1==b&&_.ma(arguments[0]))return Ga.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var Ha;_.w=function(){};_.x=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.b=0===c?-1:0;a.G=b;t:{if(a.G.length&&(b=a.G.length-1,(c=a.G[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.j=b-a.b;a.c=c;break t}a.j=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.b,a.G[c]=a.G[c]||[]):a.c[c]=a.c[c]||[]};_.y=function(a,b){return b<a.j?a.G[b+a.b]:a.c[b]};_.w.prototype.toString=function(){return this.G.toString()};_.z=function(a,b){Ha[a]=b;b.messageId=a};Ha={};
Ga("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));Ga("action","cite","data","formaction","href","manifest","poster","src");Ga("embed","iframe","link","object","script","style","template");_.Ia="StopIteration"in _.k?_.k.StopIteration:Error("f");_.Ja=function(){};_.Ja.prototype.next=function(){throw _.Ia;};_.Ja.prototype.ha=function(){return this};t:{var Ka=_.k.navigator;if(Ka){var La=Ka.userAgent;if(La){_.A=La;break t}}_.A=""};_.B=function(a,b){this.b={};this.a=[];this.j=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("h");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.B?(c=a.M(),d=a.B()):(c=_.Fa(a),d=Ea(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.B.prototype.V=function(){return this.c};_.B.prototype.B=function(){Ma(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.B.prototype.M=function(){Ma(this);return this.a.concat()};
_.Oa=function(a,b){return Na(a.b,b)};_.B.prototype.P=function(){return 0==this.c};_.B.prototype.clear=function(){this.b={};this.j=this.c=this.a.length=0};_.B.prototype.remove=function(a){return Na(this.b,a)?(delete this.b[a],this.c--,this.j++,this.a.length>2*this.c&&Ma(this),!0):!1};
var Ma=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Na(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Na(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.B.prototype;_.h.get=function(a,b){return Na(this.b,a)?this.b[a]:b};_.h.set=function(a,b){Na(this.b,a)||(this.c++,this.a.push(a),this.j++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
_.h.clone=function(){return new _.B(this)};_.h.ha=function(a){Ma(this);var b=0,c=this.a,d=this.b,e=this.j,f=this,g=new _.Ja;g.next=function(){for(;;){if(e!=f.j)throw Error("i");if(b>=c.length)throw _.Ia;var g=c[b++];return a?g:d[g]}};return g};var Na=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.Pa=function(a){if("function"==typeof a.B)return a.B();if(_.t(a))return a.split("");if(_.la(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ea(a)};
_.Qa=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(_.la(a)||_.t(a))(0,_.v)(a,b,c);else{var d;if("function"==typeof a.M)d=a.M();else if("function"!=typeof a.B)if(_.la(a)||_.t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=_.Fa(a);else d=void 0;for(var e=_.Pa(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};
var Ra,Ta,Ua,Wa,Xa,Ya,$a,ab;Ra=_.sa(_.A,"Opera")||_.sa(_.A,"OPR");_.D=_.sa(_.A,"Trident")||_.sa(_.A,"MSIE");_.Sa=_.sa(_.A,"Gecko")&&!_.sa(_.A.toLowerCase(),"webkit")&&!(_.sa(_.A,"Trident")||_.sa(_.A,"MSIE"));Ta=_.sa(_.A.toLowerCase(),"webkit");Ua=_.k.navigator||null;_.Va=Ua&&Ua.platform||"";Wa=function(){var a=_.k.document;return a?a.documentMode:void 0};
Xa=function(){var a="",b;if(Ra&&_.k.opera)return a=_.k.opera.version,_.ja(a)?a():a;_.Sa?b=/rv\:([^\);]+)(\)|;)/:_.D?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Ta&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(_.A))?a[1]:"");return _.D&&(b=Wa(),b>(0,window.parseFloat)(a))?String(b):a}();Ya={};_.Za=function(a){return Ya[a]||(Ya[a]=0<=ua(Xa,a))};$a=_.k.document;ab=$a&&_.D?Wa()||("CSS1Compat"==$a.compatMode?(0,window.parseInt)(Xa,10):5):void 0;
_.E=function(){this.C=this.C;this.j=this.j};_.E.prototype.C=!1;_.E.prototype.Bb=function(){return this.C};_.E.prototype.D=function(){this.C||(this.C=!0,this.n())};_.G=function(a,b){_.bb(a,_.ha(_.F,b))};_.bb=function(a,b){a.C?b.call(void 0):(a.j||(a.j=[]),a.j.push(_.n(void 0)?(0,_.r)(b,void 0):b))};_.E.prototype.n=function(){if(this.j)for(;this.j.length;)this.j.shift()()};_.F=function(a){a&&"function"==typeof a.D&&a.D()};
_.cb=!_.D||_.D&&9<=ab;!_.Sa&&!_.D||_.D&&_.D&&9<=ab||_.Sa&&_.Za("1.9.1");_.D&&_.Za("9");var db=function(a){db[" "](a);return a};db[" "]=_.na;_.fb=function(a,b){try{return db(a[b]),!0}catch(c){}return!1};var gb,hb;gb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.jb=function(a){if(hb){hb=!1;var b=_.k.location;if(b){var c=b.href;if(c&&(c=_.ib(c))&&c!=b.hostname)throw hb=!0,Error();}}return a.match(gb)};hb=Ta;_.ib=function(a){return(a=_.jb(a)[3]||null)?(0,window.decodeURI)(a):a};
var kb=!_.D||_.D&&9<=ab,lb=_.D&&!_.Za("9");!Ta||_.Za("528");_.Sa&&_.Za("1.9b")||_.D&&_.Za("8")||Ra&&_.Za("9.5")||Ta&&_.Za("528");_.Sa&&!_.Za("8")||_.D&&_.Za("9");_.H=function(a,b){this.type=a;this.b=this.target=b;this.tc=!0};_.H.prototype.Xa=function(){this.tc=!1};var mb=function(a,b){_.H.call(this,a?a.type:"");this.b=this.target=null;this.clientY=this.clientX=this.yb=this.xb=0;this.a=this.state=null;if(a){this.a=a;this.type=a.type;this.target=a.target||a.srcElement;this.b=b;var c=a.relatedTarget;c&&_.Sa&&_.fb(c,"nodeName");Object.defineProperties?Object.defineProperties(this,{xb:{configurable:!0,enumerable:!0,get:this.ac,set:this.wd},yb:{configurable:!0,enumerable:!0,get:this.bc,set:this.xd}}):(this.xb=this.ac(),this.yb=this.bc());this.clientX=void 0!==a.clientX?
a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;a.defaultPrevented&&this.Xa()}};_.p(mb,_.H);_.h=mb.prototype;_.h.Xa=function(){mb.t.Xa.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,lb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};_.h.ac=function(){return Ta||void 0!==this.a.offsetX?this.a.offsetX:this.a.layerX};
_.h.wd=function(a){Object.defineProperties(this,{xb:{writable:!0,enumerable:!0,configurable:!0,value:a}})};_.h.bc=function(){return Ta||void 0!==this.a.offsetY?this.a.offsetY:this.a.layerY};_.h.xd=function(a){Object.defineProperties(this,{yb:{writable:!0,enumerable:!0,configurable:!0,value:a}})};
var nb,pb;nb="closure_listenable_"+(1E6*Math.random()|0);_.ob=function(a){return!(!a||!a[nb])};pb=0;var qb=function(a,b,c,d,e){this.qa=a;this.proxy=null;this.src=b;this.type=c;this.Ua=!!d;this.ab=e;this.key=++pb;this.removed=this.Ta=!1},rb=function(a){a.removed=!0;a.qa=null;a.proxy=null;a.src=null;a.ab=null};var sb=function(a){this.src=a;this.a={};this.b=0};sb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=tb(a,b,d,e);-1<g?(b=a[g],c||(b.Ta=!1)):(b=new qb(b,this.src,f,!!d,e),b.Ta=c,a.push(b));return b};sb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=tb(e,b,c,d);return-1<b?(rb(e[b]),_.u.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var ub=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=_.Ba(a.a[c],b);d&&(rb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};sb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,rb(d[e]);delete this.a[c];this.b--}return b}; var vb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=tb(a,c,d,e));return-1<b?a[b]:null},tb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.qa==b&&f.Ua==!!c&&f.ab==d)return e}return-1};
var wb,xb,yb,Db,Eb,Jb,Ib,Fb,Cb,Kb;wb="closure_lm_"+(1E6*Math.random()|0);xb={};yb=0;_.zb=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)_.zb(a,b[f],c,d,e);return null}c=_.Ab(c);return _.ob(a)?a.listen(b,c,d,e):_.Bb(a,b,c,!1,d,e)};_.Bb=function(a,b,c,d,e,f){if(!b)throw Error("l");var g=!!e,l=Cb(a);l||(a[wb]=l=new sb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=Db();c.proxy=d;d.src=a;d.qa=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Eb(b.toString()),d);yb++;return c};
Db=function(){var a=Fb,b=kb?function(c){return a.call(b.src,b.qa,c)}:function(c){c=a.call(b.src,b.qa,c);if(!c)return c};return b};_.Gb=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)_.Gb(a,b[f],c,d,e);else c=_.Ab(c),_.ob(a)?a.Ib(b,c,d,e):a&&(a=Cb(a))&&(b=vb(a,b,c,!!d,e))&&_.Hb(b)};
_.Hb=function(a){if(_.ka(a)||!a||a.removed)return!1;var b=a.src;if(_.ob(b))return ub(b.U,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ua):b.detachEvent&&b.detachEvent(Eb(c),d);yb--;(c=Cb(b))?(ub(c,a),0==c.b&&(c.src=null,b[wb]=null)):rb(a);return!0};Eb=function(a){return a in xb?xb[a]:xb[a]="on"+a};Jb=function(a,b,c,d){var e=!0;if(a=Cb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ua==c&&!f.removed&&(f=Ib(f,d),e=e&&!1!==f)}return e};
Ib=function(a,b){var c=a.qa,d=a.ab||a.src;a.Ta&&_.Hb(a);return c.call(d,b)};
Fb=function(a,b){if(a.removed)return!0;if(!kb){var c;if(!(c=b))t:{c=["window","event"];for(var d=_.k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new mb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.b;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--){c.b=e[l];var q=Jb(e[l],f,!0,c),d=d&&q}for(l=0;l<e.length;l++)c.b=e[l],q=Jb(e[l],
f,!1,c),d=d&&q}return d}return Ib(a,new mb(b,this))};Cb=function(a){a=a[wb];return a instanceof sb?a:null};Kb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Ab=function(a){if(_.ja(a))return a;a[Kb]||(a[Kb]=function(b){return a.handleEvent(b)});return a[Kb]};
_.Lb=function(a){_.x(this,a,"h_cc",null)};_.p(_.Lb,_.w);_.z("h_cc",_.Lb);_.Lb.prototype.Z=function(){return _.y(this,19)};_.I=function(a){_.E.call(this);this.I=a;this.g={}};_.p(_.I,_.E);var Mb=[];_.I.prototype.listen=function(a,b,c,d){return _.Nb(this,a,b,c,d)};_.Nb=function(a,b,c,d,e,f){_.ma(c)||(c&&(Mb[0]=c.toString()),c=Mb);for(var g=0;g<c.length;g++){var l=_.zb(b,c[g],d||a.handleEvent,e||!1,f||a.I||a);if(!l)break;a.g[l.key]=l}return a};
_.I.prototype.Ib=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)this.Ib(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.I||this,c=_.Ab(c),d=!!d,b=_.ob(a)?vb(a.U,String(b),c,d,e):a?(a=Cb(a))?vb(a,b,c,d,e):null:null,b&&(_.Hb(b),delete this.g[b.key]);return this};_.I.prototype.removeAll=function(){_.Da(this.g,_.Hb);this.g={}};_.I.prototype.n=function(){_.I.t.n.call(this);this.removeAll()};_.I.prototype.handleEvent=function(){throw Error("m");};
var Pb,Qb,Rb;Pb=function(a){_.k.setTimeout(function(){throw a;},0)};_.Sb=function(a,b){var c=a;b&&(c=(0,_.r)(a,b));!_.ja(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(Qb||(Qb=Rb()),Qb(c)):_.k.setImmediate(c)};
Rb=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.sa(_.A,"Presto")&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.r)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.sa(_.A,"Trident")&&!_.sa(_.A,"MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.Tb;c.Tb=null;a()}};return function(a){d.next={Tb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")? function(a){var b=window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};
var Yb=function(a,b){Tb||Ub();Vb||(Tb(),Vb=!0);Wb.push(new Xb(a,b))},Tb,Ub=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve();Tb=function(){a.then(Zb)}}else Tb=function(){_.Sb(Zb)}},Vb=!1,Wb=[],Zb=function(){for(;Wb.length;){var a=Wb;Wb=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Pb(d)}}}Vb=!1},Xb=function(a,b){this.a=a;this.b=b};
_.J=function(){_.E.call(this);this.U=new sb(this);this.L=this;this.u=null};_.p(_.J,_.E);_.J.prototype[nb]=!0;_.h=_.J.prototype;_.h.addEventListener=function(a,b,c,d){_.zb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.Gb(this,a,b,c,d)};_.h.n=function(){_.J.t.n.call(this);this.U&&this.U.removeAll(void 0);this.u=null};_.h.listen=function(a,b,c,d){return this.U.add(String(a),b,!1,c,d)};_.h.Ib=function(a,b,c,d){return this.U.remove(String(a),b,c,d)}; _.h.da=function(a,b,c){a=this.U.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ua==b){var g=f.qa,l=f.ab||f.src;f.Ta&&ub(this.U,f);d=!1!==g.call(l,c)&&d}}return d&&0!=c.tc};
var $b=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},ac=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var cc;cc=function(a,b){this.b=0;this.f=void 0;this.a=this.c=null;this.j=this.e=!1;try{var c=this;a.call(b,function(a){bc(c,2,a)},function(a){bc(c,3,a)})}catch(d){bc(this,3,d)}};_.ec=function(){var a,b=new cc(function(b){a=b});return new dc(b,a)};cc.prototype.then=function(a,b,c){return fc(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};$b(cc);
var ic=function(a){0==a.b&&Yb(function(){var a=new gc(void 0);hc(this,a)},a)},hc=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.Ea)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?hc(c,b):(d=c.a.splice(e,1)[0],jc(c,d,3,b)))}}else bc(a,3,b)},lc=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||kc(a);a.a||(a.a=[]);a.a.push(b)},fc=function(a,b,c,d){var e={Ea:null,nc:null,pc:null};e.Ea=new cc(function(a,g){e.nc=b?function(c){try{var e=b.call(d,c);a(e)}catch(C){g(C)}}:
a;e.pc=c?function(b){try{var e=c.call(d,b);!_.n(e)&&b instanceof gc?g(b):a(e)}catch(C){g(C)}}:g});e.Ea.c=a;lc(a,e);return e.Ea};cc.prototype.g=function(a){this.b=0;bc(this,2,a)};cc.prototype.h=function(a){this.b=0;bc(this,3,a)};
var bc=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(ac(c)){a.b=1;c.then(a.g,a.h,a);return}if(_.ia(c))try{var d=c.then;if(_.ja(d)){mc(a,c,d);return}}catch(e){b=3,c=e}}a.f=c;a.b=b;kc(a);3!=b||c instanceof gc||nc(a,c)}},mc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.g(b))},f=function(b){d||(d=!0,a.h(b))};try{c.call(b,e,f)}catch(g){f(g)}},kc=function(a){a.e||(a.e=!0,Yb(a.k,a))};
cc.prototype.k=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)jc(this,a[b],this.b,this.f)}this.e=!1};var jc=function(a,b,c,d){if(2==c)b.nc(d);else{if(b.Ea)for(;a&&a.j;a=a.c)a.j=!1;b.pc(d)}},nc=function(a,b){a.j=!0;Yb(function(){a.j&&oc.call(null,b)})},oc=Pb,gc=function(a){_.pa.call(this,a)};_.p(gc,_.pa);gc.prototype.name="cancel";var dc=function(a,b){this.b=a;this.a=b};
var pc,qc,rc,sc,tc,uc,vc,yc,zc,Ac,Bc,Cc,Dc;vc=uc=tc=sc=rc=qc=pc=!1;var wc=_.A;wc&&(-1!=wc.indexOf("Firefox")?pc=!0:-1!=wc.indexOf("Camino")?qc=!0:-1!=wc.indexOf("iPad")?sc=!0:-1!=wc.indexOf("iPhone")||-1!=wc.indexOf("iPod")?rc=!0:-1!=wc.indexOf("Chrome")?uc=!0:-1!=wc.indexOf("Android")?tc=!0:-1!=wc.indexOf("Safari")&&(vc=!0));_.xc=pc;yc=qc;zc=rc;Ac=sc;Bc=tc;Cc=uc;Dc=vc;
_.Ec=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.Fc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.Gc=function(a,b){this.j=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.e=null;this.h=b||"u";this.a=this.g=null;this.f=[]};_.Gc.prototype.message=function(){var a={};a.i=this.a;a.m=this.f;a.r=this.h;a.o=this.g;a.s=this.b;a.st=this.c;a.d=this.e;a.dt=this.j;return a};_.ga("ace.base.Message.prototype.message",_.Gc.prototype.message);
_.Hc=function(a,b){for(var c in b)switch(c){case "r":a.h=b[c];break;case "i":a.a=b[c];break;case "m":a.f=b[c];break;case "o":a.g=b[c];break;case "s":a.b=b[c];break;case "d":a.e=b[c];break;case "st":a.c=b[c];break;case "dt":a.j=b[c]}return a};_.Ic=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))};_.Jc=function(a,b){null!=b&&(a.a=b)};_.Kc=function(a,b){"object"==typeof b?a.f=b:a.f=[b]};_.Gc.prototype.source=function(){return this.b};_.Gc.prototype.target=function(){return this.e}; _.Gc.prototype.content=function(){return this.f};
_.Lc=function(a,b,c,d,e){_.E.call(this);this.b=a;this.Qa=b;this.a=typeof b;this.Db=c?c:!1;this.ba=!0;this.zb=d?d:!1;this.qb=e?e:!1};_.p(_.Lc,_.E);_.h=_.Lc.prototype;_.h.n=function(){_.Lc.t.n.call(this);this.b="";this.Qa=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.F=function(){return this.Qa};_.h.setEnabled=function(a){this.ba=a};
var Mc=function(a){return(a=a.exec(_.A))?a[1]:""},Nc=function(){if(_.xc)return Mc(/Firefox\/([0-9.]+)/);if(_.D||Ra)return Xa;if(Cc)return Mc(/Chrome\/([0-9.]+)/);if(Dc)return Mc(/Version\/([0-9.]+)/);if(zc||Ac){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.A))return a[1]+"."+a[2]}else{if(Bc)return(a=Mc(/Android\s+([0-9.]+)/))?a:Mc(/Version\/([0-9.]+)/);if(yc)return Mc(/Camino\/([0-9.]+)/)}return""}();
_.Pc=function(a){_.E.call(this);this.a=new _.B;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&_.Oc(this,a)};_.p(_.Pc,_.E);_.Qc=0<=ua(Nc,"23.0.1262.0")&&!_.Fc();_.Pc.prototype.n=function(){_.Pc.t.n.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)_.F(this.a.get(a[b]));delete this.a};_.Pc.prototype.getItem=function(a){return _.Oa(this.a,a)?this.a.get(a):null};
_.Pc.prototype.setItem=function(a){this.a.set(a.id(),a)};_.Oc=function(a,b){for(var c in b){var d=b[c],e=null;_.Oa(a.a,c)?(e=a.a.get(c),e.Qa=d.value,d.changed&&(e.qb=d.changed)):(e=new _.Lc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.Tc=function(){this.c=new _.B;this.a=null;this.b=!1;this.a=new Rc;this.b=!0;_.Sc(this)};_.Tc.ua=function(){return _.Tc.a?_.Tc.a:_.Tc.a=new _.Tc};_.Sc=function(a,b){var c=b||_.na;a.b?c():window.chrome.storage.local.get((0,_.r)(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};_.Tc.prototype.get=function(a){return this.a.get(a)};_.Tc.prototype.set=function(a,b){var c=_.ec();this.a.set(a,b);c.a(void 0);return c.b};_.Tc.prototype.remove=function(a){this.a.remove(a)};
_.Tc.prototype.clear=function(){this.a.clear()};var Rc=function(){this.a=window.localStorage};Rc.prototype.clear=function(){this.a.clear()};Rc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ha[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a};Rc.prototype.set=function(a,b){var c=null;b instanceof _.w&&(b=b.G,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}}; Rc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
_.Uc=function(a,b){this.b=a;this.a=b;this.constructor.Rb||(this.constructor.Rb={});this.constructor.Rb[this.toString()]=this};_.Uc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};_.K=function(a,b){_.Uc.call(this,a,b)};_.p(_.K,_.Uc);_.Vc=function(a){this.a=a};_.Wc=new _.Vc("lib");_.M=function(a){this.a=a};_.M.prototype.toString=function(){return this.a};_.Xc=new _.M("fJuxOc");_.Yc=new _.M("ZtVrH");_.Zc=new _.M("zZa4xc");_.$c=new _.M("pVbxBc");_.ad=new _.M("byfTOb");_.bd=new _.M("LEikZe");_.cd=new _.M("rJmJrc");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.dd=function(a,b){this.j=[];this.u=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.f=!1;this.e=0;this.h=null;this.q=0};_.dd.prototype.k=function(a,b){this.f=!1;_.ed(this,a,b)};_.ed=function(a,b,c){a.a=!0;a.c=c;a.b=!b;fd(a)};_.hd=function(a){if(a.a){if(!a.l)throw new gd;a.l=!1}};_.dd.prototype.g=function(a){_.hd(this);_.ed(this,!0,a)};_.id=function(a,b,c,d){a.j.push([b,c,d]);a.a&&fd(a)};
_.dd.prototype.then=function(a,b,c){var d,e,f=new cc(function(a,b){d=a;e=b});_.id(this,d,function(a){"undefined"!=typeof _.jd&&a instanceof _.jd?ic(f):e(a)});return f.then(a,b,c)};$b(_.dd);
var kd=function(a){return(0,_.Aa)(a.j,function(a){return _.ja(a[1])})},fd=function(a){if(a.e&&a.a&&kd(a)){var b=a.e,c=ld[b];c&&(_.k.clearTimeout(c.Wa),delete ld[b]);a.e=0}a.h&&(a.h.q--,delete a.h);for(var b=a.c,d=c=!1;a.j.length&&!a.f;){var e=a.j.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var l=f.call(e||a.u,b);_.n(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);ac(b)&&(d=!0,a.f=!0)}catch(q){b=q,a.b=!0,kd(a)||(c=!0)}}a.c=b;d&&(l=(0,_.r)(a.k,a,!0),d=(0,_.r)(a.k,a,!1),b instanceof _.dd?(_.id(b,
l,d),b.p=!0):b.then(l,d));c&&(b=new md(b),ld[b.Wa]=b,a.e=b.Wa)},gd=function(){_.pa.call(this)};_.p(gd,_.pa);gd.prototype.message="Deferred has already fired";gd.prototype.name="AlreadyCalledError";var md=function(a){this.Wa=_.k.setTimeout((0,_.r)(this.b,this),0);this.a=a};md.prototype.b=function(){delete ld[this.Wa];throw this.a;};var ld={};

}catch(e){_._DumpException(e)}
try{
var od;_.nd=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};od=function(a,b){for(var c=_.t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};_.qd=function(a){_.E.call(this);this.c={};this.h={};this.k={};this.e={};this.l={};this.q={};this.p=a?a.ta():new _.J;this.w=!a;this.f=null;a?(this.f=a,this.k=a.k,this.e=a.e,this.h=a.h,this.l=a.l):(0,_.m)();a=pd(this);this!=a&&(a.g?a.g.push(this):a.g=[this])};_.p(_.qd,_.E);var pd=function(a){for(;a.f;)a=a.f;return a};_.qd.prototype.get=function(a){var b=this.b(a);if(null==b)throw new rd(a);return b};
_.qd.prototype.b=function(a){for(var b=this;b;b=b.f){if(b.C)throw Error("q");if(b.c[a])return b.c[a][0];if(b.q[a])break}if(b=this.k[a]){b=b(this);if(null==b)throw Error("r`"+a);this.a(a,b);return b}return null};_.qd.prototype.a=function(a,b,c){if(this.C)c||_.F(b);else{this.c[a]=[b,!c];b=sd(this,this,a);for(c=0;c<b.length;c++)b[c].g(null);delete this.h[a]}};_.qd.prototype.u=function(){var a=_.td;if(!this.c[a])throw Error("s`"+a);var b=this.c[a];delete this.c[a];b[1]&&_.F(b[0])};
var sd=function(a,b,c){var d=[],e=a.e[c];e&&(od(e,function(a){var c;t:{for(c=a.Sb;c;){if(c==b){c=!0;break t}c=c.f}c=!1}c&&(d.push(a.Gd),_.Ba(e,a))}),0==e.length&&delete a.e[c]);return d},ud=function(a,b){a.e&&_.Qa(a.e,function(a,d,e){od(a,function(d){d.Sb==b&&_.Ba(a,d)});0==a.length&&delete e[d]})};
_.qd.prototype.n=function(){if(pd(this)==this){var a=this.g;if(a)for(;a.length;)a[0].D()}else for(var a=pd(this).g,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&"undefined"!=typeof a[0].D&&a[0].D();this.c=null;this.w&&this.p.D();ud(this,this);this.e=null;_.F(this.v);this.q=this.v=null;_.qd.t.n.call(this)};_.qd.prototype.ta=function(){return this.p};var rd=function(a){_.pa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'}; _.p(rd,_.pa);var vd=new _.Vc("fva");new _.K(vd,1);

}catch(e){_._DumpException(e)}
try{
var wd,xd,yd,zd,Ad,Bd,Id,Jd,Kd,Od,Pd,Sd,Td,Ud,Vd,Wd,Xd,Yd,ce;wd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};xd=function(a,b){b.push('"',a.replace(_.Ca,function(a){if(a in wd)return wd[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return wd[a]=e+b.toString(16)}),'"')};yd="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
zd=function(a,b,c){switch(typeof b){case "string":xd(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(_.ma(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),zd(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),xd(e,c),c.push(":"),
zd(a,f,c),d=","));c.push("}");break;case "function":break;default:throw Error("d`"+typeof b);}};Ad=function(){};Bd=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)Bd(a,b[f],c,d,e);return null}c=_.Ab(c);return _.ob(a)?a.U.add(String(b),c,!0,d,e):_.Bb(a,b,c,!0,d,e)};_.N=function(a,b,c){b<a.j?a.G[b+a.b]=c:a.c[b]=c};
_.Cd=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<yd.length;f++)c=yd[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};_.Dd=function(a){var b=[];zd(new Ad,a,b);return b.join("")};_.Ed=function(a,b,c){null!=b&&(a.e=b,null!=c&&(a.j=c))};
_.O=function(a,b){var c,d=a.u;if(d)for(c=[];d;d=d.u)c.push(d);var d=a.L,e=b,f=e.type||e;if(_.t(e))e=new _.H(e,d);else if(e instanceof _.H)e.target=e.target||d;else{var g=e,e=new _.H(f,d);_.Cd(e,g)}var g=!0,l;if(c)for(var q=c.length-1;0<=q;q--)l=e.b=c[q],g=l.da(f,!0,e)&&g;l=e.b=d;g=l.da(f,!0,e)&&g;g=l.da(f,!1,e)&&g;if(c)for(q=0;q<c.length;q++)l=e.b=c[q],g=l.da(f,!1,e)&&g};
_.Fd=function(a,b,c,d,e,f){if(_.ma(c))for(var g=0;g<c.length;g++)_.Fd(a,b,c[g],d,e,f);else{b=Bd(b,c,d||a.handleEvent,e,f||a.I||a);if(!b)return a;a.g[b.key]=b}return a};_.Hd=function(a,b,c){var d=c?c.G:c;a.a[b]=c;_.N(a,b,d)};_.Q=function(a,b,c){if(!a.a[c]){var d=_.y(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};Id=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};Jd=function(a,b){return a?b?(0,window.decodeURI)(a):(0,window.decodeURIComponent)(a):""};
Kd=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?(0,window.decodeURIComponent)(g.replace(/\+/g," ")):"")}};_.Ld=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.Md=function(a){return _.u.concat.apply(_.u,arguments)};_.Nd=function(a,b,c){this.a=a||null;this.b=!!c};
Od=function(a){a.H||(a.H=new _.B,a.O=0,a.a&&Kd(a.a,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};_.h=_.Nd.prototype;_.h.H=null;_.h.O=null;_.h.V=function(){Od(this);return this.O};_.h.add=function(a,b){Od(this);this.a=null;a=Pd(this,a);var c=this.H.get(a);c||this.H.set(a,c=[]);c.push(b);this.O++;return this};_.h.remove=function(a){Od(this);a=Pd(this,a);return _.Oa(this.H,a)?(this.a=null,this.O-=this.H.get(a).length,this.H.remove(a)):!1};
_.h.clear=function(){this.H=this.a=null;this.O=0};_.h.P=function(){Od(this);return 0==this.O};var Qd=function(a,b){Od(a);b=Pd(a,b);return _.Oa(a.H,b)};_.Nd.prototype.M=function(){Od(this);for(var a=this.H.B(),b=this.H.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.Nd.prototype.B=function(a){Od(this);var b=[];if(_.t(a))Qd(this,a)&&(b=_.Md(b,this.H.get(Pd(this,a))));else{a=this.H.B();for(var c=0;c<a.length;c++)b=_.Md(b,a[c])}return b};
_.Nd.prototype.set=function(a,b){Od(this);this.a=null;a=Pd(this,a);Qd(this,a)&&(this.O-=this.H.get(a).length);this.H.set(a,[b]);this.O++;return this};_.Nd.prototype.get=function(a,b){var c=a?this.B(a):[];return 0<c.length?String(c[0]):b};_.Rd=function(a,b,c){a.remove(b);0<c.length&&(a.a=null,a.H.set(Pd(a,b),_.Ld(c)),a.O+=c.length)};
_.Nd.prototype.toString=function(){if(this.a)return this.a;if(!this.H)return"";for(var a=[],b=this.H.M(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.B(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(g)}return this.a=a.join("&")};_.Nd.prototype.clone=function(){var a=new _.Nd;a.a=this.a;this.H&&(a.H=this.H.clone(),a.O=this.O);return a};Pd=function(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c};
Sd=function(a,b){b&&!a.b&&(Od(a),a.a=null,a.H.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.Rd(this,e,a))},a));a.b=b};Td=/#/g;Ud=/[\#\?@]/g;Vd=/[\#\?]/g;Wd=/[\#\?:]/g;Xd=/[#\/\?@]/g;Yd=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,Id),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};_.Zd=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36)};
_.$d=function(a,b){var c;"undefined"!=typeof _.$d&&a instanceof _.$d?(this.ma=_.n(b)?b:a.ma,_.ae(this,a.fa),this.sa=a.sa,this.R=a.R,_.be(this,a.ea),this.N=a.N,ce(this,a.a.clone()),this.la=a.la):a&&(c=_.jb(String(a)))?(this.ma=!!b,_.ae(this,c[1]||"",!0),this.sa=Jd(c[2]||""),this.R=Jd(c[3]||"",!0),_.be(this,c[4]),this.N=Jd(c[5]||"",!0),ce(this,c[6]||"",!0),this.la=Jd(c[7]||"")):(this.ma=!!b,this.a=new _.Nd(null,0,this.ma))};_.h=_.$d.prototype;_.h.fa="";_.h.sa="";_.h.R="";_.h.ea=null;_.h.N="";
_.h.la="";_.h.ma=!1;_.h.toString=function(){var a=[],b=this.fa;b&&a.push(Yd(b,Xd,!0),":");if(b=this.R){a.push("//");var c=this.sa;c&&a.push(Yd(c,Xd,!0),"@");a.push((0,window.encodeURIComponent)(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.ea;null!=b&&a.push(":",String(b))}if(b=this.N)this.R&&"/"!=b.charAt(0)&&a.push("/"),a.push(Yd(b,"/"==b.charAt(0)?Vd:Wd,!0));(b=this.a.toString())&&a.push("?",b);(b=this.la)&&a.push("#",Yd(b,Td));return a.join("")};
_.de=function(a,b){var c=a.clone(),d=!!b.fa;d?_.ae(c,b.fa):d=!!b.sa;d?c.sa=b.sa:d=!!b.R;d?c.R=b.R:d=null!=b.ea;var e=b.N;if(d)_.be(c,b.ea);else if(d=!!b.N){if("/"!=e.charAt(0))if(a.R&&!a.N)e="/"+e;else{var f=c.N.lastIndexOf("/");-1!=f&&(e=c.N.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(_.sa(f,"./")||_.sa(f,"/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),g=[],l=0;l<f.length;){var q=f[l++];"."==q?e&&l==f.length&&g.push(""):".."==q?((1<g.length||1==g.length&&""!=g[0])&&g.pop(),e&&l==
f.length&&g.push("")):(g.push(q),e=!0)}e=g.join("/")}else e=f}d?c.N=e:d=""!==b.a.toString();d?ce(c,Jd(b.a.toString())):d=!!b.la;d&&(c.la=b.la);return c};_.$d.prototype.clone=function(){return new _.$d(this)};_.ae=function(a,b,c){a.fa=c?Jd(b,!0):b;a.fa&&(a.fa=a.fa.replace(/:$/,""))};_.be=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("j`"+b);a.ea=b}else a.ea=null};ce=function(a,b,c){b instanceof _.Nd?(a.a=b,Sd(a.a,a.ma)):(c||(b=Yd(b,Ud)),a.a=new _.Nd(b,0,a.ma))};
_.R=function(a,b,c){a.a.set(b,c)};_.ee=function(a,b,c){_.ma(c)||(c=[String(c)]);_.Rd(a.a,b,c)};_.fe=function(a,b){return a.a.get(b)};_.ge=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.he=function(a,b){return 0<=(0,_.va)(a,b)};
_.ie=function(a,b,c){if(_.ja(a))c&&(a=(0,_.r)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.r)(a.handleEvent,a);else throw Error("n");return 2147483647<b?-1:_.k.setTimeout(a,b||0)};_.je=function(a){_.k.clearTimeout(a)};_.ke=function(a){var b={},c;for(c in a)b[c]=a[c];return b};_.le=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.la(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}}; _.me=function(a,b){var c;t:{c=a.length;for(var d=_.t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break t}c=-1}return 0>c?null:_.t(a)?a.charAt(c):a[c]};
var qe,oe,pe,re;_.ne=function(){};qe=function(a){var b=a.ia,c=function(a){c.t.constructor.call(this,a);var b=this.T.length;this.a=[];for(var d=0;d<b;++d)this.T[d].Hd||(this.a[d]=new this.T[d](a))};_.p(c,b);for(var d=[];a;){if(b=a.ia){b.T&&_.le(d,b.T);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ja(e[f])&&e[f]!==b){var g=!!e[f].Qc,l=oe(f,e,d,g);(g=pe(f,e,l,g))&&(c.prototype[f]=g)}}a=a.t&&a.t.constructor}c.prototype.T=d;return c};
oe=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e};
pe=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.T[c[0]].prototype[a].apply(this,arguments)}:b[a].Sc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var q=this.a[c[e]];if(q=q?q[a].apply(q,d):this.T[c[e]].prototype[a].apply(this,d)){d=q;break t}}d=!1}return d}:b[a].Rc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var q=this.a[c[e]],q=q?q[a].apply(q,
d):this.T[c[e]].prototype[a].apply(this,d);if(null!=q){d=q;break t}}d=void 0}return d}:b[a].lc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var q=this.a[c[e]];q?q[a].apply(q,d):this.T[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],q=0;q<c.length;++q){var C=this.a[c[q]];e.push(C?C[a].apply(C,d):this.T[c[q]].prototype[a].apply(this,d))}return e}:d||b[a].Sc||b[a].Rc||b[a].lc?e=null:e=re;return e};re=function(){return[]}; _.ne.prototype.ub=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var se;_.te=function(a){if(!a.rb){var b;for(b=a.constructor;b&&!b.ia;)b=b.t&&b.t.constructor;b.ia.Wb||(b.ia.Wb=qe(b));b=new b.ia.Wb(a);a.rb=b;a.ub||(a.ub=se)}};se=function(a){return this.rb.ub(a)};var ue=function(){};ue.prototype.a=null;var we=function(a){var b;(b=a.a)||(b={},ve(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var xe,ye=function(){};_.p(ye,ue);var ze=function(a){return(a=ve(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},ve=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("t");}return a.b};xe=new ye;
var Be,Ee,Je,Le,Ke,Ge;_.Ae=function(a){_.J.call(this);this.A=new _.B;this.k=a||null;this.b=!1;this.h=this.a=null;this.q="";this.e=0;this.c=this.p=this.f=this.l=!1;this.v=0;this.g=null;this.I="";this.w=this.aa=!1};_.p(_.Ae,_.J);Be=/^https?$/i;_.Ce=["POST","PUT"];_.De=[];_.Ae.prototype.S=function(){this.D();_.Ba(_.De,this)};
_.Ae.prototype.send=function(a,b,c,d){if(this.a)throw Error("u`"+this.q+"`"+a);b=b?b.toUpperCase():"GET";this.q=a;this.e=0;this.l=!1;this.b=!0;this.a=this.k?ze(this.k):ze(xe);this.h=this.k?we(this.k):we(xe);this.a.onreadystatechange=(0,_.r)(this.J,this);try{this.p=!0,this.a.open(b,String(a),!0),this.p=!1}catch(e){Ee(this);return}a=c||"";var f=this.A.clone();d&&_.Qa(d,function(a,b){f.set(b,a)});d=_.me(f.M(),Fe);c=_.k.FormData&&a instanceof _.k.FormData;!_.he(_.Ce,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.I&&(this.a.responseType=this.I);"withCredentials"in this.a&&(this.a.withCredentials=this.aa);try{Ge(this),0<this.v&&((this.w=He(this.a))?(this.a.timeout=this.v,this.a.ontimeout=(0,_.r)(this.K,this)):this.g=_.ie(this.K,this.v,this)),this.f=!0,this.a.send(a),this.f=!1}catch(g){Ee(this)}};var He=function(a){return _.D&&_.Za(9)&&_.ka(a.timeout)&&_.n(a.ontimeout)},Fe=function(a){return"content-type"==a.toLowerCase()};
_.Ae.prototype.K=function(){"undefined"!=typeof _.aa&&this.a&&(this.e=8,_.O(this,"timeout"),_.Ie(this,8))};Ee=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.e=5;Je(a);Ke(a)};Je=function(a){a.l||(a.l=!0,_.O(a,"complete"),_.O(a,"error"))};_.Ie=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.e=b||7,_.O(a,"complete"),_.O(a,"abort"),Ke(a))};_.Ae.prototype.n=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Ke(this,!0));_.Ae.t.n.call(this)};
_.Ae.prototype.J=function(){this.C||(this.p||this.f||this.c?Le(this):this.W())};_.Ae.prototype.W=function(){Le(this)};Le=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.h[1]||4!=(a.a?a.a.readyState:0)||2!=_.Me(a)))if(a.f&&4==(a.a?a.a.readyState:0))_.ie(a.J,0,a);else if(_.O(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.Ne(a)?(_.O(a,"complete"),_.O(a,"success")):(a.e=6,Je(a))}finally{Ke(a)}}};
Ke=function(a,b){if(a.a){Ge(a);var c=a.a,d=a.h[0]?_.na:null;a.a=null;a.h=null;b||_.O(a,"ready");try{c.onreadystatechange=d}catch(e){}}};Ge=function(a){a.a&&a.w&&(a.a.ontimeout=null);_.ka(a.g)&&(_.je(a.g),a.g=null)};
_.Ne=function(a){var b=_.Me(a),c;t:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break t;default:c=!1}if(!c){if(b=0===b)a=_.jb(String(a.q))[1]||null,!a&&window.self.location&&(a=window.self.location.protocol,a=a.substr(0,a.length-1)),b=!Be.test(a?a.toLowerCase():"");c=b}return c};_.Me=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};_.Oe=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
_.Pe=function(a){_.x(this,a,"h_icr",null)};_.p(_.Pe,_.w);_.z("h_icr",_.Pe);_.Qe=function(a){_.x(this,a,"h_cs",null)};_.p(_.Qe,_.w);_.z("h_cs",_.Qe);_.Qe.prototype.getState=function(){return _.y(this,1)};_.Re=new _.M("HwdKC");
}catch(e){_._DumpException(e)}
try{
_.Se=function(){return window.chrome.runtime.getURL("feedbackdialog.html")};
}catch(e){_._DumpException(e)}
try{
_.k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_description:{message:"Always stay connected with the new desktop app for Hangouts on ChromeOS and Windows."},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},
chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},chrome_app_signin_button:{message:"Sign in"},chrome_app_outdated_title:{message:"Update your Hangouts Chrome app"},chrome_app_outdated_detail:{message:"This app is out of date. There's a newer version available."},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_title_2:{message:"Do you want to quit Hangouts?"},chrome_app_exit_detail:{message:"You will not receive new messages or calls on this device"},
chrome_app_exit_detail_2:{message:"You can also choose to minimize it and continue to receive messages and calls."},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"},chrome_app_exit_minimize:{message:"Minimize"},chrome_app_osx_warning_message:{message:"Hangouts Chrome app is not fully supported on Mac OSX."},chrome_app_osx_warning_ack:{message:"OK, GOT IT"}};

}catch(e){_._DumpException(e)}
try{
var Te=function(a,b){var c,d,e,f;c=window.document;c=b||c;if(c.querySelectorAll&&c.querySelector&&a)return c.querySelectorAll(""+(a?"."+a:""));if(a&&c.getElementsByClassName){var g=c.getElementsByClassName(a);return g}g=c.getElementsByTagName("*");if(a){f={};for(d=e=0;c=g[d];d++){var l=c.className;"function"==typeof l.split&&_.he(l.split(/\s+/),a)&&(f[e++]=c)}f.length=e;return f}return g},Ue=function(a){return a instanceof _.$d?a.clone():new _.$d(a,void 0)},Ve=function(a){_.x(this,a,0,null)};
_.p(Ve,_.w);var We=function(a){_.x(this,a,0,null)};_.p(We,_.w);var Xe=function(a){_.x(this,a,0,null)};_.p(Xe,_.w);var Ye=function(a){_.x(this,a,0,null)};_.p(Ye,_.w);
var Ze=/[?&]($|#)/,$e=/#|$/,af=function(a,b,c,d){for(var e=c.length;0<=(b=a.indexOf(c,b))&&b<d;){var f=a.charCodeAt(b-1);if(38==f||63==f)if(f=a.charCodeAt(b+e),!f||61==f||38==f||35==f)return b;b+=e+1}return-1},bf=function(a){if(a&&"number"==typeof a.length){if(_.ia(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.ja(a))return"function"==typeof a.item}return!1},cf={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",
role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},df=/[\x00&<>"']/,ef=/\x00/g,ff=/'/g,gf=/"/g,hf=/>/g,jf=/</g,kf=/&/g,lf=function(a,b,c){function d(c){c&&b.appendChild(_.t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!_.la(f)||_.ia(f)&&0<f.nodeType?d(f):(0,_.v)(bf(f)?_.Ld(f):f,d)}},mf=function(a,b){_.Da(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in cf?a.setAttribute(cf[d],b):0==d.lastIndexOf("aria-",
0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},nf=function(a){if(!df.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(kf,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(jf,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(hf,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(gf,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(ff,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(ef,"&#0;"));return a},of={LOADING:0,zc:1,Dd:2,Ed:3,ERROR:4,LOADED:5,yc:6},pf=function(a,b,c){for(var d=a.search($e),e=0,f,g=[];0<=(f=af(a,
e,b,d));)g.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);g.push(a.substr(e));a=[g.join("").replace(Ze,"$1"),"&",b];null!=c&&a.push("=",(0,window.encodeURIComponent)(String(c)));a[1]&&(c=a[0],b=c.indexOf("#"),0<=b&&(a.push(c.substr(b)),a[0]=c=c.substr(0,b)),b=c.indexOf("?"),0>b?a[1]="?":b==c.length-1&&(a[1]=void 0));return a.join("")},qf=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},rf=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,
sf=function(a){_.J.call(this);this.c=a;this.a=of.LOADING;this.b=new _.I(this);_.G(this,this.b);this.b.listen(this.c.ta(),"h_cs",this.e)};_.p(sf,_.J);sf.prototype.getState=function(){return this.a};sf.prototype.e=function(a){a=new _.Qe(a.bb);this.a!=a.getState()&&(this.a=a.getState(),_.O(this,"c"))};
var tf=function(a){(a?a:function(){}).Qc=!0},uf=function(a,b,c){var d=arguments,e=window.document,f=d[0],g=d[1];if(!_.cb&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',nf(g.name),'"');if(g.type){f.push(' type="',nf(g.type),'"');var l={};_.Cd(l,g);delete l.type;g=l}f.push(">");f=f.join("")}f=e.createElement(f);g&&(_.t(g)?f.className=g:_.ma(g)?f.className=g.join(" "):mf(f,g));2<d.length&&lf(e,f,d);return f},vf=function(a,b){var c=b||window.document,d=null;c.querySelectorAll&&c.querySelector? d=c.querySelector("."+a):d=Te(a,b)[0];return d||null},wf=function(a){var b;b=b||0;return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,b))}};
var xf=function(a){this.a=a;_.D||(delete this.a.lpu,delete this.a.ppu)},yf=["cn","tp"],zf=function(a,b){var c=null,d;if(_.ja(window.document.postMessage)||_.ja(window.postMessage)||_.D&&window.postMessage)d=1;else if(_.Sa)d=2;else{if(c=_.D){c=!1;try{d=window.opener,window.opener={},c=_.fb(window,"opener"),window.opener=d}catch(e){}}d=c?6:4}c=d;d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new xf(d)};_.ga("GTalk_IFrameChannelConfig.build",zf);
var Af=function(){if(vf("talk_loading_msg")){var a=vf("talk_loading_msg_error");a&&_.nd(a)}},Bf=function(a){var b=vf("talk_loading_msg");if(b){Af();var c=window.document.createElement("DIV");mf(c,{"class":"talk_loading_msg_error",style:"margin: 12px 8px; font-size: 10px"});var d=window.document.createElement("DIV");a="Errors: "+a.join(", ");if("textContent"in d)d.textContent=a;else if(3==d.nodeType)d.data=a;else if(d.firstChild&&3==d.firstChild.nodeType){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild); d.firstChild.data=a}else qf(d),d.appendChild((9==d.nodeType?d:d.ownerDocument||d.document).createTextNode(String(a)));c.appendChild(d);b.appendChild(c)}};
var Cf=function(){};_.p(Cf,_.ne);Cf.prototype.b=function(a){return a};tf(Cf.prototype.b);Cf.prototype.c=function(){return!0};tf(Cf.prototype.c);var Df=function(a){_.x(this,a,0,null)};_.p(Df,_.w);var Ef=function(a,b){var c=new Df;_.N(c,1,b);_.N(c,2,a);return c},Ff=Ef("?",0),Gf=Ef("q",1),Hf=Ef("<",2),If=Ef(">",3),Jf=Ef("~",4),Kf=Ef("s",5),Lf={e:Ff,k:Gf,g:Hf,h:If,f:Jf,l:Kf};var Mf=function(a){_.x(this,a,"ci:dc",null)};_.p(Mf,_.w);_.z("ci:dc",Mf);var Nf=function(a){_.x(this,a,"ci:ec",null)};_.p(Nf,_.w);_.z("ci:ec",Nf);var Of=function(a){return null!=_.y(a,2)?_.y(a,2):!1};var Pf=function(a){this.a=a},Qf=/\s*;\s*/;_.h=Pf.prototype;_.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("v`"+a);if(/[;\r\n]/.test(b))throw Error("w`"+b);_.n(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.m)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.h.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(Qf),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.h.remove=function(a,b,c){var d=_.n(this.get(a));this.set(a,"",0,b,c);return d};_.h.M=function(){return Rf(this).keys};_.h.B=function(){return Rf(this).values};_.h.P=function(){return!this.a.cookie};_.h.V=function(){return this.a.cookie?(this.a.cookie||"").split(Qf).length:0};
_.h.clear=function(){for(var a=Rf(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};var Rf=function(a){a=(a.a.cookie||"").split(Qf);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var Sf=function(a,b,c){_.te(this);var d=this.rb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(0==d.lastIndexOf("https://talkgadget.google.com/talkgadget/",0)){var e=(new Pf(window.document)).get("WCSDBG",""),e=e.split(";")[0],e=e.split("|")[0],f=["plus.google.com"],g=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<e.length&&!_.he(f,e)&&g.test(e)&&(d=Ue(d),d=Ue("https://"+e+d.N).toString())}this.ca=d;this.c=c||new Nf;a.notificationsOnly&&_.N(this.c,1,!0);this.b="0";null!=a.authUser?
this.b=a.authUser:(c=_.fe(new _.$d(window.location.href),"authuser"),null!=c&&(this.b=c));this.j=a.clientUrl||"notifierclient";c=_.fe(Ue(this.j),"authuser");null!=c&&(this.b=c);this.g=a.propertyName||"Google Talk";this.l=a.cssUrl;this.locale=a.locale;this.f=a.debug;this.Ob=a.userJid;this.Mb=a.uiVersion;this.Ic=null!=a.rosterExpanded?a.rosterExpanded:!0;this.L=a.hostLogMinValue;this.Ra=a.hideChat;this.Ec=a.refresh;this.A=a.hideProfileCard;this.K=a.hideStatusMsgs;this.J=a.hideRosterOptions;this.I=a.hideRecentConversations;
this.w=a.hideOTR;this.Bc=a.hostServerMessageCallback||!1;this.W=a.isCentralRoster;this.Dc=a.isFullFrame||!1;this.Hc=a.rosterClass||"talk_roster";this.Ca=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.e=a.parentToken;this.Gc=b||!1;_.n(a.isRtl)||rf.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var l in Lf)b.push(Lf[l].G)}this.q=
a.entityId;this.Nb=a.useQuasarPanels||!1;this.Kb=a.silent||!1;this.Cc=a.ignoreCentralRoster||!1;this.Fc=a.lazy||!1;this.Ac=a.handleProfileLinks||!1;this.S=a.hostSettings;this.h=a.screen;this.p=a.docsConfig;this.aa=a.jsmode;this.Ba=a.moleWidth;this.Aa=a.moleHeight;this.za=a.minimizedMoleHeight||36;this.xc=a.derp;this.Lb=window.location.protocol+"//"+window.location.host;this.v=a.optOutAllowed;this.u=a.legacyTalkSignedIn;this.k=a.conversationId};Cf.t||_.p(Cf,_.ne);Sf.ia=Cf;
var Tf=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp"}};
var Uf=function(a,b,c,d,e){_.E.call(this);this.a=a;this.b=d||window.document;this.c=new _.I(this);_.G(this,this.c);var f=_.A;d=new _.$d(a.ca+a.j);Of(a.c)||(_.R(d,"ts","0"),_.R(d,"re",a.Ic),_.R(d,"ref",a.Ec));_.R(d,"client","sm");_.R(d,"prop",a.g);_.R(d,"nav","true");_.R(d,"fid",a.a);a.f&&_.R(d,"debug",a.f);_.R(d,"os",_.Va);_.R(d,"stime",c);a.Ra&&_.R(d,"hc",a.Ra);for(c=0;c<yf.length;++c);b=_.Dd(b.a);_.R(d,"xpc",b);_.R(d,"ec",_.Dd(a.c.G));a.h&&_.R(d,"screen",a.h);-1!=f.indexOf("MSIE")&&_.R(d,"ua",f);
a.e&&_.R(d,"pvt",a.e);a.Bc&&_.R(d,"hsmc","true");_.n(a.L)&&_.R(d,"logl",a.L);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.R(d,"href",b.join("?")));b=new _.$d(window.location.href);"false"==_.fe(b,"uacheck")&&_.R(d,"uacheck",!1);(f=a.aa)&&_.R(d,"jsmode",f);(f=_.fe(b,"cssmode"))&&_.R(d,"cssmode",f);(f=_.fe(b,"convid"))&&_.R(d,"convid",f);(f=b.a.B("convp"))&&_.ee(d,"convp",f);(f=_.fe(b,"smexp"))&&_.R(d,"smexp",f);f=b.a.B("mods");a.Fc&&
f.push("lazy");e&&(f=_.Md(f,e));0<f.length&&_.R(d,"mods",f.join(","));if(!a.ca||0>a.ca.indexOf("/u/"))(e=_.fe(b,"authuser"))?_.R(d,"authuser",e):null!=a.b&&_.R(d,"authuser",a.b);e=_.fe(b,"eid");/^[\s\xa0]*$/.test(null==e?"":String(e))||_.R(d,"eid",e);e=this.a.q;/^[\s\xa0]*$/.test(null==e?"":String(e))||_.R(d,"eid",this.a.q);null!=this.a.position&&_.R(d,"pos",this.a.position);_.n(a.Mb)&&_.R(d,"uiv",this.a.Mb);a.l&&_.R(d,"css",a.l);e=a.locale||_.fe(b,"hl");null!=e&&_.R(d,"hl",e);_.n(a.Ob)&&_.R(d,"uj",
a.Ob);null!=a.A&&_.R(d,"hpc",a.A);null!=a.K&&_.R(d,"hsm",a.K);null!=a.J&&_.R(d,"hro",a.J);null!=a.I&&_.R(d,"hrc",a.I);null!=a.w&&_.R(d,"hotr",a.w);null!=a.W&&_.R(d,"pop",a.W);a.Gc&&_.R(d,"pal","1");null!=a.Nb&&_.R(d,"uqp",a.Nb);null!=a.v&&_.R(d,"gooa",a.v);null!=a.u&&_.R(d,"gltsi",a.u);null!=a.Kb&&_.R(d,"sl",a.Kb);a.Cc&&_.R(d,"icr","1");a.Ac&&_.R(d,"hpl","1");a.S&&_.R(d,"hs",a.S);a.p&&_.R(d,"dc",_.Dd(a.p.G));null!=a.Ba&&_.R(d,"molew",a.Ba);null!=a.Aa&&_.R(d,"moleh",a.Aa);null!=a.za&&_.R(d,"mmoleh",
a.za);a.xc&&_.R(d,"derp","1");null!=a.Lb&&_.R(d,"two",a.Lb);null!=a.k&&_.R(d,"convid",a.k);_.R(d,"host","1");_.R(d,"zx",_.Zd());this.e=d.toString()};_.p(Uf,_.E);
var Vf=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Hc,a.b.body.appendChild(e));a=(0,_.r)(function(){var a="";this.a.Dc||(a="height:400px");var b=this.b.createElement("iframe");mf(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a});vf("talk_loading_msg",e)||qf(e);e.appendChild(b);a=this.b.getElementById(this.a.a);_.Fd(this.c,a,["load","error"],wf(d),void 0);a.src=this.e.toString();c()},a);window.setTimeout(a,0)};
var Wf=function(a){_.H.call(this,a[0]);this.bb=a};_.p(Wf,_.H);var Xf=function(a){_.x(this,a,"h_ccf",null)};_.p(Xf,_.w);_.z("h_ccf",Xf);var Yf=function(a){_.x(this,a,"h_rtp",null)};_.p(Yf,_.w);_.z("h_rtp",Yf);var Zf=function(a,b){_.E.call(this);this.I=(0,_.m)();this.A=a;this.document=b||window.document;this.a=new Sf(a,!0,a.endpointConfig);this.g=[];this.q=new _.J;this.f=null};_.p(Zf,_.E);Zf.prototype.n=function(){Zf.t.n.call(this);_.je(this.f);this.b&&this.l&&this.b.parentNode.removeEventListener("DOMAttrModified",this.l,!0)};Zf.prototype.e=function(a,b){this.c?this.c[a]&&this.c[a].apply(this.c,Array.prototype.slice.call(arguments,1)):this.g.push(arguments)};
Zf.prototype.h=function(){var a=this.cc().GTalkNotifier;if(a){var b=_.ke(this.A);b.endpointConfig=this.a.c.G;this.c=new a(b,!0);for(a=0;a<this.g.length;a++)this.e.apply(this,this.g[a]);this.g=[];a=(0,_.r)(this.onMessage,this);this.e("_addClientMessageCallback",a);this.e("_addHostBundleMessageCallback",a)}};Zf.prototype.onMessage=function(a){switch(a[0]){case "h_ccf":new Xf(a)}_.O(this.q,new Wf(a))};var $f=function(a,b){a.e("_h",b.G)};_.h=Zf.prototype;_.h.sendMessage=function(a){$f(this,a)};
_.h.ta=function(){return this.q};_.h.cc=function(){return this.document.parentWindow||this.document.defaultView};_.h.Zc=function(a,b){if(b.target==a&&("style"==b.attrName||"class"==b.attrName)){var c=new Yf;$f(this,c)}};_.h.$c=function(){vf("talk_loading_msg",this.document.getElementById(this.a.Ca))&&(this.document.getElementById(this.a.a).style.display="none")};
var ag=function(a){var b=a.a.ca+"host-js",b=pf(b,"prop",a.a.g),c=a.a.aa;c&&(b=pf(b,"jsmode",c));Of(a.a.c)&&(b=pf(b,"b","1"));var b=pf(b,"zx",_.Zd()),d=(0,_.r)(a.h,a),e=uf("script",{type:"text/javascript",src:b}),f=!1;e.onload=e.onreadystatechange=function(){f||e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(f=!0,d())};e.onerror=(0,_.r)(a.u,a,e);a.f&&(_.je(a.f),a.f=null);a.f=_.ie((0,_.r)(function(){null!=this.c||this.v(e)},a),25E3);a.document.body.appendChild(e)};Zf.prototype.u=function(){}; Zf.prototype.v=function(){};
var bg=function(a){if(a.classList)return a.classList;a=a.className;return _.t(a)&&a.match(/\S+/g)||[]},cg=function(a){return a.classList?a.classList.contains("talk_network_warning"):_.he(bg(a),"talk_network_warning")},dg=function(a){a.classList?a.classList.remove("talk_network_warning"):cg(a)&&(a.className=(0,_.xa)(bg(a),function(a){return"talk_network_warning"!=a}).join(" "))};
var eg=function(a,b){this.b=b;this.a=a};eg.prototype.F=function(){return this.a};var fg=function(a){a.a=Math.min(a.b,2*a.a)};var gg=function(a,b,c){var d={},e=null!=_.y(a,1)?_.y(a,1):"talkgadget.google.com",f="";0>e.indexOf("://")&&(f="https://",0<=e.indexOf(":")&&23!=_.y(a,2)&&27!=_.y(a,2)&&(f="http://"));d.clientBaseUrl=f+e+"/talkgadget/_/";d.authUser=null!=_.y(a,8)?_.y(a,8):"0";d.clientUrl="chat";d.propertyName=Tf(_.y(a,2));d.locale=_.y(a,4);d.hideProfileCard=!0;d.parentToken=_.y(a,3);d.isRtl=null!=_.y(a,6)?_.y(a,6):!1;d.lazy=null!=_.y(a,7)?_.y(a,7):!1;d.entityId=_.y(a,9);d.hostSettings=_.y(a,5);d.jsmode=_.y(a,11);d.isFullFrame=
null!=_.y(a,13)?_.y(a,13):!1;d.rosterId=null!=_.y(a,12)?_.y(a,12):"talk_roster";d.rosterIframeIdB=null!=_.y(a,15)?_.y(a,15):"gtn-roster-iframe-id-b";d.derp=!(null==_.y(a,16)||!_.y(a,16));e=_.Q(a,Ve,14);null!=e&&(d.isCentralRoster=null!=_.y(e,1)?_.y(e,1):!1,d.useQuasarPanels=null!=_.y(e,2)?_.y(e,2):!1);e=_.Q(a,Ye,10);null!=e&&(d.moleManagerLeftMargin=_.y(e,1),d.moleManagerMiddleMargin=_.y(e,2),d.moleManagerRightMargin=_.y(e,3),d.moleManagerNoMoleAreaMargin=_.y(e,4),d.moleManagerBoundingElementId=_.y(e,
5),d.moleWidth=_.y(e,6),d.moleHeight=_.y(e,7),d.minimizedMoleHeight=_.y(e,8));e=_.Q(a,Xe,18);null!=e&&(d.optOutAllowed=null!=_.y(e,1)?_.y(e,1):!0,e=_.Q(e,We,3),null!=e&&(d.legacyTalkSignedIn=null!=_.y(e,1)?_.y(e,1):!0));d.uiVersion=2;d.hideStatusMsgs=!0;d.hideRecentConversations=!0;e=new Nf;_.N(e,2,!0);_.N(e,1,!0);_.N(e,3,!1);d.endpointConfig=e;d.ignoreAutomatedRoster=null!=_.y(a,17)?_.y(a,17):!1;d.conversationId=a.Z();d.hostCallback=c;Zf.call(this,d,b);this.p=new eg(5E3,3E5);this.w=null};
_.p(gg,Zf);var hg=function(a,b){var c=1+.5*Math.random();a.w=_.ie(function(){null==this.c&&(_.ge(this.document.body,b)&&this.document.body.removeChild(b),ag(this))},a.p.F()*c,a);fg(a.p)};gg.prototype.v=function(a){Bf(["301"]);hg(this,a)};gg.prototype.u=function(a){var b=vf("talk_loading_msg",this.document.body);b&&(b.classList?b.classList.add("talk_network_warning"):cg(b)||(b.className+=0<b.className.length?" talk_network_warning":"talk_network_warning"));Bf(["302"]);hg(this,a)}; gg.prototype.h=function(){gg.t.h.call(this);var a=vf("talk_loading_msg",this.document.body);a&&dg(a);Af()};gg.prototype.n=function(){gg.t.n.call(this);_.je(this.w)};
var ig=function(a){_.J.call(this);this.c=a?a:null;this.a=null;this.e=!1;this.b=[];this.f=(0,_.r)(this.Kc,this);this.g=(0,_.r)(this.Pb,this);this.h=null};_.p(ig,_.J);var jg=function(a){_.H.call(this,"message");this.message=a};_.p(jg,_.H);_.h=ig.prototype;_.h.n=function(){ig.t.n.call(this);_.je(this.h);this.Pb(!0);for(var a=0;a<this.b.length;++a)_.F(this.b[a]);delete this.b;delete this.f;delete this.g};
_.h.sendMessage=function(a){if(null==a||null==a.message)return!1;_.Ic(a,this.c,"p");this.a&&this.e?this.a.postMessage(a.message()):this.b.push(a);return!0};_.h.connect=function(){if(null==this.c)return!1;try{if(this.a=window.chrome.runtime.connect({name:this.c}),null==this.a)return!1}catch(a){return!1}this.e=!0;this.a.onMessage.addListener(this.f);this.a.onDisconnect.addListener(this.g);for(var b=this.b.shift();null!=b;)_.Ic(b,this.c,"p"),this.a.postMessage(b.message()),b=this.b.shift();return!0};
_.h.Kc=function(a){_.O(this,new jg(_.Hc(new _.Gc,a)))};_.h.Pb=function(a){this.a&&(this.a.onMessage.removeListener(this.f),this.a.onDisconnect.removeListener(this.g),this.a.disconnect(),delete this.a);this.e=!1;a||(this.h=_.ie(this.ud,5E3,this))};_.h.ud=function(){this.connect()?_.O(this,{type:"reconnected"}):_.O(this,{type:"disconnected"})};
var lg=function(a){_.x(this,a,"h_exts",kg)};_.p(lg,_.w);var kg=[2];_.z("h_exts",lg);var mg=function(){_.E.call(this);this.b=" "};_.p(mg,_.E);var ng=function(a,b,c){a.a=c;b=new _.$d(b);b=_.de(b,new _.$d("/talkgadget/_/extension-start"));a=(0,_.r)(a.c,a);c=new _.Ae;_.De.push(c);a&&c.listen("complete",a);c.U.add("ready",c.S,!0,void 0,void 0);c.send(b,void 0,void 0,void 0)};mg.prototype.c=function(a){if(!this.C){this.b="";if(_.Ne(a.target))try{var b=JSON.parse(_.Oe(a.target)),c=new lg(b);this.b=_.y(c,1)||""}catch(d){}this.a&&(this.a(),this.a=null)}};
var og=function(a){_.x(this,a,"h_cp",null)};_.p(og,_.w);_.z("h_cp",og);var pg=function(a){_.x(this,a,"rbc_d",null)};_.p(pg,_.w);_.z("rbc_d",pg);pg.prototype.setTitle=function(a){_.N(this,1,a)};var rg=function(a){_.x(this,a,"h_cd",qg)};_.p(rg,_.w);var qg=[1,4,5];_.z("h_cd",rg);rg.prototype.Z=function(){return _.y(this,2)};var sg=function(a){_.x(this,a,"h_hn",null)};_.p(sg,_.w);_.z("h_hn",sg);var tg=function(a){_.x(this,a,"h_hs",null)};_.p(tg,_.w);_.z("h_hs",tg);var vg=function(a){_.x(this,a,"h_jm",ug)};_.p(vg,_.w);var ug=[2];_.z("h_jm",vg);var wg=function(a){_.x(this,a,"h_oc",null)};_.p(wg,_.w);_.z("h_oc",wg);var xg=function(a){_.x(this,a,"h_opc",null)};_.p(xg,_.w);_.z("h_opc",xg);var yg=function(a){_.x(this,a,"h_ogc",null)};_.p(yg,_.w);_.z("h_ogc",yg);var zg=function(a){_.x(this,a,"h_sc",null)};_.p(zg,_.w);_.z("h_sc",zg);var Bg=function(a){_.x(this,a,"h_ssc",Ag)};_.p(Bg,_.w);var Ag=[5];_.z("h_ssc",Bg);var Dg=function(a){_.x(this,a,"h_sm",Cg)};_.p(Dg,_.w);var Cg=[1,3];_.z("h_sm",Dg);var Eg=function(a){_.J.call(this);this.a=a};_.p(Eg,_.J);var Fg=new _.M("O9EQob");var Gg=function(a){_.x(this,a,"capi:f_cfr",null)};_.p(Gg,_.w);_.z("capi:f_cfr",Gg);var Hg=function(a){_.x(this,a,"capi:f_cvr",null)};_.p(Hg,_.w);_.z("capi:f_cvr",Hg);var Ig=function(a){_.x(this,a,"capi:f_vsm",null)};_.p(Ig,_.w);_.z("capi:f_vsm",Ig);var Jg=function(a){_.x(this,a,"capi:f_ccr",null)};_.p(Jg,_.w);_.z("capi:f_ccr",Jg);var Kg=function(a){_.x(this,a,"capi:f_csm",null)};_.p(Kg,_.w);_.z("capi:f_csm",Kg);var Lg=function(a){_.x(this,a,0,null)};_.p(Lg,_.w);
var Mg=function(a){_.x(this,a,"capi:f_var",null)};_.p(Mg,_.w);_.z("capi:f_var",Mg);Mg.prototype.getState=function(){return _.Q(this,Lg,1)};var Ng=function(a){_.x(this,a,"capi:f_van",null)};_.p(Ng,_.w);_.z("capi:f_van",Ng);Ng.prototype.getState=function(){return _.Q(this,Lg,1)};var Og=function(a){_.x(this,a,0,null)};_.p(Og,_.w);var Pg=function(a){_.x(this,a,"capi:f_vcr",null)};_.p(Pg,_.w);_.z("capi:f_vcr",Pg);Pg.prototype.getState=function(){return _.Q(this,Og,1)};
var Qg=function(a){_.x(this,a,"capi:f_vcn",null)};_.p(Qg,_.w);_.z("capi:f_vcn",Qg);Qg.prototype.getState=function(){return _.Q(this,Og,1)};var Rg=function(a){_.x(this,a,0,null)};_.p(Rg,_.w);var Sg=function(a){_.x(this,a,"capi:f_vcor",null)};_.p(Sg,_.w);_.z("capi:f_vcor",Sg);Sg.prototype.getState=function(){return _.Q(this,Rg,1)};var Tg=function(a){_.x(this,a,"capi:f_vcon",null)};_.p(Tg,_.w);_.z("capi:f_vcon",Tg);Tg.prototype.getState=function(){return _.Q(this,Rg,1)};
var Ug=function(a){_.x(this,a,0,null)};_.p(Ug,_.w);var Vg=function(a){_.x(this,a,"capi:f_vfr",null)};_.p(Vg,_.w);_.z("capi:f_vfr",Vg);Vg.prototype.getState=function(){return _.Q(this,Ug,1)};var Wg=function(a){_.x(this,a,"capi:f_vfn",null)};_.p(Wg,_.w);_.z("capi:f_vfn",Wg);Wg.prototype.getState=function(){return _.Q(this,Ug,1)};var Xg=function(a){_.x(this,a,0,null)};_.p(Xg,_.w);var Yg=function(a){_.x(this,a,"capi:f_vmr",null)};_.p(Yg,_.w);_.z("capi:f_vmr",Yg);
Yg.prototype.getState=function(){return _.Q(this,Xg,1)};var Zg=function(a){_.x(this,a,"capi:f_vmn",null)};_.p(Zg,_.w);_.z("capi:f_vmn",Zg);Zg.prototype.getState=function(){return _.Q(this,Xg,1)};var $g=function(a){_.x(this,a,0,null)};_.p($g,_.w);var ah=function(a){_.x(this,a,"capi:f_vpr",null)};_.p(ah,_.w);_.z("capi:f_vpr",ah);ah.prototype.getState=function(){return _.Q(this,$g,1)};var bh=function(a){_.x(this,a,"capi:f_vpn",null)};_.p(bh,_.w);_.z("capi:f_vpn",bh);
bh.prototype.getState=function(){return _.Q(this,$g,1)};var ch=function(a){_.x(this,a,"capi:f_vsr",null)};_.p(ch,_.w);_.z("capi:f_vsr",ch);var dh=function(a){_.x(this,a,"capi:f_vsn",null)};_.p(dh,_.w);_.z("capi:f_vsn",dh);var eh=function(a){_.x(this,a,"capi:f_vtr",null)};_.p(eh,_.w);_.z("capi:f_vtr",eh);eh.prototype.setTitle=function(a){_.Hd(this,1,a)};var fh=function(a){_.x(this,a,"capi:f_vtn",null)};_.p(fh,_.w);_.z("capi:f_vtn",fh);fh.prototype.setTitle=function(a){_.Hd(this,1,a)};
var gh=function(a){_.x(this,a,0,null)};_.p(gh,_.w);var hh=function(a){_.x(this,a,"capi:f_vvr",null)};_.p(hh,_.w);_.z("capi:f_vvr",hh);hh.prototype.getState=function(){return _.Q(this,gh,1)};var ih=function(a){_.x(this,a,"capi:f_vvn",null)};_.p(ih,_.w);_.z("capi:f_vvn",ih);ih.prototype.getState=function(){return _.Q(this,gh,1)};var jh=function(a){_.x(this,a,0,null)};_.p(jh,_.w);var kh=function(a){_.x(this,a,"capi:f_uvor",null)};_.p(kh,_.w);_.z("capi:f_uvor",kh);
var lh=function(a){_.x(this,a,"capi:f_uvon",null)};_.p(lh,_.w);_.z("capi:f_uvon",lh);var mh=function(a){_.x(this,a,0,null)};_.p(mh,_.w);var nh=function(a){_.x(this,a,"capi:f_sp",null)};_.p(nh,_.w);_.z("capi:f_sp",nh);nh.prototype.getState=function(){return _.Q(this,mh,1)};var oh=function(a){_.x(this,a,"capi:f_spn",null)};_.p(oh,_.w);_.z("capi:f_spn",oh);oh.prototype.getState=function(){return _.Q(this,jh,1)};
var ph=function(a){_.x(this,a,"uvc",null)};_.p(ph,_.w);_.z("uvc",ph);var qh=function(a){_.x(this,a,"capi:clstup",null)};_.p(qh,_.w);_.z("capi:clstup",qh);var rh=function(a){_.x(this,a,"capi:r_clre",null)};_.p(rh,_.w);_.z("capi:r_clre",rh);var sh=function(a){_.x(this,a,"capi:r_rrst",null)};_.p(sh,_.w);_.z("capi:r_rrst",sh);var th=function(a){_.x(this,a,"capi:r_rers",null)};_.p(th,_.w);_.z("capi:r_rers",th);var uh=function(a){_.x(this,a,"capi:r_recl",null)};_.p(uh,_.w);_.z("capi:r_recl",uh);var vh=function(a){_.x(this,a,"capi:r_rstr",null)};_.p(vh,_.w); _.z("capi:r_rstr",vh);
var wh=new _.M("nED8Yb"),xh=new _.M("xclgJb");var yh=function(a){_.x(this,a,"h_ec",null)};_.p(yh,_.w);_.z("h_ec",yh);var zh=function(a){_.x(this,a,"h_fr",null)};_.p(zh,_.w);_.z("h_fr",zh);var Ah=function(a){_.x(this,a,"capii_c_cel",null)};_.p(Ah,_.w);_.z("capii_c_cel",Ah);var Bh=function(a){_.x(this,a,"capi:rfc",null)};_.p(Bh,_.w);_.z("capi:rfc",Bh);var Ch=function(a){_.x(this,a,"capii_c_ucmc",null)};_.p(Ch,_.w);_.z("capii_c_ucmc",Ch);var Dh=function(a){_.x(this,a,"capii_c_rc",null)};_.p(Dh,_.w);_.z("capii_c_rc",Dh);Dh.prototype.Z=function(){return _.y(this,1)};
var Eh=function(a){_.J.call(this);this.c=a.get(wh);this.a=this.f=0;this.e=this.b=!1;a=new _.I(this);_.G(this,a);a.listen(this.c.ta(),"capii_c_ucmc",this.g);this.c.sendMessage(new Ch)};_.p(Eh,_.J);Eh.prototype.g=function(a){a=new Ch(a.bb);this.b||(this.b=!0,this.e&&(_.N(a,5,!0),this.e=!1));var b=this.f!=_.y(a,1);this.f=Number(_.y(a,1));var c=this.a!=_.y(a,2);this.a=Number(_.y(a,2));_.y(a,5)?_.O(this,"g"):(b&&_.O(this,"i"),c&&_.O(this,"h"))};
var Fh=function(a){_.x(this,a,"h_rha",null)};_.p(Fh,_.w);_.z("h_rha",Fh);var Gh=function(a){_.x(this,a,"h_ssf",null)};_.p(Gh,_.w);_.z("h_ssf",Gh);var Hh=function(a,b){_.E.call(this);this.a=new _.I(this);_.G(this,this.a);this.a.listen(a.ta(),"h_ssf",function(a){a=new Gh(a.bb);a=_.y(a,1);var c;if(null!=a&&JSON&&JSON.parse)try{c=JSON.parse(a)}catch(f){}b(c)});var c=new Fh;_.N(c,1,1);$f(a,c)};_.p(Hh,_.E);
var Ih=function(a){_.x(this,a,"h_ext",null)};_.p(Ih,_.w);_.z("h_ext",Ih);var Jh=function(a){_.x(this,a,"h_sru",null)};_.p(Jh,_.w);_.z("h_sru",Jh);var Mh=function(){_.I.call(this);this.b=new _.qd;_.G(this,this.b);this.l=this.f=this.k=this.a=null;this.q=_.Ec("quasar",""+(new Date).getTime());this.c=[];this.e=new ig(this.q);_.G(this,this.e);this.h=null;this.e.connect();_.Nb(this,this.e,"message",this.J,!0,this);this.p=new mg;_.G(this,this.p);this.listen(window,"unload",this.D);this.listen(window,"load",this.v);Kh(this,(0,_.r)(function(){Lh(this,["onHostReady"],"extensionLibrary")},this))},Nh;_.p(Mh,_.I);var Kh=function(a,b){null==a.c?b():a.c.push(b)};
Mh.prototype.v=function(){var a=new _.Pc(_.Tc.ua().get("settings"));this.h=a.b[0];_.F(a);ng(this.p,this.h,(0,_.r)(function(){if(!this.C&&-1!=this.h.lastIndexOf("talkgadget/")){var a=new Nf;_.N(a,2,!0);var a=new _.Lb,c=this.p.b;if(c){_.N(a,3,c);var c=Ue(this.h),d=c.R;null!=c.ea&&(d+=":"+c.ea);_.N(a,1,d);_.N(a,2,23);d=window.chrome.i18n.getMessage("@@ui_locale");_.N(a,4,d);_.N(a,13,!0);_.N(a,17,!0);c=_.fe(c,"jsmode");null!=c&&_.N(a,11,c);c=new Ve;_.N(c,2,!0);_.N(c,1,!0);_.Hd(a,14,c);a=new gg(a,void 0,
(0,_.r)(this.A,this));_.t(void 0)&&(a.a.e=void 0);c=a.a;var e=a.a.ca,d=a.a.b,f=Ue(e),g=f.N;if(0<=g.indexOf("/u/"))d=e;else{e=g.lastIndexOf("_/");if(0>e||e!=g.length-2)g+="_/";f.N="/u/"+d+g;d=f.toString()}c.ca=d;a.a.j=a.a.j.replace("notifierclient","chat");a.k||(c=zf(a.a.ca,a.a.a),a.k=new Uf(a.a,c,a.I,a.document,void 0),_.G(a,a.k));Vf(a.k,a.a.Ca,(0,_.r)(a.$c,a),(0,_.r)(a.e,a,"_rosterIframeLoaded"));_.xc&&(a.b=a.document.createElement("IFRAME"),a.b.id="gth-talk-plugin-frame-id",a.b.name="gth-talk-plugin-frame-id",
a.b.src=a.a.ca+"blank",a.b.style.cssText="width: 0px; height: 0px; position: absolute; top: 0px; left: 0px; visibility:hidden;",a.document.documentElement.appendChild(a.b),a.l=(0,_.r)(a.Zc,a,a.b.parentNode),a.b.parentNode.addEventListener("DOMAttrModified",a.l,!0));ag(a);this.a=a;this.b.a(wh,this.a);this.k=new sf(this.a);this.b.a(_.Re,this.k);this.listen(this.k,"c",this.w);this.f=new Eg(this.a);this.b.a(Fg,this.f);this.l=new Eh(this.b);this.b.a(xh,this.l);this.listen(this.l,"h",this.u);this.u();a=
new Hh(this.a,(0,_.r)(this.K,this));_.G(this,a);this.listen(this.a.ta(),"h_sru",this.L)}else Lh(this,["changeDesktop",3],"desktopManager")}for(;this.c.length;)this.c.shift()();this.c=null},this))};Mh.prototype.A=function(a,b){if("extensionMessage"==a)if("__reload__"==b)window.chrome.runtime.reload();else{var c=new _.Gc;_.Hc(c,JSON.parse(b)||{});this.e.sendMessage(c)}};
Mh.prototype.w=function(){var a;switch(this.k.getState()){case of.LOADING:a=2;break;case of.zc:a=4;break;case of.yc:a=3;break;default:return}Lh(this,["changeDesktop",a],"desktopManager")};
Mh.prototype.J=function(a){Kh(this,(0,_.r)(function(){var b=a.message;switch(b.a){case "onSendHostMessage":var c=new Ih,b=b.content().toString();_.N(c,1,b);this.a&&this.a.sendMessage(c);break;case "onOpenConversation":var b=b.content()[0],c=this.f,d=new wg;_.N(d,1,b);$f(c.a,d);d=new rg;_.N(d,1,[b]);b=new xg;_.Hd(b,1,d);$f(c.a,b);break;case "h_icr":c=b.content()[0],this.f&&(b=this.f,d=new _.Pe,_.N(d,1,c),$f(b.a,d))}},this))};
var Lh=function(a,b,c){var d=new _.Gc;_.Ic(d,a.q,"p");_.Ed(d,"","e");_.Kc(d,b);null!=c&&(d.g=c);_.Jc(d,""+(0,_.m)());a.e.sendMessage(d)};Mh.prototype.K=function(){var a=_.Se();window.open(a)};Mh.prototype.L=function(a){a=new Jh(a.bb);Lh(this,["setRosterUrl",_.y(a,2)],"dataChannelManager")};Mh.prototype.u=function(){Lh(this,["setUnreadIndicator",!!this.l.a],"desktopManager")};
if(!_.n(Nh)||null==Nh||Nh.C)Nh=new Mh;
}catch(e){_._DumpException(e)}
}).call(this,this.default_datachannel);
// Google Inc.
