"use strict";this.default_feedback=this.default_feedback||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,da,ea;_.n=function(a){return void 0!==a};ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};da=function(a,b,c){return a.call.apply(a.bind,arguments)};
ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.t=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Fd=function(a,c,f){for(var g=Array(arguments.length-2),l=2;l<arguments.length;l++)g[l-2]=arguments[l];return b.prototype[c].apply(a,g)}};
_.ga=function(a,b){var c=a.split("."),d=_.k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.r=function(a,b,c){_.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return _.r.apply(null,arguments)};
_.ia=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ja=function(a){return"function"==ea(a)};_.ka=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.la=function(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ma=function(a){return"array"==ea(a)};_.na=function(){};_.pa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}; _.p(_.pa,Error);_.pa.prototype.name="CustomError";
var ra,ua,ta;ra=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.sa=function(a,b){return-1!=a.indexOf(b)};
ua=function(a,b){for(var c=0,d=ra(String(a)).split("."),e=ra(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var l=d[g]||"",q=e[g]||"",C=RegExp("(\\d*)(\\D*)","g"),L=RegExp("(\\d*)(\\D*)","g");do{var fa=C.exec(l)||["","",""],P=L.exec(q)||["","",""];if(0==fa[0].length&&0==P[0].length)break;c=ta(0==fa[1].length?0:(0,window.parseInt)(fa[1],10),0==P[1].length?0:(0,window.parseInt)(P[1],10))||ta(0==fa[2].length,0==P[2].length)||ta(fa[2],P[2])}while(0==c)}return c}; ta=function(a,b){return a<b?-1:a>b?1:0};
_.u=Array.prototype;_.va=_.u.indexOf?function(a,b,c){return _.u.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.wa=_.u.lastIndexOf?function(a,b,c){return _.u.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.t(a))return _.t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.v=_.u.forEach?function(a,b,c){_.u.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.xa=_.u.filter?function(a,b,c){return _.u.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.t(a)?a.split(""):a,l=0;l<d;l++)if(l in g){var q=g[l];b.call(c,q,l,a)&&(e[f++]=q)}return e};_.ya=_.u.map?function(a,b,c){return _.u.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.za=_.u.reduce?function(a,b,c,d){d&&(b=(0,_.r)(b,d));return _.u.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.v)(a,function(c,g){e=b.call(d,e,c,g,a)});return e};_.Aa=_.u.some?function(a,b,c){return _.u.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Ba=function(a,b){var c=(0,_.va)(a,b),d;(d=0<=c)&&_.u.splice.call(a,c,1);return d};
_.Ca=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var Ea,Ga;_.Da=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Ea=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Fa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Ga=function(a){var b=arguments.length;if(1==b&&_.ma(arguments[0]))return Ga.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var Ha;_.w=function(){};_.x=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.b=0===c?-1:0;a.G=b;t:{if(a.G.length&&(b=a.G.length-1,(c=a.G[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.j=b-a.b;a.c=c;break t}a.j=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.b,a.G[c]=a.G[c]||[]):a.c[c]=a.c[c]||[]};_.y=function(a,b){return b<a.j?a.G[b+a.b]:a.c[b]};_.w.prototype.toString=function(){return this.G.toString()};_.z=function(a,b){Ha[a]=b;b.messageId=a};Ha={};
Ga("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));Ga("action","cite","data","formaction","href","manifest","poster","src");Ga("embed","iframe","link","object","script","style","template");_.Ia="StopIteration"in _.k?_.k.StopIteration:Error("f");_.Ja=function(){};_.Ja.prototype.next=function(){throw _.Ia;};_.Ja.prototype.ha=function(){return this};t:{var Ka=_.k.navigator;if(Ka){var La=Ka.userAgent;if(La){_.A=La;break t}}_.A=""};_.B=function(a,b){this.b={};this.a=[];this.j=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("h");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.B?(c=a.M(),d=a.B()):(c=_.Fa(a),d=Ea(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.B.prototype.V=function(){return this.c};_.B.prototype.B=function(){Ma(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.B.prototype.M=function(){Ma(this);return this.a.concat()};
_.Oa=function(a,b){return Na(a.b,b)};_.B.prototype.P=function(){return 0==this.c};_.B.prototype.clear=function(){this.b={};this.j=this.c=this.a.length=0};_.B.prototype.remove=function(a){return Na(this.b,a)?(delete this.b[a],this.c--,this.j++,this.a.length>2*this.c&&Ma(this),!0):!1};
var Ma=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Na(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Na(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.B.prototype;_.h.get=function(a,b){return Na(this.b,a)?this.b[a]:b};_.h.set=function(a,b){Na(this.b,a)||(this.c++,this.a.push(a),this.j++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
_.h.clone=function(){return new _.B(this)};_.h.ha=function(a){Ma(this);var b=0,c=this.a,d=this.b,e=this.j,f=this,g=new _.Ja;g.next=function(){for(;;){if(e!=f.j)throw Error("i");if(b>=c.length)throw _.Ia;var g=c[b++];return a?g:d[g]}};return g};var Na=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.Pa=function(a){if("function"==typeof a.B)return a.B();if(_.t(a))return a.split("");if(_.la(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ea(a)};
_.Qa=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(_.la(a)||_.t(a))(0,_.v)(a,b,c);else{var d;if("function"==typeof a.M)d=a.M();else if("function"!=typeof a.B)if(_.la(a)||_.t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=_.Fa(a);else d=void 0;for(var e=_.Pa(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};
var Ra,Ta,Ua,Wa,Xa,Ya,$a,ab;Ra=_.sa(_.A,"Opera")||_.sa(_.A,"OPR");_.D=_.sa(_.A,"Trident")||_.sa(_.A,"MSIE");_.Sa=_.sa(_.A,"Gecko")&&!_.sa(_.A.toLowerCase(),"webkit")&&!(_.sa(_.A,"Trident")||_.sa(_.A,"MSIE"));Ta=_.sa(_.A.toLowerCase(),"webkit");Ua=_.k.navigator||null;_.Va=Ua&&Ua.platform||"";Wa=function(){var a=_.k.document;return a?a.documentMode:void 0};
Xa=function(){var a="",b;if(Ra&&_.k.opera)return a=_.k.opera.version,_.ja(a)?a():a;_.Sa?b=/rv\:([^\);]+)(\)|;)/:_.D?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Ta&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(_.A))?a[1]:"");return _.D&&(b=Wa(),b>(0,window.parseFloat)(a))?String(b):a}();Ya={};_.Za=function(a){return Ya[a]||(Ya[a]=0<=ua(Xa,a))};$a=_.k.document;ab=$a&&_.D?Wa()||("CSS1Compat"==$a.compatMode?(0,window.parseInt)(Xa,10):5):void 0;
_.E=function(){this.C=this.C;this.j=this.j};_.E.prototype.C=!1;_.E.prototype.Bb=function(){return this.C};_.E.prototype.D=function(){this.C||(this.C=!0,this.n())};_.G=function(a,b){_.bb(a,_.ha(_.F,b))};_.bb=function(a,b){a.C?b.call(void 0):(a.j||(a.j=[]),a.j.push(_.n(void 0)?(0,_.r)(b,void 0):b))};_.E.prototype.n=function(){if(this.j)for(;this.j.length;)this.j.shift()()};_.F=function(a){a&&"function"==typeof a.D&&a.D()};
_.cb=!_.D||_.D&&9<=ab;!_.Sa&&!_.D||_.D&&_.D&&9<=ab||_.Sa&&_.Za("1.9.1");_.D&&_.Za("9");var db=function(a){db[" "](a);return a};db[" "]=_.na;_.fb=function(a,b){try{return db(a[b]),!0}catch(c){}return!1};var gb,hb;gb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.jb=function(a){if(hb){hb=!1;var b=_.k.location;if(b){var c=b.href;if(c&&(c=_.ib(c))&&c!=b.hostname)throw hb=!0,Error();}}return a.match(gb)};hb=Ta;_.ib=function(a){return(a=_.jb(a)[3]||null)?(0,window.decodeURI)(a):a};
var kb=!_.D||_.D&&9<=ab,lb=_.D&&!_.Za("9");!Ta||_.Za("528");_.Sa&&_.Za("1.9b")||_.D&&_.Za("8")||Ra&&_.Za("9.5")||Ta&&_.Za("528");_.Sa&&!_.Za("8")||_.D&&_.Za("9");_.H=function(a,b){this.type=a;this.b=this.target=b;this.tc=!0};_.H.prototype.Xa=function(){this.tc=!1};var mb=function(a,b){_.H.call(this,a?a.type:"");this.b=this.target=null;this.clientY=this.clientX=this.yb=this.xb=0;this.a=this.state=null;if(a){this.a=a;this.type=a.type;this.target=a.target||a.srcElement;this.b=b;var c=a.relatedTarget;c&&_.Sa&&_.fb(c,"nodeName");Object.defineProperties?Object.defineProperties(this,{xb:{configurable:!0,enumerable:!0,get:this.ac,set:this.wd},yb:{configurable:!0,enumerable:!0,get:this.bc,set:this.xd}}):(this.xb=this.ac(),this.yb=this.bc());this.clientX=void 0!==a.clientX?
a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;a.defaultPrevented&&this.Xa()}};_.p(mb,_.H);_.h=mb.prototype;_.h.Xa=function(){mb.t.Xa.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,lb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};_.h.ac=function(){return Ta||void 0!==this.a.offsetX?this.a.offsetX:this.a.layerX};
_.h.wd=function(a){Object.defineProperties(this,{xb:{writable:!0,enumerable:!0,configurable:!0,value:a}})};_.h.bc=function(){return Ta||void 0!==this.a.offsetY?this.a.offsetY:this.a.layerY};_.h.xd=function(a){Object.defineProperties(this,{yb:{writable:!0,enumerable:!0,configurable:!0,value:a}})};
var nb,pb;nb="closure_listenable_"+(1E6*Math.random()|0);_.ob=function(a){return!(!a||!a[nb])};pb=0;var qb=function(a,b,c,d,e){this.qa=a;this.proxy=null;this.src=b;this.type=c;this.Ua=!!d;this.ab=e;this.key=++pb;this.removed=this.Ta=!1},rb=function(a){a.removed=!0;a.qa=null;a.proxy=null;a.src=null;a.ab=null};var sb=function(a){this.src=a;this.a={};this.b=0};sb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=tb(a,b,d,e);-1<g?(b=a[g],c||(b.Ta=!1)):(b=new qb(b,this.src,f,!!d,e),b.Ta=c,a.push(b));return b};sb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=tb(e,b,c,d);return-1<b?(rb(e[b]),_.u.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var ub=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=_.Ba(a.a[c],b);d&&(rb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};sb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,rb(d[e]);delete this.a[c];this.b--}return b}; var vb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=tb(a,c,d,e));return-1<b?a[b]:null},tb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.qa==b&&f.Ua==!!c&&f.ab==d)return e}return-1};
var wb,xb,yb,Db,Eb,Jb,Ib,Fb,Cb,Kb;wb="closure_lm_"+(1E6*Math.random()|0);xb={};yb=0;_.zb=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)_.zb(a,b[f],c,d,e);return null}c=_.Ab(c);return _.ob(a)?a.listen(b,c,d,e):_.Bb(a,b,c,!1,d,e)};_.Bb=function(a,b,c,d,e,f){if(!b)throw Error("l");var g=!!e,l=Cb(a);l||(a[wb]=l=new sb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=Db();c.proxy=d;d.src=a;d.qa=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Eb(b.toString()),d);yb++;return c};
Db=function(){var a=Fb,b=kb?function(c){return a.call(b.src,b.qa,c)}:function(c){c=a.call(b.src,b.qa,c);if(!c)return c};return b};_.Gb=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)_.Gb(a,b[f],c,d,e);else c=_.Ab(c),_.ob(a)?a.Ib(b,c,d,e):a&&(a=Cb(a))&&(b=vb(a,b,c,!!d,e))&&_.Hb(b)};
_.Hb=function(a){if(_.ka(a)||!a||a.removed)return!1;var b=a.src;if(_.ob(b))return ub(b.U,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ua):b.detachEvent&&b.detachEvent(Eb(c),d);yb--;(c=Cb(b))?(ub(c,a),0==c.b&&(c.src=null,b[wb]=null)):rb(a);return!0};Eb=function(a){return a in xb?xb[a]:xb[a]="on"+a};Jb=function(a,b,c,d){var e=!0;if(a=Cb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ua==c&&!f.removed&&(f=Ib(f,d),e=e&&!1!==f)}return e};
Ib=function(a,b){var c=a.qa,d=a.ab||a.src;a.Ta&&_.Hb(a);return c.call(d,b)};
Fb=function(a,b){if(a.removed)return!0;if(!kb){var c;if(!(c=b))t:{c=["window","event"];for(var d=_.k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new mb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.b;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--){c.b=e[l];var q=Jb(e[l],f,!0,c),d=d&&q}for(l=0;l<e.length;l++)c.b=e[l],q=Jb(e[l],
f,!1,c),d=d&&q}return d}return Ib(a,new mb(b,this))};Cb=function(a){a=a[wb];return a instanceof sb?a:null};Kb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Ab=function(a){if(_.ja(a))return a;a[Kb]||(a[Kb]=function(b){return a.handleEvent(b)});return a[Kb]};
_.Lb=function(a){_.x(this,a,"h_cc",null)};_.p(_.Lb,_.w);_.z("h_cc",_.Lb);_.Lb.prototype.Z=function(){return _.y(this,19)};_.I=function(a){_.E.call(this);this.I=a;this.g={}};_.p(_.I,_.E);var Mb=[];_.I.prototype.listen=function(a,b,c,d){return _.Nb(this,a,b,c,d)};_.Nb=function(a,b,c,d,e,f){_.ma(c)||(c&&(Mb[0]=c.toString()),c=Mb);for(var g=0;g<c.length;g++){var l=_.zb(b,c[g],d||a.handleEvent,e||!1,f||a.I||a);if(!l)break;a.g[l.key]=l}return a};
_.I.prototype.Ib=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)this.Ib(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.I||this,c=_.Ab(c),d=!!d,b=_.ob(a)?vb(a.U,String(b),c,d,e):a?(a=Cb(a))?vb(a,b,c,d,e):null:null,b&&(_.Hb(b),delete this.g[b.key]);return this};_.I.prototype.removeAll=function(){_.Da(this.g,_.Hb);this.g={}};_.I.prototype.n=function(){_.I.t.n.call(this);this.removeAll()};_.I.prototype.handleEvent=function(){throw Error("m");};
var Pb,Qb,Rb;Pb=function(a){_.k.setTimeout(function(){throw a;},0)};_.Sb=function(a,b){var c=a;b&&(c=(0,_.r)(a,b));!_.ja(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(Qb||(Qb=Rb()),Qb(c)):_.k.setImmediate(c)};
Rb=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.sa(_.A,"Presto")&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.r)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.sa(_.A,"Trident")&&!_.sa(_.A,"MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.Tb;c.Tb=null;a()}};return function(a){d.next={Tb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")? function(a){var b=window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};
var Yb=function(a,b){Tb||Ub();Vb||(Tb(),Vb=!0);Wb.push(new Xb(a,b))},Tb,Ub=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve();Tb=function(){a.then(Zb)}}else Tb=function(){_.Sb(Zb)}},Vb=!1,Wb=[],Zb=function(){for(;Wb.length;){var a=Wb;Wb=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Pb(d)}}}Vb=!1},Xb=function(a,b){this.a=a;this.b=b};
_.J=function(){_.E.call(this);this.U=new sb(this);this.L=this;this.u=null};_.p(_.J,_.E);_.J.prototype[nb]=!0;_.h=_.J.prototype;_.h.addEventListener=function(a,b,c,d){_.zb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.Gb(this,a,b,c,d)};_.h.n=function(){_.J.t.n.call(this);this.U&&this.U.removeAll(void 0);this.u=null};_.h.listen=function(a,b,c,d){return this.U.add(String(a),b,!1,c,d)};_.h.Ib=function(a,b,c,d){return this.U.remove(String(a),b,c,d)}; _.h.da=function(a,b,c){a=this.U.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ua==b){var g=f.qa,l=f.ab||f.src;f.Ta&&ub(this.U,f);d=!1!==g.call(l,c)&&d}}return d&&0!=c.tc};
var $b=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},ac=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var cc;cc=function(a,b){this.b=0;this.f=void 0;this.a=this.c=null;this.j=this.e=!1;try{var c=this;a.call(b,function(a){bc(c,2,a)},function(a){bc(c,3,a)})}catch(d){bc(this,3,d)}};_.ec=function(){var a,b=new cc(function(b){a=b});return new dc(b,a)};cc.prototype.then=function(a,b,c){return fc(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};$b(cc);
var ic=function(a){0==a.b&&Yb(function(){var a=new gc(void 0);hc(this,a)},a)},hc=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.Ea)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?hc(c,b):(d=c.a.splice(e,1)[0],jc(c,d,3,b)))}}else bc(a,3,b)},lc=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||kc(a);a.a||(a.a=[]);a.a.push(b)},fc=function(a,b,c,d){var e={Ea:null,nc:null,pc:null};e.Ea=new cc(function(a,g){e.nc=b?function(c){try{var e=b.call(d,c);a(e)}catch(C){g(C)}}:
a;e.pc=c?function(b){try{var e=c.call(d,b);!_.n(e)&&b instanceof gc?g(b):a(e)}catch(C){g(C)}}:g});e.Ea.c=a;lc(a,e);return e.Ea};cc.prototype.g=function(a){this.b=0;bc(this,2,a)};cc.prototype.h=function(a){this.b=0;bc(this,3,a)};
var bc=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(ac(c)){a.b=1;c.then(a.g,a.h,a);return}if(_.ia(c))try{var d=c.then;if(_.ja(d)){mc(a,c,d);return}}catch(e){b=3,c=e}}a.f=c;a.b=b;kc(a);3!=b||c instanceof gc||nc(a,c)}},mc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.g(b))},f=function(b){d||(d=!0,a.h(b))};try{c.call(b,e,f)}catch(g){f(g)}},kc=function(a){a.e||(a.e=!0,Yb(a.k,a))};
cc.prototype.k=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)jc(this,a[b],this.b,this.f)}this.e=!1};var jc=function(a,b,c,d){if(2==c)b.nc(d);else{if(b.Ea)for(;a&&a.j;a=a.c)a.j=!1;b.pc(d)}},nc=function(a,b){a.j=!0;Yb(function(){a.j&&oc.call(null,b)})},oc=Pb,gc=function(a){_.pa.call(this,a)};_.p(gc,_.pa);gc.prototype.name="cancel";var dc=function(a,b){this.b=a;this.a=b};
var pc,qc,rc,sc,tc,uc,vc,yc,zc,Ac,Bc,Cc,Dc;vc=uc=tc=sc=rc=qc=pc=!1;var wc=_.A;wc&&(-1!=wc.indexOf("Firefox")?pc=!0:-1!=wc.indexOf("Camino")?qc=!0:-1!=wc.indexOf("iPad")?sc=!0:-1!=wc.indexOf("iPhone")||-1!=wc.indexOf("iPod")?rc=!0:-1!=wc.indexOf("Chrome")?uc=!0:-1!=wc.indexOf("Android")?tc=!0:-1!=wc.indexOf("Safari")&&(vc=!0));_.xc=pc;yc=qc;zc=rc;Ac=sc;Bc=tc;Cc=uc;Dc=vc;
_.Ec=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.Fc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.Gc=function(a,b){this.j=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.e=null;this.h=b||"u";this.a=this.g=null;this.f=[]};_.Gc.prototype.message=function(){var a={};a.i=this.a;a.m=this.f;a.r=this.h;a.o=this.g;a.s=this.b;a.st=this.c;a.d=this.e;a.dt=this.j;return a};_.ga("ace.base.Message.prototype.message",_.Gc.prototype.message);
_.Hc=function(a,b){for(var c in b)switch(c){case "r":a.h=b[c];break;case "i":a.a=b[c];break;case "m":a.f=b[c];break;case "o":a.g=b[c];break;case "s":a.b=b[c];break;case "d":a.e=b[c];break;case "st":a.c=b[c];break;case "dt":a.j=b[c]}return a};_.Ic=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))};_.Jc=function(a,b){null!=b&&(a.a=b)};_.Kc=function(a,b){"object"==typeof b?a.f=b:a.f=[b]};_.Gc.prototype.source=function(){return this.b};_.Gc.prototype.target=function(){return this.e}; _.Gc.prototype.content=function(){return this.f};
_.Lc=function(a,b,c,d,e){_.E.call(this);this.b=a;this.Qa=b;this.a=typeof b;this.Db=c?c:!1;this.ba=!0;this.zb=d?d:!1;this.qb=e?e:!1};_.p(_.Lc,_.E);_.h=_.Lc.prototype;_.h.n=function(){_.Lc.t.n.call(this);this.b="";this.Qa=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.F=function(){return this.Qa};_.h.setEnabled=function(a){this.ba=a};
var Mc=function(a){return(a=a.exec(_.A))?a[1]:""},Nc=function(){if(_.xc)return Mc(/Firefox\/([0-9.]+)/);if(_.D||Ra)return Xa;if(Cc)return Mc(/Chrome\/([0-9.]+)/);if(Dc)return Mc(/Version\/([0-9.]+)/);if(zc||Ac){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.A))return a[1]+"."+a[2]}else{if(Bc)return(a=Mc(/Android\s+([0-9.]+)/))?a:Mc(/Version\/([0-9.]+)/);if(yc)return Mc(/Camino\/([0-9.]+)/)}return""}();
_.Pc=function(a){_.E.call(this);this.a=new _.B;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&_.Oc(this,a)};_.p(_.Pc,_.E);_.Qc=0<=ua(Nc,"23.0.1262.0")&&!_.Fc();_.Pc.prototype.n=function(){_.Pc.t.n.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)_.F(this.a.get(a[b]));delete this.a};_.Pc.prototype.getItem=function(a){return _.Oa(this.a,a)?this.a.get(a):null};
_.Pc.prototype.setItem=function(a){this.a.set(a.id(),a)};_.Oc=function(a,b){for(var c in b){var d=b[c],e=null;_.Oa(a.a,c)?(e=a.a.get(c),e.Qa=d.value,d.changed&&(e.qb=d.changed)):(e=new _.Lc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.Tc=function(){this.c=new _.B;this.a=null;this.b=!1;this.a=new Rc;this.b=!0;_.Sc(this)};_.Tc.ua=function(){return _.Tc.a?_.Tc.a:_.Tc.a=new _.Tc};_.Sc=function(a,b){var c=b||_.na;a.b?c():window.chrome.storage.local.get((0,_.r)(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};_.Tc.prototype.get=function(a){return this.a.get(a)};_.Tc.prototype.set=function(a,b){var c=_.ec();this.a.set(a,b);c.a(void 0);return c.b};_.Tc.prototype.remove=function(a){this.a.remove(a)};
_.Tc.prototype.clear=function(){this.a.clear()};var Rc=function(){this.a=window.localStorage};Rc.prototype.clear=function(){this.a.clear()};Rc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ha[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a};Rc.prototype.set=function(a,b){var c=null;b instanceof _.w&&(b=b.G,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}}; Rc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
_.Uc=function(a,b){this.b=a;this.a=b;this.constructor.Rb||(this.constructor.Rb={});this.constructor.Rb[this.toString()]=this};_.Uc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};_.K=function(a,b){_.Uc.call(this,a,b)};_.p(_.K,_.Uc);_.Vc=function(a){this.a=a};_.Wc=new _.Vc("lib");_.M=function(a){this.a=a};_.M.prototype.toString=function(){return this.a};_.Xc=new _.M("fJuxOc");_.Yc=new _.M("ZtVrH");_.Zc=new _.M("zZa4xc");_.$c=new _.M("pVbxBc");_.ad=new _.M("byfTOb");_.bd=new _.M("LEikZe");_.cd=new _.M("rJmJrc");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.dd=function(a,b){this.j=[];this.u=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.f=!1;this.e=0;this.h=null;this.q=0};_.dd.prototype.k=function(a,b){this.f=!1;_.ed(this,a,b)};_.ed=function(a,b,c){a.a=!0;a.c=c;a.b=!b;fd(a)};_.hd=function(a){if(a.a){if(!a.l)throw new gd;a.l=!1}};_.dd.prototype.g=function(a){_.hd(this);_.ed(this,!0,a)};_.id=function(a,b,c,d){a.j.push([b,c,d]);a.a&&fd(a)};
_.dd.prototype.then=function(a,b,c){var d,e,f=new cc(function(a,b){d=a;e=b});_.id(this,d,function(a){"undefined"!=typeof _.jd&&a instanceof _.jd?ic(f):e(a)});return f.then(a,b,c)};$b(_.dd);
var kd=function(a){return(0,_.Aa)(a.j,function(a){return _.ja(a[1])})},fd=function(a){if(a.e&&a.a&&kd(a)){var b=a.e,c=ld[b];c&&(_.k.clearTimeout(c.Wa),delete ld[b]);a.e=0}a.h&&(a.h.q--,delete a.h);for(var b=a.c,d=c=!1;a.j.length&&!a.f;){var e=a.j.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var l=f.call(e||a.u,b);_.n(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);ac(b)&&(d=!0,a.f=!0)}catch(q){b=q,a.b=!0,kd(a)||(c=!0)}}a.c=b;d&&(l=(0,_.r)(a.k,a,!0),d=(0,_.r)(a.k,a,!1),b instanceof _.dd?(_.id(b,
l,d),b.p=!0):b.then(l,d));c&&(b=new md(b),ld[b.Wa]=b,a.e=b.Wa)},gd=function(){_.pa.call(this)};_.p(gd,_.pa);gd.prototype.message="Deferred has already fired";gd.prototype.name="AlreadyCalledError";var md=function(a){this.Wa=_.k.setTimeout((0,_.r)(this.b,this),0);this.a=a};md.prototype.b=function(){delete ld[this.Wa];throw this.a;};var ld={};

}catch(e){_._DumpException(e)}
try{
var wd,xd,yd,zd,Ad,Bd,Id,Jd,Kd,Od,Pd,Sd,Td,Ud,Vd,Wd,Xd,Yd,ce;wd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};xd=function(a,b){b.push('"',a.replace(_.Ca,function(a){if(a in wd)return wd[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return wd[a]=e+b.toString(16)}),'"')};yd="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
zd=function(a,b,c){switch(typeof b){case "string":xd(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(_.ma(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),zd(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),xd(e,c),c.push(":"),
zd(a,f,c),d=","));c.push("}");break;case "function":break;default:throw Error("d`"+typeof b);}};Ad=function(){};Bd=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)Bd(a,b[f],c,d,e);return null}c=_.Ab(c);return _.ob(a)?a.U.add(String(b),c,!0,d,e):_.Bb(a,b,c,!0,d,e)};_.N=function(a,b,c){b<a.j?a.G[b+a.b]=c:a.c[b]=c};
_.Cd=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<yd.length;f++)c=yd[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};_.Dd=function(a){var b=[];zd(new Ad,a,b);return b.join("")};_.Ed=function(a,b,c){null!=b&&(a.e=b,null!=c&&(a.j=c))};
_.O=function(a,b){var c,d=a.u;if(d)for(c=[];d;d=d.u)c.push(d);var d=a.L,e=b,f=e.type||e;if(_.t(e))e=new _.H(e,d);else if(e instanceof _.H)e.target=e.target||d;else{var g=e,e=new _.H(f,d);_.Cd(e,g)}var g=!0,l;if(c)for(var q=c.length-1;0<=q;q--)l=e.b=c[q],g=l.da(f,!0,e)&&g;l=e.b=d;g=l.da(f,!0,e)&&g;g=l.da(f,!1,e)&&g;if(c)for(q=0;q<c.length;q++)l=e.b=c[q],g=l.da(f,!1,e)&&g};
_.Fd=function(a,b,c,d,e,f){if(_.ma(c))for(var g=0;g<c.length;g++)_.Fd(a,b,c[g],d,e,f);else{b=Bd(b,c,d||a.handleEvent,e,f||a.I||a);if(!b)return a;a.g[b.key]=b}return a};_.Hd=function(a,b,c){var d=c?c.G:c;a.a[b]=c;_.N(a,b,d)};_.Q=function(a,b,c){if(!a.a[c]){var d=_.y(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};Id=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};Jd=function(a,b){return a?b?(0,window.decodeURI)(a):(0,window.decodeURIComponent)(a):""};
Kd=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?(0,window.decodeURIComponent)(g.replace(/\+/g," ")):"")}};_.Ld=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.Md=function(a){return _.u.concat.apply(_.u,arguments)};_.Nd=function(a,b,c){this.a=a||null;this.b=!!c};
Od=function(a){a.H||(a.H=new _.B,a.O=0,a.a&&Kd(a.a,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};_.h=_.Nd.prototype;_.h.H=null;_.h.O=null;_.h.V=function(){Od(this);return this.O};_.h.add=function(a,b){Od(this);this.a=null;a=Pd(this,a);var c=this.H.get(a);c||this.H.set(a,c=[]);c.push(b);this.O++;return this};_.h.remove=function(a){Od(this);a=Pd(this,a);return _.Oa(this.H,a)?(this.a=null,this.O-=this.H.get(a).length,this.H.remove(a)):!1};
_.h.clear=function(){this.H=this.a=null;this.O=0};_.h.P=function(){Od(this);return 0==this.O};var Qd=function(a,b){Od(a);b=Pd(a,b);return _.Oa(a.H,b)};_.Nd.prototype.M=function(){Od(this);for(var a=this.H.B(),b=this.H.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.Nd.prototype.B=function(a){Od(this);var b=[];if(_.t(a))Qd(this,a)&&(b=_.Md(b,this.H.get(Pd(this,a))));else{a=this.H.B();for(var c=0;c<a.length;c++)b=_.Md(b,a[c])}return b};
_.Nd.prototype.set=function(a,b){Od(this);this.a=null;a=Pd(this,a);Qd(this,a)&&(this.O-=this.H.get(a).length);this.H.set(a,[b]);this.O++;return this};_.Nd.prototype.get=function(a,b){var c=a?this.B(a):[];return 0<c.length?String(c[0]):b};_.Rd=function(a,b,c){a.remove(b);0<c.length&&(a.a=null,a.H.set(Pd(a,b),_.Ld(c)),a.O+=c.length)};
_.Nd.prototype.toString=function(){if(this.a)return this.a;if(!this.H)return"";for(var a=[],b=this.H.M(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.B(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(g)}return this.a=a.join("&")};_.Nd.prototype.clone=function(){var a=new _.Nd;a.a=this.a;this.H&&(a.H=this.H.clone(),a.O=this.O);return a};Pd=function(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c};
Sd=function(a,b){b&&!a.b&&(Od(a),a.a=null,a.H.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.Rd(this,e,a))},a));a.b=b};Td=/#/g;Ud=/[\#\?@]/g;Vd=/[\#\?]/g;Wd=/[\#\?:]/g;Xd=/[#\/\?@]/g;Yd=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,Id),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};_.Zd=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36)};
_.$d=function(a,b){var c;"undefined"!=typeof _.$d&&a instanceof _.$d?(this.ma=_.n(b)?b:a.ma,_.ae(this,a.fa),this.sa=a.sa,this.R=a.R,_.be(this,a.ea),this.N=a.N,ce(this,a.a.clone()),this.la=a.la):a&&(c=_.jb(String(a)))?(this.ma=!!b,_.ae(this,c[1]||"",!0),this.sa=Jd(c[2]||""),this.R=Jd(c[3]||"",!0),_.be(this,c[4]),this.N=Jd(c[5]||"",!0),ce(this,c[6]||"",!0),this.la=Jd(c[7]||"")):(this.ma=!!b,this.a=new _.Nd(null,0,this.ma))};_.h=_.$d.prototype;_.h.fa="";_.h.sa="";_.h.R="";_.h.ea=null;_.h.N="";
_.h.la="";_.h.ma=!1;_.h.toString=function(){var a=[],b=this.fa;b&&a.push(Yd(b,Xd,!0),":");if(b=this.R){a.push("//");var c=this.sa;c&&a.push(Yd(c,Xd,!0),"@");a.push((0,window.encodeURIComponent)(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.ea;null!=b&&a.push(":",String(b))}if(b=this.N)this.R&&"/"!=b.charAt(0)&&a.push("/"),a.push(Yd(b,"/"==b.charAt(0)?Vd:Wd,!0));(b=this.a.toString())&&a.push("?",b);(b=this.la)&&a.push("#",Yd(b,Td));return a.join("")};
_.de=function(a,b){var c=a.clone(),d=!!b.fa;d?_.ae(c,b.fa):d=!!b.sa;d?c.sa=b.sa:d=!!b.R;d?c.R=b.R:d=null!=b.ea;var e=b.N;if(d)_.be(c,b.ea);else if(d=!!b.N){if("/"!=e.charAt(0))if(a.R&&!a.N)e="/"+e;else{var f=c.N.lastIndexOf("/");-1!=f&&(e=c.N.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(_.sa(f,"./")||_.sa(f,"/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),g=[],l=0;l<f.length;){var q=f[l++];"."==q?e&&l==f.length&&g.push(""):".."==q?((1<g.length||1==g.length&&""!=g[0])&&g.pop(),e&&l==
f.length&&g.push("")):(g.push(q),e=!0)}e=g.join("/")}else e=f}d?c.N=e:d=""!==b.a.toString();d?ce(c,Jd(b.a.toString())):d=!!b.la;d&&(c.la=b.la);return c};_.$d.prototype.clone=function(){return new _.$d(this)};_.ae=function(a,b,c){a.fa=c?Jd(b,!0):b;a.fa&&(a.fa=a.fa.replace(/:$/,""))};_.be=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("j`"+b);a.ea=b}else a.ea=null};ce=function(a,b,c){b instanceof _.Nd?(a.a=b,Sd(a.a,a.ma)):(c||(b=Yd(b,Ud)),a.a=new _.Nd(b,0,a.ma))};
_.R=function(a,b,c){a.a.set(b,c)};_.ee=function(a,b,c){_.ma(c)||(c=[String(c)]);_.Rd(a.a,b,c)};_.fe=function(a,b){return a.a.get(b)};_.ge=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.he=function(a,b){return 0<=(0,_.va)(a,b)};
_.ie=function(a,b,c){if(_.ja(a))c&&(a=(0,_.r)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.r)(a.handleEvent,a);else throw Error("n");return 2147483647<b?-1:_.k.setTimeout(a,b||0)};_.je=function(a){_.k.clearTimeout(a)};_.ke=function(a){var b={},c;for(c in a)b[c]=a[c];return b};_.le=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.la(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}}; _.me=function(a,b){var c;t:{c=a.length;for(var d=_.t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break t}c=-1}return 0>c?null:_.t(a)?a.charAt(c):a[c]};
var qe,oe,pe,re;_.ne=function(){};qe=function(a){var b=a.ia,c=function(a){c.t.constructor.call(this,a);var b=this.T.length;this.a=[];for(var d=0;d<b;++d)this.T[d].Hd||(this.a[d]=new this.T[d](a))};_.p(c,b);for(var d=[];a;){if(b=a.ia){b.T&&_.le(d,b.T);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ja(e[f])&&e[f]!==b){var g=!!e[f].Qc,l=oe(f,e,d,g);(g=pe(f,e,l,g))&&(c.prototype[f]=g)}}a=a.t&&a.t.constructor}c.prototype.T=d;return c};
oe=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e};
pe=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.T[c[0]].prototype[a].apply(this,arguments)}:b[a].Sc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var q=this.a[c[e]];if(q=q?q[a].apply(q,d):this.T[c[e]].prototype[a].apply(this,d)){d=q;break t}}d=!1}return d}:b[a].Rc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var q=this.a[c[e]],q=q?q[a].apply(q,
d):this.T[c[e]].prototype[a].apply(this,d);if(null!=q){d=q;break t}}d=void 0}return d}:b[a].lc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var q=this.a[c[e]];q?q[a].apply(q,d):this.T[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],q=0;q<c.length;++q){var C=this.a[c[q]];e.push(C?C[a].apply(C,d):this.T[c[q]].prototype[a].apply(this,d))}return e}:d||b[a].Sc||b[a].Rc||b[a].lc?e=null:e=re;return e};re=function(){return[]}; _.ne.prototype.ub=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var se;_.te=function(a){if(!a.rb){var b;for(b=a.constructor;b&&!b.ia;)b=b.t&&b.t.constructor;b.ia.Wb||(b.ia.Wb=qe(b));b=new b.ia.Wb(a);a.rb=b;a.ub||(a.ub=se)}};se=function(a){return this.rb.ub(a)};var ue=function(){};ue.prototype.a=null;var we=function(a){var b;(b=a.a)||(b={},ve(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var xe,ye=function(){};_.p(ye,ue);var ze=function(a){return(a=ve(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},ve=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("t");}return a.b};xe=new ye;
var Be,Ee,Je,Le,Ke,Ge;_.Ae=function(a){_.J.call(this);this.A=new _.B;this.k=a||null;this.b=!1;this.h=this.a=null;this.q="";this.e=0;this.c=this.p=this.f=this.l=!1;this.v=0;this.g=null;this.I="";this.w=this.aa=!1};_.p(_.Ae,_.J);Be=/^https?$/i;_.Ce=["POST","PUT"];_.De=[];_.Ae.prototype.S=function(){this.D();_.Ba(_.De,this)};
_.Ae.prototype.send=function(a,b,c,d){if(this.a)throw Error("u`"+this.q+"`"+a);b=b?b.toUpperCase():"GET";this.q=a;this.e=0;this.l=!1;this.b=!0;this.a=this.k?ze(this.k):ze(xe);this.h=this.k?we(this.k):we(xe);this.a.onreadystatechange=(0,_.r)(this.J,this);try{this.p=!0,this.a.open(b,String(a),!0),this.p=!1}catch(e){Ee(this);return}a=c||"";var f=this.A.clone();d&&_.Qa(d,function(a,b){f.set(b,a)});d=_.me(f.M(),Fe);c=_.k.FormData&&a instanceof _.k.FormData;!_.he(_.Ce,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.I&&(this.a.responseType=this.I);"withCredentials"in this.a&&(this.a.withCredentials=this.aa);try{Ge(this),0<this.v&&((this.w=He(this.a))?(this.a.timeout=this.v,this.a.ontimeout=(0,_.r)(this.K,this)):this.g=_.ie(this.K,this.v,this)),this.f=!0,this.a.send(a),this.f=!1}catch(g){Ee(this)}};var He=function(a){return _.D&&_.Za(9)&&_.ka(a.timeout)&&_.n(a.ontimeout)},Fe=function(a){return"content-type"==a.toLowerCase()};
_.Ae.prototype.K=function(){"undefined"!=typeof _.aa&&this.a&&(this.e=8,_.O(this,"timeout"),_.Ie(this,8))};Ee=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.e=5;Je(a);Ke(a)};Je=function(a){a.l||(a.l=!0,_.O(a,"complete"),_.O(a,"error"))};_.Ie=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.e=b||7,_.O(a,"complete"),_.O(a,"abort"),Ke(a))};_.Ae.prototype.n=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Ke(this,!0));_.Ae.t.n.call(this)};
_.Ae.prototype.J=function(){this.C||(this.p||this.f||this.c?Le(this):this.W())};_.Ae.prototype.W=function(){Le(this)};Le=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.h[1]||4!=(a.a?a.a.readyState:0)||2!=_.Me(a)))if(a.f&&4==(a.a?a.a.readyState:0))_.ie(a.J,0,a);else if(_.O(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.Ne(a)?(_.O(a,"complete"),_.O(a,"success")):(a.e=6,Je(a))}finally{Ke(a)}}};
Ke=function(a,b){if(a.a){Ge(a);var c=a.a,d=a.h[0]?_.na:null;a.a=null;a.h=null;b||_.O(a,"ready");try{c.onreadystatechange=d}catch(e){}}};Ge=function(a){a.a&&a.w&&(a.a.ontimeout=null);_.ka(a.g)&&(_.je(a.g),a.g=null)};
_.Ne=function(a){var b=_.Me(a),c;t:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break t;default:c=!1}if(!c){if(b=0===b)a=_.jb(String(a.q))[1]||null,!a&&window.self.location&&(a=window.self.location.protocol,a=a.substr(0,a.length-1)),b=!Be.test(a?a.toLowerCase():"");c=b}return c};_.Me=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};_.Oe=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
_.Pe=function(a){_.x(this,a,"h_icr",null)};_.p(_.Pe,_.w);_.z("h_icr",_.Pe);_.Qe=function(a){_.x(this,a,"h_cs",null)};_.p(_.Qe,_.w);_.z("h_cs",_.Qe);_.Qe.prototype.getState=function(){return _.y(this,1)};_.Re=new _.M("HwdKC");
}catch(e){_._DumpException(e)}
try{
_.k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_description:{message:"Always stay connected with the new desktop app for Hangouts on ChromeOS and Windows."},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},
chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},chrome_app_signin_button:{message:"Sign in"},chrome_app_outdated_title:{message:"Update your Hangouts Chrome app"},chrome_app_outdated_detail:{message:"This app is out of date. There's a newer version available."},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_title_2:{message:"Do you want to quit Hangouts?"},chrome_app_exit_detail:{message:"You will not receive new messages or calls on this device"},
chrome_app_exit_detail_2:{message:"You can also choose to minimize it and continue to receive messages and calls."},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"},chrome_app_exit_minimize:{message:"Minimize"},chrome_app_osx_warning_message:{message:"Hangouts Chrome app is not fully supported on Mac OSX."},chrome_app_osx_warning_ack:{message:"OK, GOT IT"}};

}catch(e){_._DumpException(e)}
try{
_.Oh=function(a){for(var b=a.a.M(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.F(),type:f.type(),multiple:f.Db,disabled:!f.ba,inverse:f.zb,changed:f.qb}}return c};_.Ph=function(a,b){return _.t(b)?a.getElementById(b):b};_.S=function(a){return _.Ph(window.document,a)};_.Qh=new _.M("a");_.Rh=new _.M("b");_.Sh=new _.M("c");_.Th=new _.M("d");_.Uh=new _.M("e");_.Vh=new _.M("f");_.Wh=new _.M("g");_.Xh=new _.M("h");_.td=new _.M("i");_.Yh=new _.M("j");
_.T=function(a){var b;b=b||[];b.length||(b[0]="");var c=window.chrome.i18n.getMessage(a,b);if(c)return c;(c=(c=_.k.ace_i18n[a.toLowerCase()])?c.message:_.k.ace_i18n["MSG_"+a])&&(c=c.replace("$1",b[0]).replace("$2",b[1]).replace("$3",b[2]));return c};
}catch(e){_._DumpException(e)}
try{
var Zh,$h,ai,bi,ci,ei,gi,hi,ii,ji,ki,li,mi,ni,oi,pi,qi,si,ti,ui,yi,Ai,Ei;Zh=function(a){return a.b[0]};$h=function(a){return(a=a.a.get("TopMost"))&&a.ba?a.F():!0};ai=function(){return!0};bi={};ci=0;_.di=function(a){a&&a!=window.chrome.windows.WINDOW_ID_NONE&&window.chrome.windows.update(a,{focused:!0})};ei=function(a){if(bi[a])return bi[a];a=String(a);if(!bi[a]){var b=/function ([^\(]+)/.exec(a);bi[a]=b?b[1]:"[Anonymous]"}return bi[a]};_.fi=function(a){return a[_.ba]||(a[_.ba]=++ci)};
gi=function(a){window.chrome.windows.getAll({populate:!0},function(b){for(var c=0;c<b.length;++c){var d=b[c].tabs;if(null!=d)for(var e=0;e<d.length;++e)if(d[e].selected&&d[e].url==a){_.di(b[c].id);return}}})};hi=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};ii=function(){return null!=window.navigator.platform.match(/Mac.*/)};ji=function(){return!_.Fc()&&null!=window.navigator.platform.match(/Linux.*/)};ki=function(a){this.a=a||_.k.document||window.document};
ki.prototype.cc=function(){var a=this.a;return a.parentWindow||a.defaultView};ki.prototype.contains=_.ge;
li=function(a,b){var c=[];if(_.he(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(ei(a)+"(");for(var d=a.arguments,e=0;d&&e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=ei(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}b.push(a);c.push(")\n");try{c.push(li(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")};mi=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+_.fi(a):b.substr(0,1)+a};ni=function(a){if(a instanceof _.Ja)return a;if("function"==typeof a.ha)return a.ha(!1);if(_.la(a)){var b=0,c=new _.Ja;c.next=function(){for(;;){if(b>=a.length)throw _.Ia;if(b in a)return a[b++];b++}};return c}throw Error("g");};oi=function(a,b){return a>b?1:a<b?-1:0};
pi=function(a,b){null!=a&&(window.open(a,"winid_"+(new Date).getTime(),b),_.ie((0,_.r)(gi,null,a),1E3))};qi=function(a){null!=a&&(a=window.chrome.runtime.getURL("images_4/"+a));return a};_.ri=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};_.ri.prototype.clone=function(){return new _.ri(this.left,this.top,this.width,this.height)};
_.ri.prototype.contains=function(a){return"undefined"!=typeof _.ri&&a instanceof _.ri?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};_.ri.prototype.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.ri.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.U=function(a){return _.U.b(a)};_.U.b=function(a){return a+"_"};_.U.g=function(){throw Error("o");};_.U.e=function(a){if(a&&a.constructor&&a.constructor.toString()===Object.toString()){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[_.U.b(c)]=a[c]);return b}throw Error("p");};_.U.c=!0;_.U.j=function(a){return a};_.U.f=function(){return!0};
si=[/^https?:\/\/.*.google.com(:[0-9]+)?\/talkgadget\/success/,/^https:\/\/accounts.google.com\/ServiceLogin/];ti=[1E4,12E4,144E5];ui=[200,2E3,3E5];_.vi=function(a,b){_.J.call(this);this.c=a||1;this.b=b||_.k;this.f=(0,_.r)(this.h,this);this.g=(0,_.m)()};_.p(_.vi,_.J);_.vi.prototype.e=!1;_.vi.prototype.a=null;_.vi.prototype.setInterval=function(a){this.c=a;this.a&&this.e?(this.stop(),_.wi(this)):this.a&&this.stop()};
_.vi.prototype.h=function(){if(this.e){var a=(0,_.m)()-this.g;0<a&&a<.8*this.c?this.a=this.b.setTimeout(this.f,this.c-a):(this.a&&(this.b.clearTimeout(this.a),this.a=null),_.O(this,"tick"),this.e&&(this.a=this.b.setTimeout(this.f,this.c),this.g=(0,_.m)()))}};_.wi=function(a){a.e=!0;a.a||(a.a=a.b.setTimeout(a.f,a.c),a.g=(0,_.m)())};_.vi.prototype.stop=function(){this.e=!1;this.a&&(this.b.clearTimeout(this.a),this.a=null)};_.vi.prototype.n=function(){_.vi.t.n.call(this);this.stop();delete this.b};
var xi=function(a,b){this.width=a;this.height=b};xi.prototype.clone=function(){return new xi(this.width,this.height)};xi.prototype.P=function(){return!(this.width*this.height)};xi.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};xi.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};yi=function(a){var b;b||(b=li(a||arguments.callee.caller,[]));return b};
_.zi=function(a){this.a=new _.B;if(a){a=_.Pa(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])}};_.h=_.zi.prototype;_.h.V=function(){return this.a.V()};_.h.add=function(a){this.a.set(mi(a),a)};_.h.removeAll=function(a){a=_.Pa(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};_.h.remove=function(a){return this.a.remove(mi(a))};_.h.clear=function(){this.a.clear()};_.h.P=function(){return this.a.P()};_.h.contains=function(a){return _.Oa(this.a,mi(a))};_.h.B=function(){return this.a.B()};
_.h.clone=function(){return new _.zi(this)};_.h.ha=function(){return this.a.ha(!1)};Ai=function(a,b){if(_.la(a))try{(0,_.v)(a,b,void 0)}catch(c){if(c!==_.Ia)throw c;}else{a=ni(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(d){if(d!==_.Ia)throw d;}}};_.Bi=function(a,b,c){c=c||[];for(var d=[],e=0;e<c.length;e++)d[e]=c[e].G;a.a[b]=c;_.N(a,b,d)};_.Ci=function(a,b,c){if(!a.a[c]){for(var d=_.y(a,c),e=[],f=0;f<d.length;f++)e[f]=new b(d[f]);a.a[c]=e}return a.a[c]};_.Di=function(a,b){a.sort(b||oi)}; Ei=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};
var Fi=function(a){_.x(this,a,"dpgi",null)};_.p(Fi,_.w);_.z("dpgi",Fi);var Gi=function(a){_.x(this,a,"dri",null)};_.p(Gi,_.w);_.z("dri",Gi);_.Ii=function(a){_.x(this,a,"di",Hi)};_.p(_.Ii,_.w);var Hi=[6,7,10,11,12];_.z("di",_.Ii);_.Ji=function(a){_.x(this,a,"e",null)};_.p(_.Ji,_.w);_.z("e",_.Ji);_.Ki=function(a){_.x(this,a,"f.ri",null)};_.p(_.Ki,_.w);_.z("f.ri",_.Ki);var Li=function(){_.E.call(this)},Mi;_.p(Li,_.E);
_.Oi=function(a,b){var c=Mi;if(!(c.C||"undefined"!=typeof _.jd&&b instanceof _.jd))if(c.b){var c=c.b,d=Ni();d["call-stack"]=yi();a&&(d.message=a);var e;b instanceof Error?e=b:e=b||"";var f,g="";e&&(g=(e.lineNumber||"unknown")+":"+Ei(e.fileName||"unknown")+":"+Ei(e.message||"unknown"));var l="";for(f in d){var q;q="call-stack"==f?d[f].replace(/\(.*\)/g,""):d[f];l=l+f+":"+q+":"}f=g+"::"+l;g=c.c[f];g||(g={time:0,count:0},c.c[f]=g);if(1E4>(0,_.m)()-g.time)g.count++,1==g.count&&(d=Ni(),d.message="Throttling: "+ f,c.a.a(e,d));else{g.count&&(d["dropped-instances"]=g.count);g.time=(0,_.m)();for(f=g.count=0;f<c.b.length;f++)c.b[f](e,d);c.a.a(e,d)}}else c.a&&10>c.a.length&&c.a.push([a,b])};Mi=new Li;
_.Pi=function(a){var b=window;if(!b.location){var c;try{c=_.Dd(b)}catch(d){c=_.Fa(b).toString()}_.Oi(null,Error("x`"+c))}c=b.location&&b.location.ancestorOrigins;if(_.n(c))return c&&c.length?c[a?0:c.length-1]==b.location.origin:!0;try{return _.n((a?b.parent:b.top).location.href)}catch(e){return!1}};
var Qi={},Ni=function(){var a={};a.location=window.document.location.toString();if(_.Pi(!1))try{a["top.location"]=window.top.location.toString()}catch(b){a["top.location"]="[external]"}else a["top.location"]="[external]";for(var c in Qi)try{a[c]=Qi[c].call()}catch(d){a[c]="[error] "+d.message}return a};
_.Ri=function(a){this.c=a;this.a=new _.Pc;this.b=a.get(_.Xh);this.a.setItem(new _.Lc("StartOnBrowserLaunch",!0,!1,!1));_.Qc&&this.a.setItem(new _.Lc("TopMost",!0));a=new _.Lc("StopOnBrowserClose",!1,!1,!1);a.setEnabled(!1);this.a.setItem(a);a=new _.Lc("TrayIcon",!0,!1,!1);a.setEnabled(null!=window.navigator.platform.match(/Win.*/)||ji()||ii());this.a.setItem(a);(a=this.b.get("settings"))&&_.Oc(this.a,a);this.b.set("settings",_.Oh(this.a))};_.ga("ace.core.SettingsManager",_.Ri);
var Si=window.chrome.runtime&&window.chrome.runtime.getURL&&window.chrome.runtime.getURL("settingsdialog.html")||"";_.Ri.prototype.e=function(){this.b.set("settings",_.Oh(this.a));var a=_.V.e("setting");if(a&&0!=a.length)Ti(a[0],"focus");else{var a=Math.floor((window.screen.height-200)/2),b=Math.floor((window.screen.width-520)/2),c=["width=520"];c.push("height=200");c.push("top="+a);c.push("left="+b);c.push("location=no");pi(Si,c.join(","))}};_.Ri.prototype.launchSettingsDialog=_.Ri.prototype.e;
_.Ri.prototype.f=function(){var a=new _.Pc(_.Oh(this.a)),b=this.b.get("settings");_.Oc(this.a,b);var c=new _.Pc(b),b=c.getItem("StopOnBrowserClose"),a=a.getItem("TrayIcon"),c=c.getItem("TrayIcon");a.ba&&(c.F()||b.F()?(b=this.c.get(_.Rh),Ui(b),Vi(b)):c.F()||b.F()||Wi(this.c.get(_.Rh)))};_.Ri.prototype.updateSettingsFromStorage=_.Ri.prototype.f;_.Ri.prototype.j=function(){var a=_.V.e("setting");if(a)for(var b=0;b<a.length;++b)Ti(a[b],"close")};_.Ri.prototype.closeUI=_.Ri.prototype.j; var Ti=function(a,b){var c=new _.Gc;_.Jc(c,b);_.Kc(c,[]);_.V.b(a).sendMessage(c)};
var W=new _.Vc("act"),Xi=new _.Vc("impr"),Yi=new _.Vc("tran"),Zi=new _.Vc("perf");new _.K(W,1);new _.K(W,2);new _.K(W,3);new _.K(W,4);new _.K(W,5);new _.K(W,6);new _.K(W,7);new _.K(W,8);new _.K(W,9);new _.K(W,10);new _.K(W,11);new _.K(W,12);new _.K(W,25);new _.K(W,13);new _.K(W,14);new _.K(W,15);new _.K(W,22);new _.K(W,16);new _.K(W,17);new _.K(W,18);new _.K(W,19);new _.K(W,20);new _.K(W,21);new _.K(W,23);new _.K(W,24);_.$i=new _.K(Xi,1E3);new _.K(Yi,1001);new _.K(Zi,1002);
_.aj=new _.M("k");_.bj=function(a){this.k=a;this.p=a.get(_.Wh);this.b=a.get(_.Xh);this.a=1;this.e=this.h=null;this.g=this.c=!1;this.l=(0,_.r)(this.q,this);Ui(this);Vi(this);null!=this.b.a.get("UnreadIndicator")&&this.b.remove("UnreadIndicator");null!=this.b.a.get("app_status")&&this.b.remove("app_status");null!=this.b.a.get("user_id")&&this.b.remove("user_id");null!=this.b.a.get("client_state")&&this.b.remove("client_state")};_.p(_.bj,_.E);_.ga("ace.core.DesktopManager",_.bj);_.bj.prototype.n=function(){Wi(this);_.bj.t.n.call(this)};
_.bj.prototype.f=function(a,b){this.a!=b&&(this.a=b,Vi(this),cj(this),1==this.a&&(this.e=this.h=null,this.g=this.c=!1,Wi(this),this.p.j(),this.k.get(_.Uh).b()),_.V.g())};_.bj.prototype.changeDesktop=_.bj.prototype.f;_.bj.prototype.u=function(a,b){this.c!=b&&(this.c=b,Vi(this),cj(this))};_.bj.prototype.setMainUiShowing=_.bj.prototype.u;
var Ui=function(a){var b=a.p.a,c;if(c=null!=window.navigator.platform.match(/Win.*/)||ji()||ii())c=b.a.get("StopOnBrowserClose"),(c=c&&c.ba?c.F():!1)||(c=(b=b.a.get("TrayIcon"))&&b.ba?b.F():!1);c&&window.chrome.systemIndicator&&(window.chrome.systemIndicator.enable(),window.chrome.systemIndicator.onClicked.addListener(a.l))},Wi=function(a){window.chrome.systemIndicator&&(window.chrome.systemIndicator.disable(),window.chrome.systemIndicator.onClicked.removeListener(a.l))},cj=function(a){var b;switch(a.a){case 2:b=
_.T("QUASAR_TIP_CONNECTING");break;case 3:b=_.T("QUASAR_TIP_NOT_LOGIN");break;case 4:case 9:case 8:b=a.c?a.g?_.T("CHROME_EXT_TIP_CONNECTED_MISSED_MESSAGES"):_.T("QUASAR_TIP_CONNECTED"):_.T("QUASAR_TIP_NOT_LOGIN");break;case 6:b=_.T("QUASAR_TIP_NOT_LOAD");break;default:b=_.T("QUASAR_TIP_DISCONNECTED")}a=a.e?"\n"+a.e:"";(b=_.T("CHROME_EXT_SHORT_NAME")+a+"\n"+b)&&window.chrome.browserAction.setTitle({title:b})};
_.bj.prototype.w=function(a,b,c){1!=this.a&&(a=b||_.T("QUASAR_MENUTEXT_UNKNOWN_USER"),a!=this.h&&(this.h=a),this.e=c)};_.bj.prototype.updateUserName=_.bj.prototype.w;_.bj.prototype.v=function(a,b){this.g!=b&&(this.g=b,Vi(this),cj(this))};_.bj.prototype.setUnreadIndicator=_.bj.prototype.v;
var Vi=function(a){window.chrome.browserAction.setIcon(dj(a,!0));window.chrome.systemIndicator&&window.chrome.systemIndicator.setIcon(dj(a))},ej=function(a){switch(a.a){case 2:return"offline_working";case 4:case 9:case 8:return a.c?a.g?"available_missed":"available":"offline";case 6:return"offline_unknown";default:return"offline"}},dj=function(a,b){var c=!b&&ii()?"_mac_":"_",d=ej(a),e=window.chrome.runtime.getURL("images_4/presence/"+d+c+"19.png"),c=window.chrome.runtime.getURL("images_4/presence/"+ d+c+"38.png");return{path:{19:e,38:c}}};_.bj.prototype.q=function(){var a=_.V.a();this.k.get(_.aj).a("qstcl");a.nb();a.b("onTrayClick",[1])};
var gj=function(a,b,c){_.J.call(this);this.a=b.createElement("IFRAME");b.body.appendChild(this.a);this.a.src=a;c&&(this.a.id=c,this.a.name=c);a=new _.I(this);_.G(this,a);a=_.Fd(a,this.a,"load",this.c,void 0);_.Fd(a,this.a,"error",fj,void 0).listen(b.defaultView,"focus",this.b).listen(b.body,"focus",this.b)};_.p(gj,_.J);gj.prototype.b=function(){_.Sb(this.a.focus,this.a)};gj.prototype.c=function(){this.b()};gj.prototype.n=function(){this.a.parentElement.removeChild(this.a);this.a=null;gj.t.n.call(this)};
var hj={},ij=function(){delete hj.X},fj=function(){hj.X(1)};var oj=function(a,b){_.I.call(this);this.b=a;_.Ec("viewer",""+(new Date).getTime());this.e=this.f=null;this.l=_.V;this.u=(0,_.m)();this.k=a.get(_.Rh);var c=a.get(_.Vh),d=_.T("CHROME_EXT_SHORT_NAME"),e=qi("viewer-14.png"),f=qi("viewer-28.png"),d=jj(c,"viewer","viewer","viewer.html?viewer",d,e,f),e=b?_.Q(b,_.kj,2).Ja():null,e=lj(c,new xi(260,460),!0,e);mj(c,d.id,e);this.a=d;this.a.onClosed.addListener((0,_.r)(this.D,this));nj(this.a,(0,_.r)(this.p,this))};_.p(oj,_.I);
oj.prototype.n=function(){this.b.b(_.td)==this&&this.b.u();this.removeAll();oj.t.n.call(this)};var pj=function(a){_.F(a.f);a.f=null;_.F(a.e);a.e=null;_.Ph(a.c.a,"retryInfo").style.display="none"};oj.prototype.close=function(){_.F(this.a);this.b.b(_.td)==this&&this.b.u()};
oj.prototype.p=function(){this.c=new ki(qj(this.a).document);this.a.setTitle(_.T("CHROME_EXT_SHORT_NAME"));_.Ph(this.c.a,"retryMessage").textContent=_.T("CHROME_EXT_CANNOT_CONNECT");var a=_.Ph(this.c.a,"retryLink");a.textContent=_.T("QUASAR_TRY_NOW");this.listen(a,"click",this.q);this.listen(this.l,"onStatusChange",this.h);this.h()};oj.prototype.q=function(a){a.Xa();this.b.get(_.Qh).f()};
oj.prototype.h=function(){switch(this.k.a){case 3:if(!this.f){pj(this);var a;a=this.b.get(_.Wh).a;a=new _.$d(a.b[0]);var b=new _.$d("/talkgadget/qsignin");_.R(b,"passive","1");_.R(b,"hl",window.chrome.i18n.getMessage("@@ui_locale"));a=_.de(a,b).toString();this.f=new gj(a,this.c.a)}break;case 2:pj(this);break;case 6:pj(this);_.Ph(this.c.a,"retryInfo").style.display="block";break;default:rj(this)}}; var rj=function(a){a.e||(pj(a),sj(a.b.get(_.Qh)).then(function(a){this.e=new gj(a,this.c.a,"popoutRoster")},void 0,a))};
var tj=function(a,b){this.b=_.Ld(a);this.a=0;this.c=b||!1};tj.prototype.F=function(a){var b=this.b[this.a],b=(.5+1*Math.random())*b;a&&uj(this);return b};var uj=function(a){a.c&&a.a==a.b.length-1||a.a++};var vj=function(a,b,c){_.E.call(this);this.b=a;this.e=b||0;this.c=c;this.X=(0,_.r)(this.f,this)};_.p(vj,_.E);vj.prototype.a=0;vj.prototype.n=function(){vj.t.n.call(this);this.stop();delete this.b;delete this.c};var wj=function(a,b){a.stop();a.a=_.ie(a.X,_.n(b)?b:a.e)};vj.prototype.stop=function(){0!=this.a&&_.je(this.a);this.a=0};vj.prototype.f=function(){this.a=0;this.b&&this.b.call(this.c)};
var xj=function(a,b,c){_.E.call(this);this.c=a;this.b=b;this.a=c;this.X=(0,_.r)(this.Wc,this)};_.p(xj,_.E);_.h=xj.prototype;_.h.Pa=!1;_.h.na=null;_.h.stop=function(){this.na&&(_.je(this.na),this.na=null,this.Pa=!1)};_.h.n=function(){xj.t.n.call(this);this.stop()};_.h.Wc=function(){this.na=null;this.Pa&&(this.Pa=!1,yj(this))};var yj=function(a){a.na=_.ie(a.X,a.b);a.c.call(a.a)};
_.X=function(a){_.I.call(this);this.a=a;this.c=a.get(_.Rh);this.S=a.b(_.Vh);this.L=_.ec();this.l=null;this.J=new xj(this.f,6E4,this);_.G(this,this.J);a=(0,_.r)(this.hd,this);hj.X=a;_.bb(this,ij);this.h=!1;this.q=new tj(ti,!0);this.K=new vj(this.vd,this.q.F(),this);_.G(this,this.K);this.k=new vj(this.sc,2E4,this);_.G(this,this.k);this.listen(window,"online",this.od);this.w=this.A=0;this.b=new tj(ui);this.e=new vj(this.Aa,this.b.F(),this);_.G(this,this.e);window.chrome.cookies.onChanged.addListener((0,_.r)(this.Ba,
this));this.v=(0,_.r)(this.aa,this);this.u=(0,_.r)(this.W,this);window.chrome.tabs.onUpdated.addListener(this.v);window.chrome.tabs.onCreated.addListener(this.u)};_.p(_.X,_.I);_.ga("ace.core.DataChannelManager",_.X);_.X.prototype.n=function(){window.chrome.tabs.onCreated.removeListener(this.u);window.chrome.tabs.onUpdated.removeListener(this.v);delete this.u;delete this.v;_.F(this.l);_.X.t.n.call(this)};
_.X.prototype.p=function(a,b){_.zj(this);t:{var c=this.a,d=c.b(_.td);if(d){if(Aj(d.a)?!Bj(d.a):1E3>(0,_.m)()-d.u){d.a.focus();break t}d.close()}d=new oj(c,b);c.a(_.td,d,!0)}};_.X.prototype.showViewer=_.X.prototype.p;_.X.prototype.Ra=function(a,b){this.L.a(b||"")};_.X.prototype.setRosterUrl=_.X.prototype.Ra;var sj=function(a){return a.L.b};_.X.prototype.za=function(){this.c.f(0,1);var a=this.a.b(_.td);a&&a.close();Cj(this);this.h=!1};_.X.prototype.terminateApplication=_.X.prototype.za;
_.zj=function(a){a.h||(a.listen(_.V,"onStatusChange",a.Lc),a.f(),a.a.get(_.Wh),a.h=!0)};_.X.prototype.f=function(){this.C||(this.c.f(0,2),Cj(this),this.l=new gj(window.chrome.runtime.getURL("datachannel.html"),window.document,"centralRoster"))};var Cj=function(a){a.S.f();a.a.get(_.Uh).b();_.F(a.l);a.l=null;a.L=_.ec()},Ej=function(a,b){var c=Zh(a.a.get(_.Wh).a);window.chrome.cookies.getAll({url:c},(0,_.r)(function(a){a=a&&Dj("SID",a)&&Dj("SSID",a)&&Dj("SAPISID",a);b(a)},a))};
_.X.prototype.Ca=function(a){var b=this.c.a;if(a){if(3==b){if(a=0==this.e.a)a=this.b,a=a.a<a.b.length;a&&wj(this.e,this.b.F())}}else 3!=b&&this.f()};_.X.prototype.Ba=function(a){"SSID"!=a.cookie.name&&"SAPISID"!=a.cookie.name||".google.com"!=a.cookie.domain||Ej(this,(0,_.r)(this.Ca,this))};var Dj=function(a,b){return(0,_.Aa)(b,function(b){var d=b.expirationDate&&b.expirationDate<(0,_.m)()/1E3;return b.name==a&&".google.com"==b.domain&&!d})};_.h=_.X.prototype;
_.h.Lc=function(){this.K.stop();this.k.stop();switch(this.c.a){case 2:wj(this.k);break;case 6:wj(this.K,this.q.F());break;case 4:case 9:case 8:case 5:this.q.a=0,this.e.stop()}};_.h.od=function(){if(4!=this.c.a){var a=this.J;a.na?a.Pa=!0:yj(a)}};_.h.vd=function(){uj(this.q);this.f()};_.h.hd=function(a){Cj(this);switch(a){case 1:this.sc();break;case 2:a=this.J,a.na?a.Pa=!0:yj(a)}};_.h.sc=function(){this.C||(this.k.stop(),this.c.f(0,6))};
var Fj=function(a){a.w++;var b=a.a.get(_.aj);1==a.w?b.a("qccro"):2==a.w?b.a("qccrt"):b.a("qccrm")};_.X.prototype.Aa=function(){uj(this.b);Fj(this);Ej(this,(0,_.r)(function(a){a&&this.f()},this))};_.X.prototype.aa=function(a,b){b.url&&Gj(this,b.url)};_.X.prototype.W=function(a){a.url&&Gj(this,a.url)}; var Hj=function(a){a.A++;var b=a.a.get(_.aj);1==a.A?b.a("qctro"):2==a.A?b.a("qctrt"):b.a("qctrm")},Gj=function(a,b){(0,_.Aa)(si,function(a){return a.test(b)})&&0!=a.b.a&&(a.b.a=0,Hj(a),0!=a.e.a&&wj(a.e,a.b.F()))};
var Ij=function(a,b){this.a=a;this.h=b;this.k=window.chrome.runtime.getURL("images_4/icon-128x128.png");this.j=this.g=this.l="";this.e=0;this.b=[];this.f=""},Jj=function(a){this.name=a;this.title=""};Ij.prototype.setTitle=function(a){a&&(this.l=a)};
var Kj=function(a){return a.replace(/^(\<br\>)+/,"")},Lj=function(a){var b=a.l;a.g&&(b+=" "+a.g);var c=Kj(a.j||7!=a.h?a.j||"":_.T("CHROME_EXT_ONEONONE_PLUS_HANGOUT_DETAILS")),d=(0,_.ya)(a.b,function(a){var b;if(!(b=a.title))t:{switch(a.name){case "join hangout":b=_.T("QUASAR_ANSWER_BUTTON_TEXT");break t;case "ignore":b=_.T("QUASAR_DECLINE_BUTTON_TEXT");break t}b=""}return{title:b}},a);return{type:"basic",iconUrl:a.k,title:b,message:c,buttons:d,priority:2}};
var Mj=function(){this.b=new _.B;this.a=new _.vi(18E5);_.zb(this.a,"tick",(0,_.r)(this.c,this,this.b,0,200));_.wi(this.a)};_.p(Mj,_.E);Mj.prototype.n=function(){this.a.D()};var Nj=function(a,b){var c=null!=b.c?b.a+b.c:null;return null!=c?_.Oa(a.b,c):!1};Mj.prototype.add=function(a){var b=null!=a.c?a.a+a.c:null;null!=b&&!Nj(this,a)&&this.b.set(b,(0,_.m)()+18E5)};
Mj.prototype.c=function(a,b,c){var d=a.V();if(0!=d){var e=0;null!=b&&0<b&&(e=b<d?b:d);b=d;null!=c&&c<d&&(b=0<c?c:0);e>b&&(e=b);var f=[];c=a.ha(!0);Ai(c,function(b){f.push([b,a.get(b)])});f.sort(function(a,b){return a[1]-b[1]});if(31536E7<f[d-1][1]-f[0][1])a.clear();else{c=0;b=d-b;for(var d=d-e,e=(0,_.m)(),g=0;g<f.length;++g)if(c<b||c<d&&f[g][1]<=e)a.remove(f[g][0]),c+=1;else break}}};
var Oj=function(a){_.x(this,a,"acr:bcr",null)};_.p(Oj,_.w);_.z("acr:bcr",Oj);var Pj=function(a){_.x(this,a,"acr:srs",null)};_.p(Pj,_.w);_.z("acr:srs",Pj);var Qj=function(a){_.x(this,a,"acr:rss",null)};_.p(Qj,_.w);_.z("acr:rss",Qj);var Rj=function(a){_.x(this,a,"acr:rrs",null)};_.p(Rj,_.w);_.z("acr:rrs",Rj);var Sj=function(a){_.x(this,a,"acr:rsr",null)};_.p(Sj,_.w);_.z("acr:rsr",Sj);_.Uj=function(a){_.x(this,a,"acr:wrs",Tj)};_.p(_.Uj,_.w);var Tj=[1];_.z("acr:wrs",_.Uj); var Vj=function(a){_.x(this,a,0,null)};_.p(Vj,_.w);Vj.prototype.Z=function(){return _.y(this,2)};Vj.prototype.Ia=function(){return _.y(this,11)};
var Zj;_.Xj=function(a){_.x(this,a,"acq:rs",Wj)};_.p(_.Xj,_.w);var Wj=[3];_.z("acq:rs",_.Xj);var Yj=function(a){_.x(this,a,0,null)};_.p(Yj,_.w);Yj.prototype.getState=function(){return _.y(this,6)};_.kj=function(a){_.x(this,a,0,null)};_.p(_.kj,_.w);_.kj.prototype.Ja=function(){return _.Q(this,Yj,1)};Zj=function(a,b){_.Hd(a,1,b)};_.ak=function(a){_.x(this,a,0,null)};_.p(_.ak,_.w);_.ak.prototype.Z=function(){return _.y(this,1)};_.ak.prototype.Ja=function(){return _.Q(this,Yj,2)}; var bk=function(a,b){_.Hd(a,2,b)};_.ak.prototype.Ia=function(){return _.y(this,3)};
var ck,gk,fk;ck=function(a){this.c=a;this.a={};this.b=a.get(_.Xh)};_.dk=function(a,b){return(null!=a?a:"null")+"-"+(null!=b?b:"null")};
gk=function(a,b){_.ie(a.reload,6E4,a);var c=[],d={},e=a.c.get(_.Vh),f=_.Ci(b,Vj,1)||[];(0,_.v)(f,function(a){c.push(_.y(a,1));d[_.dk(a.Z(),a.Ia())]=a});var g=c.length;c.push("viewer");ek(e,c,(0,_.r)(function(a){for(var c=[],e=0;e<f.length;e++){var L=a[e];if(L){var fa=f[e],P=new _.ak;_.N(P,3,fa.Ia());_.N(P,1,fa.Z());bk(P,fk(L));c.push(P)}}_.Di(c,function(a,b){var c=b.Ja(),c=_.y(c,2),d=a.Ja();return c-_.y(d,2)});(0,_.v)(c,function(a,b){_.N(d[_.dk(a.Z(),a.Ia())],3,b)});a=a[g];e=new _.Xj;a&&(L=new _.kj,
Zj(L,fk(a)),_.Hd(e,2,L));_.Bi(e,3,c);_.Bi(b,1,f);_.Hd(e,1,b);this.b.set("ReloadState",e.G);_.V.a().b("eventReloadStateSaved",[])},a))};fk=function(a){var b=new Yj;_.N(b,1,a.top);_.N(b,2,a.left);_.N(b,3,a.width);_.N(b,4,a.height);_.N(b,5,a.focused);_.N(b,6,a.state);_.N(b,7,a.alwaysOnTop);return b};ck.prototype.read=function(){var a=this.j;this.j=null;_.V.a().b("eventReloadStateRead",[a&&a.G||null])};ck.prototype.reload=function(){window.chrome.runtime.reload()};
_.Y=function(a){this.a=new ck(a);this.b=a;window.chrome.runtime.onUpdateAvailable.addListener((0,_.r)(this.g,this))};_.ga("ace.core.ExtensionLibrary",_.Y);_.Y.prototype.g=function(){_.V.a().b("eventReloadClient",[]);_.ie(this.a.reload,864E5+288E5*Math.random(),this.a)};_.Y.prototype.q=function(a,b,c,d){a=_.V.b(b);null!=a&&_.n(d)&&d&&(d=a.h,null!=d&&null!=d.id&&(window.chrome.tabs.update(d.id,{selected:!0}),c&&window.chrome.tabs.get(d.id,function(a){_.di(a.windowId)})))};_.Y.prototype.selectTab=_.Y.prototype.q;
_.Y.prototype.h=function(a,b,c){c?pi(b,"width=500,height=400"):window.chrome.tabs.create({url:b,selected:!0},function(a){null!=a?_.ie(function(){window.chrome.tabs.get(a.id,function(a){_.di(a.windowId)})},2E3):pi(b)})};_.Y.prototype.openUrl=_.Y.prototype.h;_.Y.prototype.f=function(a,b){this.c=this.b.get(_.Vh);this.c.focus(b)};_.Y.prototype.focusMoleByFrameId=_.Y.prototype.f;_.Y.prototype.e=function(){_.V.a().nb()};_.Y.prototype.showApplication=_.Y.prototype.e;
_.Y.prototype.p=function(a,b){var c=new _.Uj(b);gk(this.a,c)};_.Y.prototype.saveReloadState=_.Y.prototype.p;_.Y.prototype.k=function(){this.a.read()};_.Y.prototype.readReloadState=_.Y.prototype.k;_.Y.prototype.l=function(){this.a.reload()};_.Y.prototype.reloadExtension=_.Y.prototype.l;_.Y.prototype.j=function(){_.V.a().Jc()};_.Y.prototype.onHostReady=_.Y.prototype.j;
var hk=function(a,b){if(a)this.focused=a.focused,this.alwaysOnTop=a.alwaysOnTop,this.top=a.top,this.left=a.left,this.width=a.width,this.height=a.height,this.state=a.state;else if(b){this.focused=b.contentWindow.document.hasFocus();this.alwaysOnTop=b.isAlwaysOnTop();var c=b.getBounds();this.top=c.top;this.left=c.left;this.width=c.width;this.height=c.height;this.state=b.isMinimized()?"minimized":"normal"}else this.alwaysOnTop=this.focused=!1,this.height=this.width=this.left=this.top=0,this.state=""}; hk.prototype.isMinimized=function(){return"minimized"==this.state};
var ik=function(a,b,c){this.a=c||new hk;c||(this.a.alwaysOnTop=$h(a.get(_.Wh).a))};ik.prototype.getProperties=function(){return this.a};var kk=function(a,b,c){(b=b.f)?jk(a.get(_.Vh),b,function(b){c(new ik(a,0,b))}):c(new ik(a))};var lk=function(){_.E.call(this);this.a=new _.zi};_.p(lk,_.E);lk.prototype.da=function(a){var b,c=Array.prototype.slice.call(arguments);(0,_.v)(this.a.B(),function(a){b=a.apply(null,c)});return b};lk.prototype.addListener=function(a){this.a.add(a)};lk.prototype.removeListener=function(a){this.a.remove(a)};lk.prototype.n=function(){this.a.clear();lk.t.n.call(this)};
var ok=function(){_.E.call(this);this.b=[];this.h=new lk;_.G(this,this.h);this.f=new lk;_.G(this,this.f);this.onClosed=new lk;this.g=!1;this.c=null;this.k=(0,_.r)(this.A,this);mk.addListener(this.k);this.l=(0,_.r)(this.w,this);nk.addListener(this.l)};_.p(ok,_.E);ok.prototype.n=function(){Bj(this)||void 0!=this.a&&window.chrome.windows.remove(this.a);pk(this);this.k&&(mk.removeListener(this.k),nk.removeListener(this.l));_.F(this.onClosed);ok.t.n.call(this)};
var mk=window.chrome.windows&&window.chrome.windows.onRemoved,nk=window.chrome.windows&&window.chrome.windows.onFocusChanged;ok.prototype.create=function(a){window.chrome.windows.create(a,(0,_.r)(function(a){this.C?window.chrome.windows.remove(a.id):(this.a=a.id,qk(this))},this))};
var qk=function(a){if(null!=a.b&&Aj(a))if(Bj(a))pk(a);else{for(;a.b.length&&!Bj(a);)a.b.shift()(a);a.b=null}},Aj=function(a){return!(!_.ka(a.a)||!a.e)},nj=function(a,b){Bj(a)?pk(a):null==a.b?b(a):a.b.push(b)},Bj=function(a){return!(!a.e||!a.e.closed)};ok.prototype.A=function(){Bj(this)&&pk(this)};var pk=function(a){if(!a.g){var b=a.onClosed;a.onClosed=new lk;_.ie((0,_.r)(function(){this.g||(this.g=!0,b.da(this));_.F(b)},a))}};
ok.prototype.w=function(a){if(a!=this.a){if(null===this.c||this.c)this.c&&(this.c=!1),this.f.da(this)}else this.c=!0,this.h.da(this)};var qj=function(a){var b;b=a.a?a.e:null;return!b||Bj(a)?null:b};ok.prototype.isMinimized=function(){return this.u.isMinimized()};ok.prototype.isMaximized=function(){return this.u.isMaximized()};ok.prototype.minimize=function(){nj(this,(0,_.r)(function(){window.chrome.windows.update(this.a,{state:"minimized"})},this))};
ok.prototype.focus=function(){nj(this,(0,_.r)(function(){window.chrome.windows.update(this.a,{focused:!0})},this))};var rk=function(a,b){nj(a,(0,_.r)(function(){window.chrome.windows.update(this.a,{drawAttention:b})},a))};ok.prototype.getProperties=function(a){nj(this,_.ha(sk,[this],function(b){a(b[0])}))}; var sk=function(a,b){window.chrome.windows.getAll(function(c){var d={};(0,_.v)(c,function(a){d[a.id]=a});var e=[];(0,_.v)(a,function(a){var b;a&&Aj(a)&&!Bj(a)&&(b=d[a.a]);var c;b&&(c=new hk(b));e.push(c)});b(e)})};
var tk=function(){ok.call(this)};_.p(tk,ok);tk.prototype.setTitle=function(a){nj(this,(0,_.r)(function(){qj(this).document.title=a},this))};
var vk=function(a,b){a.q=b;nj(a,(0,_.r)(function(){uk(this)},a))},wk=function(a,b){a.v=b;nj(a,(0,_.r)(function(){uk(this)},a))},uk=function(a){var b=qj(a).document,c=b.querySelector("HEAD"),d=c.querySelectorAll("link[rel='shortcut icon']"),e=qi("icon-24x24.png");a=[a.q||e,a.v];for(var e=_.Fc()?2:1,f="",g=0;g<e;++g)if(a[g]&&a!=f){var f=a[g],l=d[g];l||(l=b.createElement("LINK"),c.appendChild(l));l.rel="shortcut icon";var q=a[g];l.type=hi(q,".ico")?"image/x-icon":hi(q,".gif")?"image/gif":"image/png"; l.href=a[g]}};
var zk,xk,Ak;_.yk=function(a){this.a={};if(a)for(var b=0;b<a.length;b++)this.a[xk(a[b])]=null;for(var c in Object.prototype);};zk={};xk=function(a){return a in zk||32==String(a).charCodeAt(0)?" "+a:a};Ak=function(a){return 32==a.charCodeAt(0)?a.substr(1):a};_.h=_.yk.prototype;_.h.add=function(a){this.a[xk(a)]=null};_.h.clear=function(){this.a={}};_.h.clone=function(){var a=new _.yk,b;for(b in this.a)a.a[b]=null;return a};_.h.contains=function(a){return xk(a)in this.a};
_.h.forEach=function(a,b){for(var c in this.a)a.call(b,Ak(c),void 0,this)};_.h.V=Object.keys?function(){return Object.keys(this.a).length}:function(){var a=0,b;for(b in this.a)a++;return a};_.h.B=Object.keys?function(){return Object.keys(this.a).map(Ak,this)}:function(){var a=[],b;for(b in this.a)a.push(Ak(b));return a};_.h.P=function(){for(var a in this.a)return!1;return!0};_.h.remove=function(a){a=xk(a);return a in this.a?(delete this.a[a],!0):!1};_.h.ha=function(){return ni(this.B())};
_.Z=function(a){_.E.call(this);this.h=a;this.a={};this.c={};this.b=new _.yk;_.ga("__onPanelLoad",(0,_.r)(this.I,this));this.p=a.get(_.Rh);a=new _.I(this);_.G(this,a);a.listen(_.V,"onStatusChange",this.u)};_.p(_.Z,_.E);_.ga("ace.core.PanelsManager",_.Z);_.Z.prototype.n=function(){for(var a in this.a)this.gb(this.a[a]);_.Z.t.n.call(this)};
_.Z.prototype.isMaximized=function(a,b){var c=function(a){a=a?!a.isMinimized():null;_.V.a().b("eventIsMinimizedResponse",[b,a])},d=this.a[b];d?d.getProperties(c):c(void 0)};_.Z.prototype.isMaximized=_.Z.prototype.isMaximized;
_.Z.prototype.J=function(a,b,c,d,e,f,g,l,q,C){a="panel.html?"+b;d=d||_.T("CHROME_EXT_SHORT_NAME");b=jj(this,b,l||b,a,d,e,g);nj(b,(0,_.r)(this.k,this,c));c=new xi(280,420);q||C?(q=q||null,e=C||null,C=this.h.get(_.Sh).a,q=_.dk(q,e),(e=C.a[q])&&delete C.a[q],C=e?e.Ja():null):C=null;f=lj(this,c,!!f,C);mj(this,b.id,f)};_.Z.prototype.openPanel=_.Z.prototype.J;
_.Z.prototype.v=function(a,b,c,d,e,f,g){a="dialog.html?"+b;d=d||_.T("CHROME_EXT_SHORT_NAME");b=jj(this,b,b,a,d);nj(b,(0,_.r)(this.k,this,c));c=lj(this,new xi(f,g),e,null);c.ad=!0;mj(this,b.id,c);return b};_.Z.prototype.openDialog=_.Z.prototype.v;var jj=function(a,b,c,d,e,f,g){a.a[b]&&a.gb(a.a[b]);var l=new tk;l.id=b;l.key=c;l.url=d;l.setTitle(e);vk(l,f);wk(l,g);a.a[b]=l;a.c[c]=b;return l};_.Z.prototype.k=function(a,b){b.p=new gj(a,qj(b).document);_.G(b,b.p)};
var lj=function(a,b,c,d){b={focus:c,ya:null,width:b.width,height:b.height,minimize:!1};if(d){b.top=_.y(d,1);b.left=_.y(d,2);c=_.y(d,3);var e=_.y(d,4);_.y(d,7)?(b.width=Math.max(b.width,c),b.height=Math.max(b.height,e)):(b.width=c,b.height=e);"minimized"==d.getState()&&(b.minimize=!0);b.ya=_.y(d,7);b.focus=_.y(d,5)}b.ya="boolean"==typeof b.ya?b.ya:$h(a.h.get(_.Wh).a);return b},mj=function(a,b,c){var d=a.a[b];d.onClosed.addListener((0,_.r)(a.gb,a));d.h.addListener((0,_.r)(a.A,a));d.f.addListener((0,_.r)(a.w,
a));c.minimize&&d.minimize();b="panel";c.ya||(b=ji()?"popup":"detached_panel");c.ad&&(b="popup");var e={type:b,url:d.url,focused:c.focus,width:c.width,height:c.height};if(b=null!=c.top&&null!=c.left)e.top=c.top,e.left=c.left;b||c.ya?d.create(e):ek(a,Object.keys(a.c),(0,_.r)(function(a){var b=window.screen,c;c=new xi(260,460);var q=new xi(280,420);c=new xi(Math.max(c.width,q.width),Math.max(c.height,q.height));for(var C=b.availWidth,L=b.availHeight-50,q=b.availTop+L%c.height,b=b.availLeft+C%c.width,
C=Math.floor(C/c.width),fa=Math.floor(L/c.height),L=Array(C*fa),P=0;P<a.length;P++){var oa=a[P];if(oa){for(var Ob=[oa.left,oa.left+oa.width-1],oa=[oa.top,oa.top+oa.height-1],qa=0;2>qa;qa++)Ob[qa]=Math.floor(Math.max(0,Ob[qa]-b)/c.width),oa[qa]=Math.floor(Math.max(0,oa[qa]-q)/c.height);for(qa=Ob[0];qa<=Ob[1];qa++)for(var eb=oa[0];eb<=oa[1];eb++)qa<C&&eb<fa&&(L[qa+eb*C]=1)}}a=L.length-1;for(P=L.length-1;0<=P;P--)if(!L[P]){a=P;break}L=a%C*c.width;e.top=q+Math.floor(a/C)*c.height+(c.height-e.height);
e.left=b+L+(c.width-e.width);d.create(e)},a))};_.Z.prototype.g=function(a,b){var c=this.a[b];c&&_.F(c)};_.Z.prototype.closePanel=_.Z.prototype.g;_.Z.prototype.f=function(){for(var a in this.a)0==this.a[a].url.indexOf("panel.html")&&this.g(0,a)};_.Z.prototype.closeAllPanels=_.Z.prototype.f;_.Z.prototype.setTitle=function(a,b,c){(a=this.a[b])&&a.setTitle(c)};_.Z.prototype.setTitle=_.Z.prototype.setTitle;_.Z.prototype.q=function(a,b,c){this.a[b]&&rk(this.a[b],c)};_.Z.prototype.drawAttention=_.Z.prototype.q;
_.Z.prototype.focus=function(a){if(this.a[a]){var b=this.a[a];b.getProperties((0,_.r)(function(a){if(a&&(a=qj(b),0==a.outerWidth&&0==a.outerHeight)){this.gb(b);return}b.focus()},this))}};_.Z.prototype.L=function(a,b,c){this.a[b]&&vk(this.a[b],c)};_.Z.prototype.setPresence=_.Z.prototype.L;_.Z.prototype.K=function(a,b,c){this.a[b]&&wk(this.a[b],c)};_.Z.prototype.setAvatar=_.Z.prototype.K;_.Z.prototype.e=function(a,b,c){for(var d in this.a)(b||this.b.contains(d))&&this.l(0,d,b,c);b||this.b.clear()};
_.Z.prototype.minimizeAllPanelsIfTopmost=_.Z.prototype.e;_.Z.prototype.l=function(a,b,c,d){var e=this.a[b];e&&e.getProperties((0,_.r)(function(a){if(a&&a.alwaysOnTop&&!this.C)if(c){var g;(g=!d)||(g=new _.ri(a.left,a.top,a.width,a.height),g=g.left<=d.left+d.width&&d.left<=g.left+g.width&&g.top<=d.top+d.height&&d.top<=g.top+g.height);g&&!a.isMinimized()&&(e.minimize(),this.b.add(b))}else window.chrome.windows.update(e.a,{state:"normal"}),this.b.remove(b)},this))};
_.Z.prototype.minimizePanelIfTopmost=_.Z.prototype.l;_.Z.prototype.I=function(a){var b=this.a[a.location.search.substring(1)];b&&(b.e=a,qk(b))};var jk=function(a,b,c){a=a.a[a.c[b]];!a||Bj(a)?c(void 0):a.getProperties(c)},ek=function(a,b,c){var d=[];(0,_.v)(b,(0,_.r)(function(a){d.push(this.a[this.c[a]])},a));sk(d,c)};_.Z.prototype.gb=function(a){this.a[a.id]==a&&(this.b.remove(a.id),delete this.c[a.key],delete this.a[a.id],_.F(a))};_.Z.prototype.A=function(a){this.a[a.id]==a&&this.b.remove(a.id)}; _.Z.prototype.w=function(a){this.a[a.id]==a&&_.V.a().b("eventBlurred",[a.id])};_.Z.prototype.u=function(){3==this.p.a&&this.f()};
_.Bk=function(a){_.E.call(this);this.k=a;this.a=new _.B;this.h=new _.B;this.c=new Mj;_.G(this,this.c);this.g=(0,_.r)(this.dd,this);window.chrome.notifications.onClosed.addListener(this.g);this.e=(0,_.r)(this.Mc,this);window.chrome.notifications.onClicked.addListener(this.e);this.f=(0,_.r)(this.cd,this);window.chrome.notifications.onButtonClicked.addListener(this.f)};_.p(_.Bk,_.E);_.ga("ace.core.NotificationManager",_.Bk);
_.Bk.prototype.n=function(){_.v(this.a.B(),_.F);this.a.clear();window.chrome.notifications.onClosed.removeListener(this.g);window.chrome.notifications.onClicked.removeListener(this.e);window.chrome.notifications.onButtonClicked.removeListener(this.f);_.Bk.t.n.call(this)};
_.Bk.prototype.p=function(a,b){var c;if(b&&b.Content){c=[b.Id.ServiceUrl,b.Id.ServiceId].join(";");0==c.indexOf("bc")?c=new Ij(c,2):0==c.indexOf("hangout")?(c=new Ij(c,7),c.b.push(new Jj("join hangout")),c.b.push(new Jj("ignore"))):c=void 0;c.setTitle(b.Content.TitleText);c.g=b.Content.SubtitleText;c.j=b.Content.BodyText;c.c=b.Content.BodyTextId;var d=0;b.Content.EndTimeMs&&(d=b.Content.EndTimeMs,(0,window.isNaN)(d)||!(0,window.isFinite)(d))&&(d=0);d=d||(0,_.m)()+1E4;c.e=d;if(b.Content.ServiceIcon){var d=
c,e=b.Content.ServiceIcon;e&&(0==e.indexOf("images_4/")&&(e=window.chrome.runtime.getURL(e)),d.k=e)}b.Content.FrameId&&(c.f=b.Content.FrameId)}else c=null;c&&(_.V.a().b("eventLogImpression",["qnop"]),Nj(this.c,c)||(this.c.add(c),Ck(this,c)))};_.Bk.prototype.registerNotification=_.Bk.prototype.p;
var Ck=function(a,b){2==b.h||b.f?kk(a.k,b,function(c){c=c.getProperties();c.focused||c.alwaysOnTop||Dk(a,b)}):Dk(a,b)},Dk=function(a,b){var c=b.a,d=b.e-(0,_.m)();0>=d?a.fc(c):(a.a.set(c,b),window.chrome.notifications.create(c,Lj(b),function(){_.V.a().b("eventLogImpression",["qtod"])}),_.je(a.h.get(c,null)),b.e!=Number.MAX_VALUE&&a.h.set(c,_.ie((0,_.r)(a.fc,a,c),d)),_.V.a().b("eventLogImpression",["qnst"]))};_.Bk.prototype.b=function(){(0,_.v)((0,_.xa)(this.a.B(),ai),this.Fa,this)};
_.Bk.prototype.cleanAllNotifications=_.Bk.prototype.b;_.Bk.prototype.l=function(a,b){var c=this.a.get(b);c&&this.Fa(c)};_.Bk.prototype.cleanANotification=_.Bk.prototype.l;_.h=_.Bk.prototype;_.h.Fa=function(a){a=a.a;window.chrome.notifications.clear(a,_.na);this.a.remove(a)};_.h.dd=function(a,b){b&&this.a.get(a)&&(this.a.remove(a),Ek(a,"toastEventOnClose"))};_.h.Mc=function(a){var b=this.a.get(a);b&&(Ek(a,"toastEventOnBody"),this.Fa(b))};
_.h.cd=function(a,b){var c=this.a.get(a);c&&(Ek(a,"toastEventOnButton",c.b[b].name),this.Fa(c))};_.h.fc=function(a){var b=this.a.get(a);b&&(Ek(a,"toastEventOnTimeout"),this.Fa(b))};var Ek=function(a,b,c){var d=_.V;(d=d&&d.a())&&!d.C&&_.V.a().b(b,[a,c,"",!1])};
_.Fk=function(a){_.x(this,a,"f.mt",null)};_.p(_.Fk,_.w);_.z("f.mt",_.Fk);_.Gk=function(a){_.x(this,a,"er",null)};_.p(_.Gk,_.w);_.z("er",_.Gk);_.Gk.prototype.wb=function(){return _.y(this,9)};_.Gk.prototype.getData=function(){return _.y(this,4)};new _.zi;_.D&&_.Za(8);var Hk=function(){throw Error("y");};Hk.prototype.a=null;Hk.prototype.toString=function(){return this.content};var Ik=function(){Hk.call(this)};_.p(Ik,Hk);(function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){var e=new b(String(a));void 0!==d&&(e.a=d);return e}})(Ik);(function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){var e=String(a);if(!e)return"";e=new b(e);void 0!==d&&(e.a=d);return e}})(Ik);
var Jk=function(a,b){_.Uc.call(this,a,b)};_.p(Jk,_.Uc);_.Kk=function(a){this.a=a?_.y(a,1)||-1:-1};_.Lk=new _.Kk;_.Mk=function(){};_.p(_.Mk,_.ne);_.Mk.prototype.b=function(){};_.Mk.prototype.b.lc=!0;_.Mk.t||_.p(_.Mk,_.ne);_.U.a={};_.U.a.lb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";_.U.a.jb=_.U.a.lb+"0123456789";_.U.a.mb=_.U.a.lb.length;_.U.a.kb=_.U.a.jb.length;_.U.a.Jb=-2147483648;_.U.a.yd=function(a){for(var b=0,c=a.length-1;0<=c;c--)b=b*(0==c?_.U.a.mb:_.U.a.kb)+_.U.a.jb.indexOf(a.charAt(c));return b+_.U.a.Jb};_.U.a.toString=function(a){var b=[],c=0;a-=_.U.a.Jb;b[c++]=_.U.a.lb.charAt(a%_.U.a.mb);for(a=Math.floor(a/_.U.a.mb);0<a;)b[c++]=_.U.a.jb.charAt(a%_.U.a.kb),a=Math.floor(a/_.U.a.kb);return b.join("")};
new Jk(_.Wc,"f_req");
}catch(e){_._DumpException(e)}
try{
var Cn=function(a,b,c){a.timeOfStartCall=(new Date).getTime();if(b&&JSON&&JSON.stringify){var d=JSON.stringify(b);200>=d.length&&(a.psdJson=d)}d=c||_.k;d.GOOGLE_FEEDBACK_START_ARGUMENTS=arguments;var e=a.serverUri||"//www.google.com/tools/feedback",f=d.GOOGLE_FEEDBACK_START;if(f)f.apply(d,arguments);else{var e=e+"/load.js?",g;for(g in a)f=a[g],null!=f&&!_.ia(f)&&(e+=(0,window.encodeURIComponent)(g)+"="+(0,window.encodeURIComponent)(f)+"&");g=d.document;d=g.createElement("script");d.src=e;g.body.appendChild(d)}}; _.ga("userfeedback.api.startFeedback",Cn);
var Dn=function(){_.I.call(this);this.listen(window,"unload",this.D);window.document.title=_.T("CHROME_EXT_SHORT_NAME")+": "+_.T("CHROME_EXT_FEEDBACK_SUBTITLE");_.S("system-legend").innerText=_.T("QUASAR_FEEDBACK_SYSTEM_LEGEND");_.S("system-platform-label").innerText=_.T("QUASAR_FEEDBACK_PLATFORM_LABEL");_.S("system-platform-value").innerText=window.navigator.platform;_.S("system-user-agent-label").innerText=_.T("QUASAR_FEEDBACK_USER_AGENT_LABEL");_.S("system-user-agent-value").innerText=window.navigator.userAgent;
_.S("user-legend").innerText=_.T("CHROME_EXT_FEEDBACK_COMMENTS");_.S("privacy-legend").innerText=_.T("QUASAR_FEEDBACK_PRIVACY_LEGEND");_.S("privacy-text").innerText=_.T("QUASAR_FEEDBACK_PRIVACY_TEXT");var a=_.S("submit-button");a.innerText=_.T("QUASAR_FEEDBACK_SUBMIT_BUTTON");this.listen(a,"click",this.b);a=_.S("cancel-button");a.innerText=_.T("QUASAR_FEEDBACK_CANCEL_BUTTON");this.listen(a,"click",this.a);_.S("user-text-value").focus()};_.p(Dn,_.I);
Dn.prototype.b=function(){var a=_.S("user-text-value").value;if(a&&(a=a.trim())){var a={flow:"submit",serverUri:_.T("QUASAR_FEEDBACK_SERVER_URI"),productId:83052,locale:window.chrome.i18n.getMessage("@@ui_locale"),report:{description:a},callback:this.a},b={version:window.chrome.runtime.getManifest().version,build:window.chrome.runtime.id};_.S("submit-button").disabled=!0;Cn(a,b)}};Dn.prototype.a=function(){window.close()};window.addEventListener("load",function(){new Dn},!1);

}catch(e){_._DumpException(e)}
}).call(this,this.default_feedback);
// Google Inc.
