"use strict";this.default_settings=this.default_settings||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,da,ea;_.n=function(a){return void 0!==a};ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};da=function(a,b,c){return a.call.apply(a.bind,arguments)};
ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.t=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Fd=function(a,c,f){for(var g=Array(arguments.length-2),l=2;l<arguments.length;l++)g[l-2]=arguments[l];return b.prototype[c].apply(a,g)}};
_.ga=function(a,b){var c=a.split("."),d=_.k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.r=function(a,b,c){_.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return _.r.apply(null,arguments)};
_.ia=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ja=function(a){return"function"==ea(a)};_.ka=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.la=function(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ma=function(a){return"array"==ea(a)};_.na=function(){};_.pa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}; _.p(_.pa,Error);_.pa.prototype.name="CustomError";
var ra,ua,ta;ra=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.sa=function(a,b){return-1!=a.indexOf(b)};
ua=function(a,b){for(var c=0,d=ra(String(a)).split("."),e=ra(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var l=d[g]||"",q=e[g]||"",C=RegExp("(\\d*)(\\D*)","g"),L=RegExp("(\\d*)(\\D*)","g");do{var fa=C.exec(l)||["","",""],P=L.exec(q)||["","",""];if(0==fa[0].length&&0==P[0].length)break;c=ta(0==fa[1].length?0:(0,window.parseInt)(fa[1],10),0==P[1].length?0:(0,window.parseInt)(P[1],10))||ta(0==fa[2].length,0==P[2].length)||ta(fa[2],P[2])}while(0==c)}return c}; ta=function(a,b){return a<b?-1:a>b?1:0};
_.u=Array.prototype;_.va=_.u.indexOf?function(a,b,c){return _.u.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.wa=_.u.lastIndexOf?function(a,b,c){return _.u.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.t(a))return _.t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.v=_.u.forEach?function(a,b,c){_.u.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.xa=_.u.filter?function(a,b,c){return _.u.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.t(a)?a.split(""):a,l=0;l<d;l++)if(l in g){var q=g[l];b.call(c,q,l,a)&&(e[f++]=q)}return e};_.ya=_.u.map?function(a,b,c){return _.u.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.za=_.u.reduce?function(a,b,c,d){d&&(b=(0,_.r)(b,d));return _.u.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.v)(a,function(c,g){e=b.call(d,e,c,g,a)});return e};_.Aa=_.u.some?function(a,b,c){return _.u.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Ba=function(a,b){var c=(0,_.va)(a,b),d;(d=0<=c)&&_.u.splice.call(a,c,1);return d};
_.Ca=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var Ea,Ga;_.Da=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Ea=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Fa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Ga=function(a){var b=arguments.length;if(1==b&&_.ma(arguments[0]))return Ga.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var Ha;_.w=function(){};_.x=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.b=0===c?-1:0;a.G=b;t:{if(a.G.length&&(b=a.G.length-1,(c=a.G[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.j=b-a.b;a.c=c;break t}a.j=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.b,a.G[c]=a.G[c]||[]):a.c[c]=a.c[c]||[]};_.y=function(a,b){return b<a.j?a.G[b+a.b]:a.c[b]};_.w.prototype.toString=function(){return this.G.toString()};_.z=function(a,b){Ha[a]=b;b.messageId=a};Ha={};
Ga("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));Ga("action","cite","data","formaction","href","manifest","poster","src");Ga("embed","iframe","link","object","script","style","template");_.Ia="StopIteration"in _.k?_.k.StopIteration:Error("f");_.Ja=function(){};_.Ja.prototype.next=function(){throw _.Ia;};_.Ja.prototype.ha=function(){return this};t:{var Ka=_.k.navigator;if(Ka){var La=Ka.userAgent;if(La){_.A=La;break t}}_.A=""};_.B=function(a,b){this.b={};this.a=[];this.j=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("h");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.B?(c=a.M(),d=a.B()):(c=_.Fa(a),d=Ea(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.B.prototype.V=function(){return this.c};_.B.prototype.B=function(){Ma(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.B.prototype.M=function(){Ma(this);return this.a.concat()};
_.Oa=function(a,b){return Na(a.b,b)};_.B.prototype.P=function(){return 0==this.c};_.B.prototype.clear=function(){this.b={};this.j=this.c=this.a.length=0};_.B.prototype.remove=function(a){return Na(this.b,a)?(delete this.b[a],this.c--,this.j++,this.a.length>2*this.c&&Ma(this),!0):!1};
var Ma=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Na(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Na(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.B.prototype;_.h.get=function(a,b){return Na(this.b,a)?this.b[a]:b};_.h.set=function(a,b){Na(this.b,a)||(this.c++,this.a.push(a),this.j++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
_.h.clone=function(){return new _.B(this)};_.h.ha=function(a){Ma(this);var b=0,c=this.a,d=this.b,e=this.j,f=this,g=new _.Ja;g.next=function(){for(;;){if(e!=f.j)throw Error("i");if(b>=c.length)throw _.Ia;var g=c[b++];return a?g:d[g]}};return g};var Na=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.Pa=function(a){if("function"==typeof a.B)return a.B();if(_.t(a))return a.split("");if(_.la(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ea(a)};
_.Qa=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(_.la(a)||_.t(a))(0,_.v)(a,b,c);else{var d;if("function"==typeof a.M)d=a.M();else if("function"!=typeof a.B)if(_.la(a)||_.t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=_.Fa(a);else d=void 0;for(var e=_.Pa(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};
var Ra,Ta,Ua,Wa,Xa,Ya,$a,ab;Ra=_.sa(_.A,"Opera")||_.sa(_.A,"OPR");_.D=_.sa(_.A,"Trident")||_.sa(_.A,"MSIE");_.Sa=_.sa(_.A,"Gecko")&&!_.sa(_.A.toLowerCase(),"webkit")&&!(_.sa(_.A,"Trident")||_.sa(_.A,"MSIE"));Ta=_.sa(_.A.toLowerCase(),"webkit");Ua=_.k.navigator||null;_.Va=Ua&&Ua.platform||"";Wa=function(){var a=_.k.document;return a?a.documentMode:void 0};
Xa=function(){var a="",b;if(Ra&&_.k.opera)return a=_.k.opera.version,_.ja(a)?a():a;_.Sa?b=/rv\:([^\);]+)(\)|;)/:_.D?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Ta&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(_.A))?a[1]:"");return _.D&&(b=Wa(),b>(0,window.parseFloat)(a))?String(b):a}();Ya={};_.Za=function(a){return Ya[a]||(Ya[a]=0<=ua(Xa,a))};$a=_.k.document;ab=$a&&_.D?Wa()||("CSS1Compat"==$a.compatMode?(0,window.parseInt)(Xa,10):5):void 0;
_.E=function(){this.C=this.C;this.j=this.j};_.E.prototype.C=!1;_.E.prototype.Bb=function(){return this.C};_.E.prototype.D=function(){this.C||(this.C=!0,this.n())};_.G=function(a,b){_.bb(a,_.ha(_.F,b))};_.bb=function(a,b){a.C?b.call(void 0):(a.j||(a.j=[]),a.j.push(_.n(void 0)?(0,_.r)(b,void 0):b))};_.E.prototype.n=function(){if(this.j)for(;this.j.length;)this.j.shift()()};_.F=function(a){a&&"function"==typeof a.D&&a.D()};
_.cb=!_.D||_.D&&9<=ab;!_.Sa&&!_.D||_.D&&_.D&&9<=ab||_.Sa&&_.Za("1.9.1");_.D&&_.Za("9");var db=function(a){db[" "](a);return a};db[" "]=_.na;_.fb=function(a,b){try{return db(a[b]),!0}catch(c){}return!1};var gb,hb;gb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.jb=function(a){if(hb){hb=!1;var b=_.k.location;if(b){var c=b.href;if(c&&(c=_.ib(c))&&c!=b.hostname)throw hb=!0,Error();}}return a.match(gb)};hb=Ta;_.ib=function(a){return(a=_.jb(a)[3]||null)?(0,window.decodeURI)(a):a};
var kb=!_.D||_.D&&9<=ab,lb=_.D&&!_.Za("9");!Ta||_.Za("528");_.Sa&&_.Za("1.9b")||_.D&&_.Za("8")||Ra&&_.Za("9.5")||Ta&&_.Za("528");_.Sa&&!_.Za("8")||_.D&&_.Za("9");_.H=function(a,b){this.type=a;this.b=this.target=b;this.tc=!0};_.H.prototype.Xa=function(){this.tc=!1};var mb=function(a,b){_.H.call(this,a?a.type:"");this.b=this.target=null;this.clientY=this.clientX=this.yb=this.xb=0;this.a=this.state=null;if(a){this.a=a;this.type=a.type;this.target=a.target||a.srcElement;this.b=b;var c=a.relatedTarget;c&&_.Sa&&_.fb(c,"nodeName");Object.defineProperties?Object.defineProperties(this,{xb:{configurable:!0,enumerable:!0,get:this.ac,set:this.wd},yb:{configurable:!0,enumerable:!0,get:this.bc,set:this.xd}}):(this.xb=this.ac(),this.yb=this.bc());this.clientX=void 0!==a.clientX?
a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;a.defaultPrevented&&this.Xa()}};_.p(mb,_.H);_.h=mb.prototype;_.h.Xa=function(){mb.t.Xa.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,lb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};_.h.ac=function(){return Ta||void 0!==this.a.offsetX?this.a.offsetX:this.a.layerX};
_.h.wd=function(a){Object.defineProperties(this,{xb:{writable:!0,enumerable:!0,configurable:!0,value:a}})};_.h.bc=function(){return Ta||void 0!==this.a.offsetY?this.a.offsetY:this.a.layerY};_.h.xd=function(a){Object.defineProperties(this,{yb:{writable:!0,enumerable:!0,configurable:!0,value:a}})};
var nb,pb;nb="closure_listenable_"+(1E6*Math.random()|0);_.ob=function(a){return!(!a||!a[nb])};pb=0;var qb=function(a,b,c,d,e){this.qa=a;this.proxy=null;this.src=b;this.type=c;this.Ua=!!d;this.ab=e;this.key=++pb;this.removed=this.Ta=!1},rb=function(a){a.removed=!0;a.qa=null;a.proxy=null;a.src=null;a.ab=null};var sb=function(a){this.src=a;this.a={};this.b=0};sb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=tb(a,b,d,e);-1<g?(b=a[g],c||(b.Ta=!1)):(b=new qb(b,this.src,f,!!d,e),b.Ta=c,a.push(b));return b};sb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=tb(e,b,c,d);return-1<b?(rb(e[b]),_.u.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var ub=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=_.Ba(a.a[c],b);d&&(rb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};sb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,rb(d[e]);delete this.a[c];this.b--}return b}; var vb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=tb(a,c,d,e));return-1<b?a[b]:null},tb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.qa==b&&f.Ua==!!c&&f.ab==d)return e}return-1};
var wb,xb,yb,Db,Eb,Jb,Ib,Fb,Cb,Kb;wb="closure_lm_"+(1E6*Math.random()|0);xb={};yb=0;_.zb=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)_.zb(a,b[f],c,d,e);return null}c=_.Ab(c);return _.ob(a)?a.listen(b,c,d,e):_.Bb(a,b,c,!1,d,e)};_.Bb=function(a,b,c,d,e,f){if(!b)throw Error("l");var g=!!e,l=Cb(a);l||(a[wb]=l=new sb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=Db();c.proxy=d;d.src=a;d.qa=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Eb(b.toString()),d);yb++;return c};
Db=function(){var a=Fb,b=kb?function(c){return a.call(b.src,b.qa,c)}:function(c){c=a.call(b.src,b.qa,c);if(!c)return c};return b};_.Gb=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)_.Gb(a,b[f],c,d,e);else c=_.Ab(c),_.ob(a)?a.Ib(b,c,d,e):a&&(a=Cb(a))&&(b=vb(a,b,c,!!d,e))&&_.Hb(b)};
_.Hb=function(a){if(_.ka(a)||!a||a.removed)return!1;var b=a.src;if(_.ob(b))return ub(b.U,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ua):b.detachEvent&&b.detachEvent(Eb(c),d);yb--;(c=Cb(b))?(ub(c,a),0==c.b&&(c.src=null,b[wb]=null)):rb(a);return!0};Eb=function(a){return a in xb?xb[a]:xb[a]="on"+a};Jb=function(a,b,c,d){var e=!0;if(a=Cb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ua==c&&!f.removed&&(f=Ib(f,d),e=e&&!1!==f)}return e};
Ib=function(a,b){var c=a.qa,d=a.ab||a.src;a.Ta&&_.Hb(a);return c.call(d,b)};
Fb=function(a,b){if(a.removed)return!0;if(!kb){var c;if(!(c=b))t:{c=["window","event"];for(var d=_.k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new mb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.b;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--){c.b=e[l];var q=Jb(e[l],f,!0,c),d=d&&q}for(l=0;l<e.length;l++)c.b=e[l],q=Jb(e[l],
f,!1,c),d=d&&q}return d}return Ib(a,new mb(b,this))};Cb=function(a){a=a[wb];return a instanceof sb?a:null};Kb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Ab=function(a){if(_.ja(a))return a;a[Kb]||(a[Kb]=function(b){return a.handleEvent(b)});return a[Kb]};
_.Lb=function(a){_.x(this,a,"h_cc",null)};_.p(_.Lb,_.w);_.z("h_cc",_.Lb);_.Lb.prototype.Z=function(){return _.y(this,19)};_.I=function(a){_.E.call(this);this.I=a;this.g={}};_.p(_.I,_.E);var Mb=[];_.I.prototype.listen=function(a,b,c,d){return _.Nb(this,a,b,c,d)};_.Nb=function(a,b,c,d,e,f){_.ma(c)||(c&&(Mb[0]=c.toString()),c=Mb);for(var g=0;g<c.length;g++){var l=_.zb(b,c[g],d||a.handleEvent,e||!1,f||a.I||a);if(!l)break;a.g[l.key]=l}return a};
_.I.prototype.Ib=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)this.Ib(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.I||this,c=_.Ab(c),d=!!d,b=_.ob(a)?vb(a.U,String(b),c,d,e):a?(a=Cb(a))?vb(a,b,c,d,e):null:null,b&&(_.Hb(b),delete this.g[b.key]);return this};_.I.prototype.removeAll=function(){_.Da(this.g,_.Hb);this.g={}};_.I.prototype.n=function(){_.I.t.n.call(this);this.removeAll()};_.I.prototype.handleEvent=function(){throw Error("m");};
var Pb,Qb,Rb;Pb=function(a){_.k.setTimeout(function(){throw a;},0)};_.Sb=function(a,b){var c=a;b&&(c=(0,_.r)(a,b));!_.ja(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(Qb||(Qb=Rb()),Qb(c)):_.k.setImmediate(c)};
Rb=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.sa(_.A,"Presto")&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.r)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.sa(_.A,"Trident")&&!_.sa(_.A,"MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.Tb;c.Tb=null;a()}};return function(a){d.next={Tb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")? function(a){var b=window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};
var Yb=function(a,b){Tb||Ub();Vb||(Tb(),Vb=!0);Wb.push(new Xb(a,b))},Tb,Ub=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve();Tb=function(){a.then(Zb)}}else Tb=function(){_.Sb(Zb)}},Vb=!1,Wb=[],Zb=function(){for(;Wb.length;){var a=Wb;Wb=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Pb(d)}}}Vb=!1},Xb=function(a,b){this.a=a;this.b=b};
_.J=function(){_.E.call(this);this.U=new sb(this);this.L=this;this.u=null};_.p(_.J,_.E);_.J.prototype[nb]=!0;_.h=_.J.prototype;_.h.addEventListener=function(a,b,c,d){_.zb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.Gb(this,a,b,c,d)};_.h.n=function(){_.J.t.n.call(this);this.U&&this.U.removeAll(void 0);this.u=null};_.h.listen=function(a,b,c,d){return this.U.add(String(a),b,!1,c,d)};_.h.Ib=function(a,b,c,d){return this.U.remove(String(a),b,c,d)}; _.h.da=function(a,b,c){a=this.U.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ua==b){var g=f.qa,l=f.ab||f.src;f.Ta&&ub(this.U,f);d=!1!==g.call(l,c)&&d}}return d&&0!=c.tc};
var $b=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},ac=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var cc;cc=function(a,b){this.b=0;this.f=void 0;this.a=this.c=null;this.j=this.e=!1;try{var c=this;a.call(b,function(a){bc(c,2,a)},function(a){bc(c,3,a)})}catch(d){bc(this,3,d)}};_.ec=function(){var a,b=new cc(function(b){a=b});return new dc(b,a)};cc.prototype.then=function(a,b,c){return fc(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};$b(cc);
var ic=function(a){0==a.b&&Yb(function(){var a=new gc(void 0);hc(this,a)},a)},hc=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.Ea)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?hc(c,b):(d=c.a.splice(e,1)[0],jc(c,d,3,b)))}}else bc(a,3,b)},lc=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||kc(a);a.a||(a.a=[]);a.a.push(b)},fc=function(a,b,c,d){var e={Ea:null,nc:null,pc:null};e.Ea=new cc(function(a,g){e.nc=b?function(c){try{var e=b.call(d,c);a(e)}catch(C){g(C)}}:
a;e.pc=c?function(b){try{var e=c.call(d,b);!_.n(e)&&b instanceof gc?g(b):a(e)}catch(C){g(C)}}:g});e.Ea.c=a;lc(a,e);return e.Ea};cc.prototype.g=function(a){this.b=0;bc(this,2,a)};cc.prototype.h=function(a){this.b=0;bc(this,3,a)};
var bc=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(ac(c)){a.b=1;c.then(a.g,a.h,a);return}if(_.ia(c))try{var d=c.then;if(_.ja(d)){mc(a,c,d);return}}catch(e){b=3,c=e}}a.f=c;a.b=b;kc(a);3!=b||c instanceof gc||nc(a,c)}},mc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.g(b))},f=function(b){d||(d=!0,a.h(b))};try{c.call(b,e,f)}catch(g){f(g)}},kc=function(a){a.e||(a.e=!0,Yb(a.k,a))};
cc.prototype.k=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)jc(this,a[b],this.b,this.f)}this.e=!1};var jc=function(a,b,c,d){if(2==c)b.nc(d);else{if(b.Ea)for(;a&&a.j;a=a.c)a.j=!1;b.pc(d)}},nc=function(a,b){a.j=!0;Yb(function(){a.j&&oc.call(null,b)})},oc=Pb,gc=function(a){_.pa.call(this,a)};_.p(gc,_.pa);gc.prototype.name="cancel";var dc=function(a,b){this.b=a;this.a=b};
var pc,qc,rc,sc,tc,uc,vc,yc,zc,Ac,Bc,Cc,Dc;vc=uc=tc=sc=rc=qc=pc=!1;var wc=_.A;wc&&(-1!=wc.indexOf("Firefox")?pc=!0:-1!=wc.indexOf("Camino")?qc=!0:-1!=wc.indexOf("iPad")?sc=!0:-1!=wc.indexOf("iPhone")||-1!=wc.indexOf("iPod")?rc=!0:-1!=wc.indexOf("Chrome")?uc=!0:-1!=wc.indexOf("Android")?tc=!0:-1!=wc.indexOf("Safari")&&(vc=!0));_.xc=pc;yc=qc;zc=rc;Ac=sc;Bc=tc;Cc=uc;Dc=vc;
_.Ec=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.Fc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.Gc=function(a,b){this.j=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.e=null;this.h=b||"u";this.a=this.g=null;this.f=[]};_.Gc.prototype.message=function(){var a={};a.i=this.a;a.m=this.f;a.r=this.h;a.o=this.g;a.s=this.b;a.st=this.c;a.d=this.e;a.dt=this.j;return a};_.ga("ace.base.Message.prototype.message",_.Gc.prototype.message);
_.Hc=function(a,b){for(var c in b)switch(c){case "r":a.h=b[c];break;case "i":a.a=b[c];break;case "m":a.f=b[c];break;case "o":a.g=b[c];break;case "s":a.b=b[c];break;case "d":a.e=b[c];break;case "st":a.c=b[c];break;case "dt":a.j=b[c]}return a};_.Ic=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))};_.Jc=function(a,b){null!=b&&(a.a=b)};_.Kc=function(a,b){"object"==typeof b?a.f=b:a.f=[b]};_.Gc.prototype.source=function(){return this.b};_.Gc.prototype.target=function(){return this.e}; _.Gc.prototype.content=function(){return this.f};
_.Lc=function(a,b,c,d,e){_.E.call(this);this.b=a;this.Qa=b;this.a=typeof b;this.Db=c?c:!1;this.ba=!0;this.zb=d?d:!1;this.qb=e?e:!1};_.p(_.Lc,_.E);_.h=_.Lc.prototype;_.h.n=function(){_.Lc.t.n.call(this);this.b="";this.Qa=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.F=function(){return this.Qa};_.h.setEnabled=function(a){this.ba=a};
var Mc=function(a){return(a=a.exec(_.A))?a[1]:""},Nc=function(){if(_.xc)return Mc(/Firefox\/([0-9.]+)/);if(_.D||Ra)return Xa;if(Cc)return Mc(/Chrome\/([0-9.]+)/);if(Dc)return Mc(/Version\/([0-9.]+)/);if(zc||Ac){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.A))return a[1]+"."+a[2]}else{if(Bc)return(a=Mc(/Android\s+([0-9.]+)/))?a:Mc(/Version\/([0-9.]+)/);if(yc)return Mc(/Camino\/([0-9.]+)/)}return""}();
_.Pc=function(a){_.E.call(this);this.a=new _.B;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&_.Oc(this,a)};_.p(_.Pc,_.E);_.Qc=0<=ua(Nc,"23.0.1262.0")&&!_.Fc();_.Pc.prototype.n=function(){_.Pc.t.n.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)_.F(this.a.get(a[b]));delete this.a};_.Pc.prototype.getItem=function(a){return _.Oa(this.a,a)?this.a.get(a):null};
_.Pc.prototype.setItem=function(a){this.a.set(a.id(),a)};_.Oc=function(a,b){for(var c in b){var d=b[c],e=null;_.Oa(a.a,c)?(e=a.a.get(c),e.Qa=d.value,d.changed&&(e.qb=d.changed)):(e=new _.Lc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.Tc=function(){this.c=new _.B;this.a=null;this.b=!1;this.a=new Rc;this.b=!0;_.Sc(this)};_.Tc.ua=function(){return _.Tc.a?_.Tc.a:_.Tc.a=new _.Tc};_.Sc=function(a,b){var c=b||_.na;a.b?c():window.chrome.storage.local.get((0,_.r)(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};_.Tc.prototype.get=function(a){return this.a.get(a)};_.Tc.prototype.set=function(a,b){var c=_.ec();this.a.set(a,b);c.a(void 0);return c.b};_.Tc.prototype.remove=function(a){this.a.remove(a)};
_.Tc.prototype.clear=function(){this.a.clear()};var Rc=function(){this.a=window.localStorage};Rc.prototype.clear=function(){this.a.clear()};Rc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ha[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a};Rc.prototype.set=function(a,b){var c=null;b instanceof _.w&&(b=b.G,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}}; Rc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
_.Uc=function(a,b){this.b=a;this.a=b;this.constructor.Rb||(this.constructor.Rb={});this.constructor.Rb[this.toString()]=this};_.Uc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};_.K=function(a,b){_.Uc.call(this,a,b)};_.p(_.K,_.Uc);_.Vc=function(a){this.a=a};_.Wc=new _.Vc("lib");_.M=function(a){this.a=a};_.M.prototype.toString=function(){return this.a};_.Xc=new _.M("fJuxOc");_.Yc=new _.M("ZtVrH");_.Zc=new _.M("zZa4xc");_.$c=new _.M("pVbxBc");_.ad=new _.M("byfTOb");_.bd=new _.M("LEikZe");_.cd=new _.M("rJmJrc");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.dd=function(a,b){this.j=[];this.u=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.f=!1;this.e=0;this.h=null;this.q=0};_.dd.prototype.k=function(a,b){this.f=!1;_.ed(this,a,b)};_.ed=function(a,b,c){a.a=!0;a.c=c;a.b=!b;fd(a)};_.hd=function(a){if(a.a){if(!a.l)throw new gd;a.l=!1}};_.dd.prototype.g=function(a){_.hd(this);_.ed(this,!0,a)};_.id=function(a,b,c,d){a.j.push([b,c,d]);a.a&&fd(a)};
_.dd.prototype.then=function(a,b,c){var d,e,f=new cc(function(a,b){d=a;e=b});_.id(this,d,function(a){"undefined"!=typeof _.jd&&a instanceof _.jd?ic(f):e(a)});return f.then(a,b,c)};$b(_.dd);
var kd=function(a){return(0,_.Aa)(a.j,function(a){return _.ja(a[1])})},fd=function(a){if(a.e&&a.a&&kd(a)){var b=a.e,c=ld[b];c&&(_.k.clearTimeout(c.Wa),delete ld[b]);a.e=0}a.h&&(a.h.q--,delete a.h);for(var b=a.c,d=c=!1;a.j.length&&!a.f;){var e=a.j.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var l=f.call(e||a.u,b);_.n(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);ac(b)&&(d=!0,a.f=!0)}catch(q){b=q,a.b=!0,kd(a)||(c=!0)}}a.c=b;d&&(l=(0,_.r)(a.k,a,!0),d=(0,_.r)(a.k,a,!1),b instanceof _.dd?(_.id(b,
l,d),b.p=!0):b.then(l,d));c&&(b=new md(b),ld[b.Wa]=b,a.e=b.Wa)},gd=function(){_.pa.call(this)};_.p(gd,_.pa);gd.prototype.message="Deferred has already fired";gd.prototype.name="AlreadyCalledError";var md=function(a){this.Wa=_.k.setTimeout((0,_.r)(this.b,this),0);this.a=a};md.prototype.b=function(){delete ld[this.Wa];throw this.a;};var ld={};

}catch(e){_._DumpException(e)}
try{
var od;_.nd=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};od=function(a,b){for(var c=_.t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};_.qd=function(a){_.E.call(this);this.c={};this.h={};this.k={};this.e={};this.l={};this.q={};this.p=a?a.ta():new _.J;this.w=!a;this.f=null;a?(this.f=a,this.k=a.k,this.e=a.e,this.h=a.h,this.l=a.l):(0,_.m)();a=pd(this);this!=a&&(a.g?a.g.push(this):a.g=[this])};_.p(_.qd,_.E);var pd=function(a){for(;a.f;)a=a.f;return a};_.qd.prototype.get=function(a){var b=this.b(a);if(null==b)throw new rd(a);return b};
_.qd.prototype.b=function(a){for(var b=this;b;b=b.f){if(b.C)throw Error("q");if(b.c[a])return b.c[a][0];if(b.q[a])break}if(b=this.k[a]){b=b(this);if(null==b)throw Error("r`"+a);this.a(a,b);return b}return null};_.qd.prototype.a=function(a,b,c){if(this.C)c||_.F(b);else{this.c[a]=[b,!c];b=sd(this,this,a);for(c=0;c<b.length;c++)b[c].g(null);delete this.h[a]}};_.qd.prototype.u=function(){var a=_.td;if(!this.c[a])throw Error("s`"+a);var b=this.c[a];delete this.c[a];b[1]&&_.F(b[0])};
var sd=function(a,b,c){var d=[],e=a.e[c];e&&(od(e,function(a){var c;t:{for(c=a.Sb;c;){if(c==b){c=!0;break t}c=c.f}c=!1}c&&(d.push(a.Gd),_.Ba(e,a))}),0==e.length&&delete a.e[c]);return d},ud=function(a,b){a.e&&_.Qa(a.e,function(a,d,e){od(a,function(d){d.Sb==b&&_.Ba(a,d)});0==a.length&&delete e[d]})};
_.qd.prototype.n=function(){if(pd(this)==this){var a=this.g;if(a)for(;a.length;)a[0].D()}else for(var a=pd(this).g,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&"undefined"!=typeof a[0].D&&a[0].D();this.c=null;this.w&&this.p.D();ud(this,this);this.e=null;_.F(this.v);this.q=this.v=null;_.qd.t.n.call(this)};_.qd.prototype.ta=function(){return this.p};var rd=function(a){_.pa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'}; _.p(rd,_.pa);var vd=new _.Vc("fva");new _.K(vd,1);

}catch(e){_._DumpException(e)}
try{
_.Se=function(){return window.chrome.runtime.getURL("feedbackdialog.html")};
}catch(e){_._DumpException(e)}
try{
_.k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_description:{message:"Always stay connected with the new desktop app for Hangouts on ChromeOS and Windows."},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},
chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},chrome_app_signin_button:{message:"Sign in"},chrome_app_outdated_title:{message:"Update your Hangouts Chrome app"},chrome_app_outdated_detail:{message:"This app is out of date. There's a newer version available."},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_title_2:{message:"Do you want to quit Hangouts?"},chrome_app_exit_detail:{message:"You will not receive new messages or calls on this device"},
chrome_app_exit_detail_2:{message:"You can also choose to minimize it and continue to receive messages and calls."},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"},chrome_app_exit_minimize:{message:"Minimize"},chrome_app_osx_warning_message:{message:"Hangouts Chrome app is not fully supported on Mac OSX."},chrome_app_osx_warning_ack:{message:"OK, GOT IT"}};

}catch(e){_._DumpException(e)}
try{
_.Oh=function(a){for(var b=a.a.M(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.F(),type:f.type(),multiple:f.Db,disabled:!f.ba,inverse:f.zb,changed:f.qb}}return c};_.Ph=function(a,b){return _.t(b)?a.getElementById(b):b};_.S=function(a){return _.Ph(window.document,a)};_.Qh=new _.M("a");_.Rh=new _.M("b");_.Sh=new _.M("c");_.Th=new _.M("d");_.Uh=new _.M("e");_.Vh=new _.M("f");_.Wh=new _.M("g");_.Xh=new _.M("h");_.td=new _.M("i");_.Yh=new _.M("j");
_.T=function(a){var b;b=b||[];b.length||(b[0]="");var c=window.chrome.i18n.getMessage(a,b);if(c)return c;(c=(c=_.k.ace_i18n[a.toLowerCase()])?c.message:_.k.ace_i18n["MSG_"+a])&&(c=c.replace("$1",b[0]).replace("$2",b[1]).replace("$3",b[2]));return c};
}catch(e){_._DumpException(e)}
try{
var En=function(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")},Fn=function(a){_.E.call(this);this.e=_.Ec("setting",""+(0,_.m)());this.c=null;this.b=new _.I;_.G(this,this.b);this.a=new _.B;this.f=a.get(_.Xh);this.b.listen(window,"unload",this.D)};_.p(Fn,_.E);_.ga("ace.ui.SettingsDialog",Fn);_.ga("ace.ui.SettingsDialog",Fn);
Fn.prototype.h=function(){window.document.title=_.T("CHROME_EXT_SHORT_NAME");this.c=window.chrome.runtime.connect({name:this.e});var a=this;this.c.onMessage.addListener(function(b){switch(_.Hc(new _.Gc,b).a){case "focus":Gn(a);a.sendMessage("extensionLibrary",["selectTab",a.e,!0,!0]);window.focus();break;case "close":a.g()}});this.a.set("StartOnBrowserLaunch",["BrowserStartup",1]);this.a.set("StopOnBrowserClose",["Shutdown",1]);this.a.set("TopMost",["TopMost",1]);this.a.set("TrayIcon",["TrayIcon",
1]);_.nd(_.S("fieldsetDestPage"));In("legendApp",_.T("QUASAR_LEGEND_STARTUP_SHUTDOWN"));In("legendNotice",_.T("QUASAR_LEGEND_NOTIFICATIONS"));Jn(this,"StartOnBrowserLaunch",_.T("CHROME_EXT_RUN_AT_BROWSER_START"));Jn(this,"StopOnBrowserClose",_.T("CHROME_EXT_RUN_AFTER_BROWSER_CLOSE"));Jn(this,"TrayIcon",_.T("QUASAR_LABEL_TRAY_ICON"));_.Qc?Jn(this,"TopMost",_.T("CHROME_EXT_NEW_WINDOWS_TOPMOST")):Kn(this,"TopMost");_.Fc()&&Kn(this,"TrayIcon");Gn(this);var b=_.S("feedbackLink");b.innerText=_.T("CHROME_EXT_MENUTEXT_FEEDBACK");
b.href=_.Se();b=_.S("helpLink");b.innerText=_.T("QUASAR_HELP");b.href=En("https://support.google.com/hangouts?p=help&hl=%s",window.chrome.i18n.getMessage("@@ui_locale"));this.l=_.S("buttonSave");this.l.innerText=_.T("QUASAR_BUTTON_SAVE");this.b.listen(this.l,"click",(0,_.r)(this.p,this),!1);this.k=_.S("buttonCancel");this.k.innerText=_.T("QUASAR_BUTTON_CANCEL");this.b.listen(this.k,"click",(0,_.r)(this.g,this),!1)};Fn.prototype.init=Fn.prototype.h;
var Ln=function(a,b,c){var d=[];b=b+a.a.get(c)[0];a=a.a.get(c)[1];if(1<a)for(c=0;c<a;c++)d.push(_.S(b+c));else d.push(_.S(b));return d},Gn=function(a){for(var b=new _.Pc(a.f.get("settings")),c=a.a.M(),d=0;d<c.length;d++){var e=b.getItem(c[d]);if(e){var f=Ln(a,"field",c[d]);if(e.Db){var g=e.F();0<=g&&f[g]&&(f[g].checked=!0)}else f[0]&&("boolean"==e.a?e.zb?f[0].checked=!e.F():f[0].checked=e.F():f[0].value=e.F());if(!e.ba)for(e=Ln(a,"label",c[d]),g=0;g<e.length;g++)e[g]&&(e[g].disabled=!0),f[g]&&(f[g].disabled=
!0)}}},In=function(a,b){var c=_.S(a);c&&(c.innerText=b)},Jn=function(a,b,c){var d=a.a.get(b)[0];a=a.a.get(b)[1];if(1<a)for(b=0;b<a;b++){var e=_.S("label"+d+b);e&&c&&(e.innerText=c[b])}else(e=_.S("label"+d))&&c&&(e.innerText=c)},Kn=function(a,b){var c=a.a.get(b)[0],d=_.S("field"+c);(d=(c=(c=_.S("label"+c)||d)&&c.parentNode)&&c.parentNode)&&d.removeChild(c)};
Fn.prototype.p=function(){for(var a=new _.Pc(this.f.get("settings")),b=this.a.M(),c=0;c<b.length;c++){var d=a.getItem(b[c]);if(d){var e=Ln(this,"field",b[c]),f=d.F();if(d.Db){for(var g=-1,l=0;l<e.length;l++)if(e[l]&&e[l].checked){g=l;break}-1==g&&(g=0);d.Qa=g}else e[0]&&(d.Qa="boolean"==d.a?d.zb?!e[0].checked:e[0].checked:e[0].value);f!=d.F()&&(d.qb=!0,a.setItem(d))}}this.f.set("settings",_.Oh(a));this.g()};
Fn.prototype.g=function(){this.sendMessage("settingsManager",["updateSettingsFromStorage"]);window.close()};Fn.prototype.sendMessage=function(a,b,c){c=c?c:""+(0,_.m)();var d=new _.Gc;_.Ic(d,this.e,"p");null!=a&&(d.g=a);_.Jc(d,c);_.Kc(d,b);this.c&&this.c.postMessage(d.message())};
window.addEventListener("load",function(){_.Sc(_.Tc.ua(),function(){var a=new _.qd;a.a(_.Xh,_.Tc.ua());(new Fn(a)).h()})},!1);
}catch(e){_._DumpException(e)}
}).call(this,this.default_settings);
// Google Inc.
